### ISSUE TITLE
Multi pepole connection test.

### ISSUE THREAD

**Issue by gtk2k** [Unity-Technologies/com.unity.webrtc#104]
Unity.WebRTC 2.0 Preview3
Win10 Home 1909
GeForce RTX 2070 Max-Q Design

I am trying to connect multiple people (Unity Editor) (Encode Settings: 1920x1080 16Mbps)
The connection will succeed for up to 3 people, but when the 4th person connects, an error will occur in the image and Unity Editor will crash and fall.
(1People: 1PeerConnection, 1VideoStream[dynamic instatiate camera])
![VCRuntimeError](https://user-images.githubusercontent.com/309829/80358384-49fe0b80-88b7-11ea-80be-20711a3172de.png)

**Comment by karasusan** [comment]
Thanks for your report!
This issue might be the limitation of the NVIDIA graphics board.
Please see the table on the [NVIDIA web page](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix).

We will fix the crash and add the error handling for the case of reaching the limit.

**Comment by gtk2k** [comment]
Thanks!
