### ISSUE TITLE
Several Cameras

### ISSUE THREAD

**Issue by Artemu25** [Unity-Technologies/com.unity.webrtc#105]
Is there an opportunity to use several cameras for simultaneous streaming?

**Comment by karasusan** [comment]
The multi-camera feature is ready and releases soon as version 2.0.

**Comment by Artemu25** [comment]
Can you please inform how long will it take to release version 2.0.?

**Comment by Artemu25** [comment]
And 2 more questions. Can you please describe the details of this feature and what is the the difference from using just several instances of webrtc? Or maybe this feature is connected with https://github.com/Unity-Technologies/UnityRenderStreaming? And second question - can i get this feature in prerelease version and if yes, where can i find it?

**Comment by noseeevil** [comment]
Hello!

Can I add three or more cameras to "VideoStreamTrack" list?
I use the last version 2.0.0 (project UnityRenderStreaming) and I found example scene with 2 cameras, but when I try 3 or more - it breaks.

![image](https://user-images.githubusercontent.com/16321108/80721110-84111c80-8b06-11ea-8ec0-0673df8a7a40.png)

**Comment by karasusan** [comment]
> Hello!
> 
> Can I add three or more cameras to "VideoStreamTrack" list?
> I use the last version 2.0.0 (project UnityRenderStreaming) and I found example scene with 2 cameras, but when I try 3 or more - it breaks.
> 
> ![image](https://user-images.githubusercontent.com/16321108/80721110-84111c80-8b06-11ea-8ec0-0673df8a7a40.png)

I guess this issue is the same as the error you reported.
We are fixing that it throws an exception in this case.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/104

**Comment by karasusan** [comment]
https://github.com/Unity-Technologies/com.unity.webrtc/pull/111
