### ISSUE TITLE
Build fails by throwing a lot of errors.

### ISSUE THREAD

**Issue by 8o8inCodes** [Unity-Technologies/com.unity.webrtc#109]
If I run in in unity, it works. No errors.
When I build the project, it fails and throws around 80 errors like these:
![image](https://user-images.githubusercontent.com/16385213/80868496-aa1ff380-8ca3-11ea-9ad2-1db2646506e3.png)

**How to reproduce:**

- Start a fresh unity 2D project
- Open a Package Manager.
- Select "In Project"
- Click the plus button and click on "Add package from git URL..."
- Paste the git url and hit enter. Wait until it finishes and click on "Import into Project"
- Open up one of the examples, in my case "PeerConnection"
- Hit CTRL+B in order to build it.

Maybe I didn't do something right? I made sure I simply follow the installation instructions on this repository. Maybe there is some information lacking?

**Comment by karasusan** [comment]
You can download the package from Package Manager.
It may easy for you to follow the tutorial below.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/tutorial.html

**Comment by 8o8inCodes** [comment]
> You can download the package from Package Manager.
> It may easy for you to follow the tutorial below.
> https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/tutorial.html

I already have a package manager. Is webrtc package dependent on RenderStreaming?

**Comment by haydenjameslee** [comment]
I was able to solve this by changing the architecture (in the Build Settings) to x86_64.

**Comment by 8o8inCodes** [comment]
> I was able to solve this by changing the architecture (in the Build Settings) to x86_64.

Thank you, that works.
