### ISSUE TITLE
[BUG] Obsolete links in documentation 

### ISSUE THREAD

**Issue by midopooler** [Unity-Technologies/com.unity.webrtc#135]
**Describe the bug**
There are multiple Obsolete links in the documentation at the link https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Documentation~/TableOfContents.md

**Comment by karasusan** [comment]
Fixed the issue in the PR. Thanks!
https://github.com/Unity-Technologies/com.unity.webrtc/pull/136
