### ISSUE TITLE
[BUG] MediaStreamSample doesn't work

### ISSUE THREAD

**Issue by iiiyx** [Unity-Technologies/com.unity.webrtc#138]
**Describe the bug**
MediaStreamSample doesn't work. It stucks on setting peer description. 

**To Reproduce**
Just run the sample and add tracks
After that, the program will stuck on setting local peer description: `pc1.SetLocalDescription(...)`

**Expected behavior**
WebRTC connection established and media flows

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Unity Version 2019.4.1f1
 - Package version 2.0.4-preview

**Additional context**
The problem appears when there are tracks in the stream. I.e. PeerConnectionSample works because there are no tracks.

**Comment by karasusan** [comment]
We reproduced the issue and will fix it for the next version. Thanks!

**Comment by karasusan** [comment]
fixed this issue with #161.
