### ISSUE TITLE
[BUG] Crash when starting sample scene in linux

### ISSUE THREAD

**Issue by GetJon** [Unity-Technologies/com.unity.webrtc#151]
**Describe the bug**
A clean project started from the Render Streaming HDRP template crashes when pressing play on Linux. 

I suspect either a missing library: `Fallback handler could not load library /home/andrewsj/Unity/Hub/Editor/2020.1.0f1/Editor/Data/Mono/lib/libPackages/com.unity.webrtc/Runtime/Plugins/x86_64/libwebrtc.so` or insufficient official installation documentation causing me to miss out vital steps.

**To Reproduce**
Following installation instructions from: https://gamefromscratch.com/unity-release-render-streaming-over-webrtc/ for lack of anything better.
1. Go to https://github.com/Unity-Technologies/UnityRenderStreaming/releases, download latest releases
1. Go to https://github.com/Unity-Technologies/com.unity.webrtc/releases, download latest releases
1. Copy webrtc-linux.zip to /home/.../Unity/Hub/Editor/2020.1.0f1/Editor/Data/Resources/PackageManager/Editor
1. Copy com.unity.template.renderstreaming-hd-2.0.2-preview.tgz to /home/.../Unity/Hub/Editor/2020.1.0f1/Editor/Data/Resources/PackageManager/ProjectTemplates
1. Start webserver application in terminal
1. Create new unity project from the Render Streaming HDRP template
1. Enter the webserver IP and port number to the RenderStreaming gameobject's URL Signalling variable
1. Press play on the editor
1. Unity crashes

**Expected behavior**
Unity not to crash, and for the sample project to run successfully.

**Log file**
[Editor.log](https://github.com/Unity-Technologies/com.unity.webrtc/files/5015555/Editor.log)

**Crash extract**
```
Reloading assemblies for play mode.
Begin MonoManager ReloadAssembly
./Editor/Platform/Linux/UsbDevices.cpp:UsbDevicesQuery
Symbol file LoadedFromMemory doesn't match image /home/andrewsj/TT-dev/unity-projects/webrtc2/Library/PackageCache/com.unity.ext.nunit@1.0.0/net35/unity-custom/nunit.framework.dll
Native extension for LinuxStandalone target not found
Native extension for WebGL target not found
Refreshing native plugins compatible for Editor in 0.53 ms, found 1 plugins.
Preloading 1 native plugins for Editor in 0.08 ms.
[MODES] Loading mode Default (0) for mode-current-id-webrtc2
Mono: successfully reloaded assembly
Unhandled description string =
Unhandled description string -
Unhandled description string TAB
Unhandled description string TAB
Unhandled description string '
- Completed reload, in  2.242 seconds
Platform modules already initialized, skipping
Fallback handler could not load library /home/andrewsj/Unity/Hub/Editor/2020.1.0f1/Editor/Data/Mono/lib/libPackages/com.unity.webrtc/Runtime/Plugins/x86_64/libwebrtc.so
Fallback handler could not load library /home/andrewsj/Unity/Hub/Editor/2020.1.0f1/Editor/Data/Mono/lib/libPackages/com.unity.webrtc/Runtime/Plugins/x86_64/libwebrtc.so
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Signaling: Connecting HTTP http://192.168.178.50:3080
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Unity.RenderStreaming.Signaling.HttpSignaling:HTTPCreate() (at Assets/Scripts/Signaling/HttpSignaling.cs:182)
Unity.RenderStreaming.Signaling.HttpSignaling:HTTPPooling() (at Assets/Scripts/Signaling/HttpSignaling.cs:90)
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - GPU: NVIDIA Quadro P2000
 - Browser: chrome
 - Unity Version: 2020.1.0f1
 - Package version: UnityRenderStreaming 2.0.2-preview, com.unity.webrtc M84

**Comment by karasusan** [comment]
Very thanks for the reporting details of issues.

Unfortunately, the latest version of the package doesn't support the HDRP on Linux because using HDRP needs to select Vulkan as Graphics API.
Vulkan API support is on our roadmap already.

**Comment by karasusan** [comment]
@GetJon 
We fixed this issue in this PR.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/198

We will release a new version that contains this fix.
