### ISSUE TITLE
OnIceCandidate never called.

### ISSUE THREAD

**Issue by gamedolphin** [Unity-Technologies/com.unity.webrtc#17]
Following the tutorial, and the samples, setting up the project with Unity 2019.3.0a8, even after setting local description, the onicecandidate callback is never fired.

**Comment by gamedolphin** [comment]
Oh, just created a stub data channel and the ice candidates callback started firing.  Is a data channel mandatory for ice callbacks?

**Comment by karasusan** [comment]
Mm, it seems a specification of the `libwebrtc` made by Google.
But this behavior might be changed if we upgrade this library version in the future.

**Comment by karasusan** [comment]
We will upgrade `libwebrtc` version when the package release as `2.0.0`.
We would check this issue if that time comes.

**Comment by karasusan** [comment]
I investigated the issue but this is by design.
This PR is to confirm the issue.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/115

**Comment by Ma-Pe-Ma** [comment]
> 
> 
> Oh, just created a stub data channel and the ice candidates callback started firing. Is a data channel mandatory for ice callbacks?

I'm using my own signalling solution so I have to get the ice candidates through OnIceCandidate but it's never called. (The other peer is not a Unity client.)

What do you mean by stub data channel? I created one for the involved RTCPeerConnection object by the CreateDataChannel method but no succeess. Or do I have to create a channel from the remote peer too?
