### ISSUE TITLE
VideoCapturer.cpp missing in release 2.1.0

### ISSUE THREAD

**Issue by tvkamara** [Unity-Technologies/com.unity.webrtc#184]
Hi. I'm trying to build the release/2.1.0 branch. However, the file"VideoCapturer.cpp seems to be missing. This is referred to in file Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj:

`<ClCompile Include="VideoCapturer.cpp" />`

If I open release/2.0.5 the project builds fine (as the file VideoCapturer.cpp still exists in that commit).

Is the VideoCapturer.cpp (and maybe some other files) missing, or should the project build be updated in some other ways?

Thanks.

**Comment by karasusan** [comment]
We have changed the build tool to CMake.
I will add a note to README to explain how to build with CMake.

**Comment by karasusan** [comment]
@tvkamara 
I updated the [document](https://github.com/Unity-Technologies/com.unity.webrtc/blob/6d7185aca422b92e229220da25a17e3674b55dd2/Plugin~/README.md) about building plugin.


Is it useful for you?

**Comment by tvkamara** [comment]
Thank you @karasusan. I was able to build the latest version with CMake. You can mark this issue as solved.
