### ISSUE TITLE
[BUG] Changing the bitrate of a VideoStreamTrack doesn't take effect instantly 

### ISSUE THREAD

**Issue by LukasKastern** [Unity-Technologies/com.unity.webrtc#191]
**Describe the bug**
Changing the bitrate of a VideoStreamTrack doesn't take effect instantly but slowly progresses over time.
This is visually noticeable in the stream.
As an example changing the bitrate to 20000000 takes about 30 seconds:
![image](https://user-images.githubusercontent.com/40829791/93914040-3dff6400-fd06-11ea-9887-fd3d1dd7f941.png)

I'm aware that this is discussed in the closed issue #182, but since you mentioned that it has been fixed I wanted to create a new issue regarding this problem with some more details

**To Reproduce**
1. Download the 2.1.1-preview release
2. Add the following to RenderStreaming.cs  
```cs        
        private void Update( )
        {
            foreach ( var track in m_listVideoStreamTrack )
            {
                if ( !m_mapTrackAndSenderList.ContainsKey( track ) ) continue;
                ChangeVideoParameters( track, 20000000, null );
            }
        }
``` 
3. Start the web server, go into play mode and connect through chrome
4. You will notice that the quality slowly progresses to the desired bitrate over time

**Expected behavior**
VideoStreamTrack should use the set bitrate as soon as it's set

**Environment (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Unity Version [2019.4.9f1]
 - Package version [2.1.1-preview]

**Unrelated note**
The samples of the 2.1.1-preview of the UnityRenderStreaming package inside the Unity Package Manager are not the same as the samples of the Github release.

**Comment by karasusan** [comment]
I will investigate it but I think this is a default behavior by libwebrtc which made by google so it is pretty difficult to solve...

**Comment by LukasKastern** [comment]
I can't remember having the same issues with Pixel Streaming in UE4

**Comment by WaltzBinaire** [comment]
Hey everyone - 
we were able to reproduce this issue on our side. We really believe it is important to resolve this issue before adding more features. I also believe this issue is the same as #100 and #182 
Please let us know if we can assist you. We are testing a lot on our side too.

best

**Comment by LukasKastern** [comment]
I think the default bitrate in the samples is just to low to really notice it. 
I've set the bitrate to 16000000 which looks fine with my current setup but still takes anywhere from 5-10 seconds to be reached.

The interesting part is that it almost seems as the bitrate would progress to the target rate over time at a constant speed.

**Comment by WaltzBinaire** [comment]
@LukasKastern - same here - we also felt that once the bitrate is forced to go up directly - then it will go up

**Comment by karasusan** [comment]
Thanks for your report, I am seeking how to make quicker to reach the indicated value.
I am not sure which version of the libwebrtc in Unreal Engine, but I guess they have chosen to keep to use old version of the libwebrtc for stability.

**Comment by karasusan** [comment]
I found raising bitrate immediately when indicate the parameter `min_bitrate_bps` in native code.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Plugin~/WebRTCPlugin/WebRTCPlugin.cpp#L710-L711

So, I will add the parameter `minBitrate` to `RTCRtpEncodingParameters` class.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Runtime/Scripts/RTPParameters.cs#L7-L13

Is this change make you satisfied?

**Comment by karasusan** [comment]
Amazing changes in this result.
![image](https://user-images.githubusercontent.com/1132081/94138280-d6cae680-fea2-11ea-9c08-b4e2953bd8c3.png)

**Comment by LukasKastern** [comment]
I can confirm that #195 fixes the issue for me.
Thanks a lot!


![image](https://user-images.githubusercontent.com/40829791/94149641-70c96980-fe78-11ea-98ad-1702fc572d2a.png)

**Comment by WaltzBinaire** [comment]
this is an amazing result - congratz @karasusan !!!!!!!!!
