### ISSUE TITLE
[QUESTION] Audio Interface

### ISSUE THREAD

**Issue by lstemple** [Unity-Technologies/com.unity.webrtc#196]
Hi Unity, 

I would like to know how the audio should be emitted from the remote peer. Should the audio be sent directly to the output device (bypass Unity) or should it be emitted within Unity's calls to OnAudioFilterRead? 

I require Unity<->Unity audio MediaStreamTracks in my project ahead of your roadmap and am willing to contribute towards a PR.

Thank you,
Lloyd

**Comment by karasusan** [comment]
Now, we are giving priority of our developing to streaming video renderer than audio renderer.
I am afraid that maybe we can get to start the task on January.

**Comment by lstemple** [comment]
Thank you Karasusan,

In the meantime I will implement audio receiving myself as my project cannot wait until then. Given my timing limitation, I will attempt to do it in the way suggested by another user here: https://github.com/Unity-Technologies/com.unity.webrtc/issues/44#issuecomment-632490594
If I gain any useful insights, I will be sure to share them back here.

Thanks again,
Lloyd

**Comment by lstemple** [comment]
Hi Karasuasan,

Just an update on my progress -- I have begun to implement an audio render interface in the native side similar to what has already been done for the video render interface:

My new UnityAudioRenderer.h:

```
#pragma once
#include "api/media_stream_interface.h"

namespace unity {
namespace webrtc {

    namespace webrtc = ::webrtc;
    class UnityAudioRenderer;
    using DelegateOnAudioBusReady = void(*)(UnityAudioRenderer*, const void* audio_data,
                      int bits_per_sample,
                      int sample_rate,
                      size_t number_of_channels,
                      size_t number_of_frames);

    class UnityAudioRenderer : public webrtc::AudioTrackSinkInterface
    {
    public:
        UnityAudioRenderer(uint32_t id);
        ~UnityAudioRenderer();

        uint32_t GetId();

        // NOTE(Lloyd): I modelled this after DataChannelRegisterOnMessage 
        // which also overrides the callback
        void RegisterOnData(DelegateOnAudioBusReady callback)
        {
            onData = callback;
        }

        // NOTE(Lloyd): Override the callback to expose the audio data
        void OnData(const void* audio_data,
            int bits_per_sample,
            int sample_rate,
            size_t number_of_channels,
            size_t number_of_frames) override;

        DelegateOnAudioBusReady onData = nullptr;

    private:
        uint32_t m_id;
    };

} // end namespace webrtc
} // end namespace unity
```

And implementation file UnityAudioRender.cpp:
```
#include "pch.h"
#include "UnityAudioRenderer.h"

namespace unity {
namespace webrtc {

UnityAudioRenderer::UnityAudioRenderer(uint32_t id) : m_id(id)
{
    DebugLog("Create UnityAudioRenderer Id:%d", id);
}

UnityAudioRenderer::~UnityAudioRenderer()
{
    DebugLog("Destory UnityAudioRenderer Id:%d", m_id);
}

uint32_t UnityAudioRenderer::GetId()
{
    return m_id;
}

void UnityAudioRenderer::OnData(const void* audio_data, int bits_per_sample, int sample_rate, size_t number_of_channels, size_t number_of_frames)
{
    if (onData != nullptr)
    {
        onData(this, audio_data, bits_per_sample, sample_rate, number_of_channels, number_of_frames);
    }
}

}
}
```

Does this look like it would be the right way to go? I am in the process of creating the interop code as well but am not sure about the best way to poll libwebrtc for audio frame data, I believe I may need to also override `NeedMorePlayData` (audio_device_defines.h) in order to ensure that there is audio frame data I can deliver in time for each 20ms poll to OnAudioFilterRead in the managed side. 

I look forward to hearing your feedback,

Thank you,
Lloyd

**Comment by lstemple** [comment]
Hi All,

Just an update to say that I have stopped looking into supporting audio natively through WebRTC via this plugin for the time being due to the time constraints of my project. 

For now, I am using a workaround of sending audio as libopus encoded bytes (20ms at a time) via a data channel and have satisfactory results for the needs of my project (real-time audio shared between webrtc peers) -- this was made possible by another Github user's project: https://github.com/TyounanMOTI/UnityOpus

Hopefully this will help somebody in a similar situation, 
Lloyd

**Comment by peterparnes** [comment]
@lstemple Have you shared you work on this issue somewhere? I am need of sharing real-time audio as well.

**Comment by EphTron** [comment]
@peterparnes I made a small example - maybe it helps. Might not be optimal yet. 
https://github.com/EphTron/unity-webrtc-opus-audio

**Comment by karasusan** [comment]
same issue
https://github.com/Unity-Technologies/com.unity.webrtc/issues/296
