### ISSUE TITLE
Receive h264 video over webrtc

### ISSUE THREAD

**Issue by gamedolphin** [Unity-Technologies/com.unity.webrtc#20]
Hey,
I am attempting to receive h264 video over webrtc from a remote source. Signalling works and I am able to setup a data channel with the remote client (which is not unity) but the remote never adds a video track to the connection. It works when I connect to the remote through a browser. I am guessing this is because the unity client does not mention it can receive video on its offer sdp. 
How do specify this while making an offer?

**Comment by karasusan** [comment]
Hi, I am sorry for my late response.
The current version of the library doesn't support receive the video on Unity over webrtc.
I received your request and we'll try for that near future.

**Comment by gamedolphin** [comment]
Thats alright. looking forward to when its ready. Thank you.

**Comment by pierre-rouanet** [comment]
Hi @karasusan,

Any update on this issue? Do you have any idea when it will be integrated?
