### ISSUE TITLE
[BUG] 404 error on install page

### ISSUE THREAD

**Issue by cjonesy20** [Unity-Technologies/com.unity.webrtc#202]
I'd like to install this in Unity 2019.3 but the link to the Install page is 404'ing. https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Documentation~/en/install.md

From this page https://docs.unity3d.com/Packages/com.unity.webrtc@2.1/manual/index.html a link to a different Install page is also broken. 

And it's not showing up in Package Manager. Do I have to build from source to use this? Will this support streaming a webrtc video feed from a camera?

**Comment by karasusan** [comment]
Sorry I will fix this soon...

A document to install the package is here.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.1/manual/install.html
