### ISSUE TITLE
What's your guys thoughts on the com.microsoft.wetbrtc implementation?

### ISSUE THREAD

**Issue by StephenHodgson** [Unity-Technologies/com.unity.webrtc#24]
https://github.com/microsoft/MixedReality-WebRTC

What's your guys thoughts on this?
Any chance both teams can collaborate and roll things into a single package?

Sibling Issue:
https://github.com/microsoft/MixedReality-WebRTC/issues/104

**Comment by karasusan** [comment]
We are aware of various webrtc choices and that’s great for developers. 
We have no thoughts currently for the integration, but we will collaborate with other implementation owners if that seems to be the better future for renderstreaming.

**Comment by sindharta** [comment]
Closing this issue.

**Comment by StephenHodgson** [comment]
Closing because you don't want to collaborate?

**Comment by sindharta** [comment]
Our stance is still the same:
> We have no thoughts currently for the integration, but we will collaborate with other implementation owners if that seems to be the better future for renderstreaming.

**Comment by StephenHodgson** [comment]
See https://github.com/microsoft/MixedReality-WebRTC/issues/104#issuecomment-559137706
