### ISSUE TITLE
[BUG] crash in editor on vulkan hw-encoder, windows & linux, working in editor in Windows/DirectX

### ISSUE THREAD

**Issue by subjectdenied** [Unity-Technologies/com.unity.webrtc#244]
**Describe the bug**
i bought a cuda-supporting nvidia-card so i can develop my project on linux using hw-encoding with cuda

first i was quite happy, cause the sample-scene for unityrenderstreaming seems to work (even slow, there is already a linux related issue created by someone else, i will try to set the framerate as the person suggested)

however after trying my own project im working on, which uses a custom external webcam stream that sets the unity camera-texture by custom code (and optionally also uses a shader that puts the video-frame to the maincamera background - tried both variants, makes no difference), on playing the scene in the editor, i get a crash. same happens on windows using vulkan and hw-encoding, while it is working just fine using DirectX11

i have the feeling that this is somehow related to the order at how on vulkan the camera-texture is fetched or rendered, or is related to my code constantly updating the texture as it takes in a stream. cant compare this to opengl however, as there is no support so far

**stack-trace**:
Obtained 4 stack frames.
#0  0x007f5455aed1e0 in funlockfile
#1  0x007f52feb96b5a in unity::webrtc::GraphicsUtility::GetGfxRenderer()
#2  0x007f52feb9915c in ContextCreateVideoTrack
#3  0x0000004043e719 in (wrapper managed-to-native) Unity.WebRTC.NativeMethods:ContextCreateVideoTrack (intptr,string,intptr)

not related to this crash: on windows and macos, playing the scene the second time, gives me at least on 2020.2b8 (didnt try another version) an infinite "application.reload" progress-dialog, which means i have to kill unity bascially everytime i change something

also i couldnt get streaming (the sample scene) working at all, when i tried this in MacOS yesterday using latest webrtc code, resulting in just black canvases in the browser.

**Expected behavior**
no crash, and if it doesnt work for some reason, show an exception

**Environment (please complete the following information):**
 - OS: Linux Fedora 33
 - Unity Version: 2020.2b8, but happens also with current recommanded LTS (long term suprises) version
 - Package version: 2.2.0-preview

**Additional context**
for months now i work with unity, cause i took over a project. no matter what i try to do on linux with unity, there are crashes, buggy (but marketed as working) features everywhere (my favorite so far is broken webgl building, cause a compression library in the linux build was using the macos library ...). in short i spent so much time (which means money) so far, just hitting and analyzing bugs, i should get paid by unity, even if it is kinda "free" ...

do i really have to buy a windows-pc, cause your employer doesn't feel to keep budgeting high enough to fulfill quality standards for linux and vulkan, and for some amazing at-the-edge-technology which clearly is targeted at servers and therefore linux-environments? i bought some hardware today, in times of financially depressing corona - just to stumble over the next showstopper issue for my project, which is only meant as a prototype anyways. no offense to the amazing developers that do this job, but someone higher up in the hierarchy of your company seriously needs to get his/her ass kicked (TM) ...

the funny part here is, one thing that worked flawlessly in unity today, was unityhub recognizing that i use a new gpu, and the licensing server reacting to it ... sry, for the rant, but i personally reached peak desperation with unity now

**Comment by subjectdenied** [comment]
some behaviours i found now:
- the legacyrender blit script seems to hang untiy when using vulkan, but does work with opengl
- i also tried to not use this script in vulkan and just put a camerastreamer script on the main-cam, this crashes also. so i guess this is really somehow related as to when and how the constantly updated texture is fetched for the streaming

**Comment by subjectdenied** [comment]
after further investigating, i found, that this works using a standalone build on the combination:

- linux
- vulkan
- hw-encoding with cuda

as it does in windows in the editor. so it seems to be related to the player in the editor using vulkan

**Comment by karasusan** [comment]
@subjectdenied
Can you make a minimum project to reproduce the crash?

**Comment by karasusan** [comment]
@subjectdenied 
We released the new version 2.2.1 which fixes crash bugs with Vulkan API.
Please try this version and I am glad to get your feedback. Thanks.

**Comment by karasusan** [comment]
@subjectdenied
Have you tried the latest version? Thanks.
