### ISSUE TITLE
[BUG] Documentation (install version)

### ISSUE THREAD

**Issue by andybak** [Unity-Technologies/com.unity.webrtc#246]
In https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Documentation~/install.md

> Input the string below to the input field:
> com.unity.webrtc@2.1.0-preview

2.1.0 gives an error. 2.2.0 works for now but this will obviously change. The docs should probably explain where to find a valid version string. (I just used https://github.com/Unity-Technologies/com.unity.webrtc/tags )

**Comment by karasusan** [comment]
Thanks @andybak, I will fix the docs.
