### ISSUE TITLE
Changing bitrate doesn't seem to make a difference [BUG]

### ISSUE THREAD

**Issue by 8o8inCodes** [Unity-Technologies/com.unity.webrtc#247]
Using the newest webrtc package:
I've opened up one of the example scenes `MultiVideoRecieve`, started it, and it seems to be working fine.
Now I would like to decrease the bitrate in the `MultiVideoRecieve.cs` at lines where it states:

```cs
        videoStreamTrackList.Add(cam1.CaptureStreamTrack(width, height, 8000));
        sourceImage1.texture = cam1.targetTexture;
        videoStreamTrackList.Add(cam2.CaptureStreamTrack(width, height, 8000));
        sourceImage2.texture = cam2.targetTexture;
```

But didn't make a difference at all, even if I set it to something crazy like just 8, or even 0.

**Comment by karasusan** [comment]
@8o8inCodes 
The `bitrate` is not supported which the argument of CaptureStreamTrack ...
We created a sample to show how to handle a bandwidth.
https://github.com/Unity-Technologies/com.unity.webrtc/tree/release/2.2.1/Samples~/Bandwidth

**Comment by 8o8inCodes** [comment]
> @8o8inCodes
> The `bitrate` is not supported which the argument of `CaptureStreamTrack` ...
> We created a sample to show how to handle a bandwidth.
> https://github.com/Unity-Technologies/com.unity.webrtc/tree/release/2.2.1/Samples~/Bandwidth

Ohh alright, thank you!
