### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rgeorgeoff** [Unity-Technologies/com.unity.webrtc#267]
**Describe the bug**
I may be dumb, and I feel like I have run into this with unity all the time, but importing the package, works find while running, but trying to build yields assembly reference errors.

I am on version 2020.1.4f1 but also tried 2019.4.2f1 with the same error.

I went through install steps in the readme, tried refreshing all assets, restarting unity, etc. But when building I still get:

![Capture](https://user-images.githubusercontent.com/16215420/100094440-e1a3e800-2e0d-11eb-9783-d4058b300445.PNG)

I have tried building with mono 2.x and 4.0 and I am building for windows. Also in Rider, there seems to be no issue because the linking to the reference is working fine.  Ive been pounding my head on this for way too long.

**Expected behavior**
a successful build with no assembly errors

**Screenshots**
![Capture](https://user-images.githubusercontent.com/16215420/100094702-452e1580-2e0e-11eb-8d5f-1318ec9d18b8.PNG)

**Environment (please complete the following information):**
 - OS: windows
 - Unity Version: 2020.1.4f1
 - Package version: tried 2.2.0 and 2.2.1

**Comment by rgeorgeoff** [comment]
There is no issue on my mac when i set up a new project there and build one of the sample scenes.

**Comment by karasusan** [comment]
I suppose your environment has not been installed `git` command or Unity might not be able to find a path of the command.

**Comment by rgeorgeoff** [comment]
> @rgeorgeoff
> I suppose your environment has not been installed `git` command or Unity might not be able to find a path of the command.

Well, the git command worked at least to the point of it bringing it into the project, but it may have not done all the assembly references. I did see them added to the manifest.json though, so super strange it's just the windows build giving me a hard time.

**Comment by karasusan** [comment]
@rgeorgeoff
Well, have you resolved the issue yourself yet?

**Comment by rgeorgeoff** [comment]
> @rgeorgeoff
> 
> Well, have you resolved the issue yourself yet?

No but my focus is elsewhere since I could build on Mac and that was good enough for my immediate needs.  We can close the task and I can reopen later if it becomes critical? W/e you want to do.

**Comment by karasusan** [comment]
Thanks.
I will close this issue once and please reopen it if you have trouble.

**Comment by rgeorgeoff** [comment]
This was fixed by switching architecture to 64 bit in build settings btw.
