### ISSUE TITLE
[REQUEST] h.264 decode support

### ISSUE THREAD

**Issue by KGMaxey** [Unity-Technologies/com.unity.webrtc#272]
We just recently built this plugin based off of the latest iOS support that has been pushed in. We are using this to pull down WebRTC streams one direction (no need to push data up from client). We were able to transcode our h.264 to vp8 streams before streaming down to the client to be able to use the software decoder. This however leads to an additional few seconds of latency as the stream being pushed up to our servers is in h.264 already. We were just curious as to what the timeline/ roadmap is for supporting either software or hardware decode of h.264 for all platforms. I've seen mention of hardware decode support on Nvidia graphics cards in previous issues but nothing past that. We are very excited to see this plugin continue to grow and look forward to being helpful with issues and early adoption in the future. Thank you!

**Comment by karasusan** [comment]
Thank you for your feedback!
We have a plan to support the H.264 decoder using NVIDIA GPU.
We will start to develop the feature after February.

**Comment by karasusan** [comment]
memo: WRS-63

**Comment by karasusan** [comment]
https://github.com/Unity-Technologies/com.unity.webrtc/pull/654
