### ISSUE TITLE
[BUG] Both graphical APIs are required

### ISSUE THREAD

**Issue by Artemu25** [Unity-Technologies/com.unity.webrtc#282]
Does this plugin requires both graphical API's on computer - Vulkan and OpenGL, even if i'm setting one graphical API in Unity in player settings?
I've tried to launch an app with this plugin on Ubuntu 18 and got an error:
Plugins: Couldn't open /home/atour/unity-rendering-server/web-server/unity-build/test1_Data/Plugins/libwebrtc.so, error: /home/atour/unity-rendering-server/web-server/unity-build/test1_Data/Plugins/libwebrtc.so: undefined symbol: glCopyImageSubData
However, i left only Vulkan in Unity graph settings. On Ubuntu i have opengl 3, so it's obvious why app can't find method, but why it's trying to use opengl? Moreover before i've installed vulkan-mesa-utils, app also couldn't find vulkan lib.
I'm using Unity 2019.4.15

**Comment by karasusan** [comment]
I got it.
I will fix to link OpenGL library dynamically.

**Comment by AFWork1** [comment]
Hi using unity 2019.4.24f1 and  unity render streaming 3.0.0-preview.1 I also still have this issue ( undefined symbol: glCopyImageSubData) on ubuntu 18, did I overlook something or is this not fixed yet? if so what version of opengl do I have to install for it to work?

**Comment by karasusan** [comment]
memo: WRS-199

**Comment by karasusan** [comment]
@AFWork1
Right, Not fixed yet.

**Comment by AFWork1** [comment]
Any estimation on when this might get fixed? Or maybe a known workaround? im not too familiar with linux so I wouldn't know what I'd need to install for compability. But thanks regardless!
