### ISSUE TITLE
MacOS Hardware Encoding not supported

### ISSUE THREAD

**Issue by kotrs** [Unity-Technologies/com.unity.webrtc#283]
Is not possible set Remote description, when I have WebRTC initialised with HW encoding. 

Error Detail Type: Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='0'.

**Environment (please complete the following information):**
 - OS: [macOS Big Sur]
 - Unity Version [e.g. 2020.1.17]
 - Package version [e.g. 2.2.1-preview]

**Additional context**

**Comment by karasusan** [comment]
@kotrs 
Are you trying to work with the setting below?

Sender: Unity on macOS with HW encoding
Receiver: Unity on macOS with HW encoding

**Comment by kotrs** [comment]
I don't know what setting do you mean. Do you have some static sdp file for macOS ?

**Comment by eirikwah** [comment]
I get the same error, when using this configuration:

* Sender: Ubuntu 2018.4, Unity WebRTC 2.3.1, Unity 2019.4.18f1, and HARWARE encoding.
* Receiver: Safari browser (latest version) on macOS Catalina.

I do NOT get the error if the sender is macOS Catalina, hardware or software encoding.

**Comment by kannan-xiao4** [comment]
Hi @kotrs 
package version 2.2.1-preview is not supported HW Encoder on macOS.
Please use version 2.3.3-preview or later. ( supported HW Encoder on macOS that version)

@eirikwah 
I can't reproduce my environment ( on macOS BigSur)
- Sender : Ubuntu 20.04, Unity 2019.4.23f1, WebRTC 2.3.3 ( RenderStreaming 3.0.1)
- ReceiverL Safari browser on macOS BigSur

Can you check again?
