### ISSUE TITLE
Bad received video quality of web camera

### ISSUE THREAD

**Issue by kotrs** [Unity-Technologies/com.unity.webrtc#284]
**Describe the bug**
I changed sample VideoReceive for web camera source and receive.
I use WebCamTexture for creating VideoStreamTrack. 
The quality on receive rawImage game object is very bad.
I tried to set encodings parameters later on button event. But nothing changed. 

The quality is ok when I convert WebCamTexture to the plane 3D object in front of Camera and I use Camera.CaptureStream method for to create and add track.

**Environment (please complete the following information):**
 - OS: [macOS BigSur]
 - Browser [peer to peer in Unity only]
 - Unity Version [e.g. 2020.1.17]
 - Package version [e.g. 2.2.1-preview]

**Additional context**

**Comment by karasusan** [comment]
WebCamTexture has some properties for controlling quality (`requestedFPS`, `requestedWidth`, `requestedHeight`, etc).
Did you try to change them?

**Comment by kotrs** [comment]
Yes, I set it in WebCamTexture constructor. Source video looks ok, but received video doesn't.

**Comment by karasusan** [comment]
@kotrs 
I would like to know if you try with enabled `HW encoder Support`.
https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.2/manual/components.html#render-streaming-components

**Comment by kotrs** [comment]
As I wrote in my second thread. I am not able to run it with HW support on MacOS. Is not possible to set local description.

**Comment by karasusan** [comment]
@kotrs
I see. You can enable the flag using the `WebRTC.Initialize` method.
This flag changes the preferred codec to H.264.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.2/api/Unity.WebRTC.WebRTC.html#Unity_WebRTC_WebRTC_Initialize_Unity_WebRTC_EncoderType_

**Comment by kotrs** [comment]
I don't know why. But on new version 2.3 is all OK.

**Comment by karasusan** [comment]
I close this issue, please reopen it if you have another issue.
