### ISSUE TITLE
are they both supposed to be pc1?

### ISSUE THREAD

**Issue by leon-do** [Unity-Technologies/com.unity.webrtc#292]
https://github.com/Unity-Technologies/com.unity.webrtc/blob/578c53834314c3894c6f88cf0f09564b69e640f2/Samples~/DataChannel/DataChannelSample.cs#L58-L59

**Comment by karasusan** [comment]
@leon-do 
Oh, this is a typo. I will fix it soon.
Thanks

**Comment by leon-do** [comment]
awesome. thanks!
