### ISSUE TITLE
[BUG] Hardware encoder is not supported with RTX 2080 ti 

### ISSUE THREAD

**Issue by brunosimoes** [Unity-Technologies/com.unity.webrtc#293]
After updating webrtc from 2.0.0 to 2.3.0, I start getting "Hardware encoder is not supported". I am using a RTX 2080 ti.
All versions after 2.0.0 show the same error. 

ArgumentException: Hardware encoder is not supported
Unity.WebRTC.Context.Create (System.Int32 id, Unity.WebRTC.EncoderType encoderType) (at Library/PackageCache/com.unity.webrtc@2.3.0-preview/Runtime/Scripts/Context.cs:26)
Unity.WebRTC.WebRTC.Initialize (Unity.WebRTC.EncoderType type) (at Library/PackageCache/com.unity.webrtc@2.3.0-preview/Runtime/Scripts/WebRTC.cs:328)
Unity.RenderStreaming.RenderStreaming.Awake () (at Assets/Scripts/RenderStreaming.cs:82)

**Comment by karasusan** [comment]
Could you check the graphics driver version?

The required version is described here.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.2/manual/index.html#requirements

**Comment by unnamed7** [comment]
@karasusan  akemashite omedetou gozaimasu, 
I am seeing the same error on my razer laptop with onboard GTX1060, driver version 457.30, unity . Both seem to be supported on NVIDIA Video Codec SDK 9.1, unity2019.4 & 2020.2.

**Comment by brunosimoes** [comment]
Hi @karasusan I am running on driver version 465.21, DirectX12, CUDA v10.1.

**Comment by unnamed7** [comment]
@brunosimoes @karasusan 
Thanks, Bruno for the info. I installed the latest game ready driver 460.89 and errors are gone. 
You've mentioned about Cuda, I also have that installed. Maybe something in our system overwritten setting needed to make them work, I guess. Thanks again.

Takashi

**Comment by karasusan** [comment]
I close this issue, please reopen if you have another issue.

**Comment by unnamed7** [comment]
@karasusan 
This issue came back a few days after the above post. Perhaps because at home I connect the laptop to a tb to pcie chassis that holds an rtx2080 and on-road I use the onboard 1060. Switching graphic cards seem sometimes confuse the driver. It might be nvidia's problem.
