### ISSUE TITLE
[REQUEST] Unity WebRTC for IOS and Android

### ISSUE THREAD

**Issue by nsmith1024** [Unity-Technologies/com.unity.webrtc#295]
WebRTC For Unity for IOS platform and Android platform

**Comment by karasusan** [comment]
iOS platform is already supported by the latest version 2.3.
Android platform support is worked on and will be released next month.

**Comment by nsmith1024** [comment]
Ok, great, can it transmit video and voice from the phone camera to YouTube Live Stream?

**Comment by karasusan** [comment]
@nsmith1024 
Sorry, I am not sure whether you can use it with Youtube Live Stream.
I am not familiar with the tech of it, but it might be implemented on the Youtube app natively.

**Comment by nickyonge** [comment]
Hi @karasusan, just checking in - is Android support looking on track for release soon?

**Comment by karasusan** [comment]
@nickyonge 
I posted the current status here.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/91
