### ISSUE TITLE
How to receive audio in Unity

### ISSUE THREAD

**Issue by kotrs** [Unity-Technologies/com.unity.webrtc#296]
Do you have some example how to receive audio in Unity ?
I have received track kind of Audio, but I don't know how to initialise AudioClip for AudioSource component in Unity.

Thank you

**Comment by karasusan** [comment]
Receiving audio is not supported yet.
The development of this feature will be gotten started the next month.

**Comment by gamedolphin** [comment]
Hello! Is there a branch to track progress? I would also like to contribute.

**Comment by AndreGroeschel** [comment]
Hi there! Can you guys give us an update on receiving audio? Did you already start development on this?

**Comment by karasusan** [comment]
@gamedolphin
Thanks for your offer for the contribution. But we already assigned this work to @kannan-xiao4 in my team.
This task will be started in March.

**Comment by karasusan** [comment]
@AndreGroeschel 
It is not started yet. We will start it next month.

**Comment by AndreGroeschel** [comment]
@karasusan thx for the update!

**Comment by Felix-N** [comment]
@karasusan any update on this?
I'd like as well to transfer the microphone from one peer to another.
