### ISSUE TITLE
[REQUEST] Support Encoded Transform API

### ISSUE THREAD

**Issue by karasusan** [Unity-Technologies/com.unity.webrtc#305]
Encoded Transform API (renamed from Insertable Streams API)
https://w3c.github.io/webrtc-encoded-transform

The original request is [here](https://forum.unity.com/threads/synchronize-data-per-frame.1042348/).

**Comment by karasusan** [comment]
memo: WRS-160

**Comment by karasusan** [comment]
WIP 
https://github.com/Unity-Technologies/com.unity.webrtc/tree/experimental/encoded-transform

**Comment by arturomarruffovegas** [comment]
Is this gonna be available on the next version 2.4.0-exp.5?

**Comment by karasusan** [comment]
@arturomarruffovegas
Not yet, unfortunately.

**Comment by arturomarruffovegas** [comment]
Any estimated date? Also, I see that there is some work made on this repo about it, can it be used? How?

Enviado desde mi iPhone

**Comment by karasusan** [comment]
This feature have been worked in progress. We cannot say date clearly, unfortunately.

**Comment by arturomarruffovegas** [comment]
@karasusan, great, thank you! I have a project that depends on this feature, can you tell me if this is going to be released this year?

**Comment by karasusan** [comment]
@arturomarruffovegas
I can say this will be released this year. 😉

**Comment by SaIG** [comment]
At work currently also stumbled into this ... and would require this feature ... so if there are any updates on this please keep us all posted! Thanks!

**Comment by karasusan** [comment]
@SaIG
I understood many developers are waiting to release the feature.
I will prioritize to develop the feature. Thanks!
