### ISSUE TITLE
[BUG] Getting compile errors when building examples

### ISSUE THREAD

**Issue by dragonho96** [Unity-Technologies/com.unity.webrtc#307]
Hi,

I am trying to build one of the examples but getting these errors.

Anyone know how to fix this problem? 

![image](https://user-images.githubusercontent.com/72776707/106148943-04130280-61bd-11eb-9dd3-3542c7464d2e.png)

**Comment by karasusan** [comment]
You can check the tutorial document here
https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.2/manual/tutorial.html

**Comment by cdrch** [comment]
I'm having the same error. Having followed all of the tutorial instructions in the link above, I still cannot build any example or original code. It runs perfectly in-editor.

**Comment by karasusan** [comment]
@dragonho96, @cdrch 
What version of Unity are you using? Thanks.

**Comment by karasusan** [comment]
Looks like the WebRTC package is not downloaded from Package Manager.
Can you take a screenshot of the Package Manager?

**Comment by cdrch** [comment]
Unity 2019.4.19f1. Below is the PM as it appears now.

![image](https://user-images.githubusercontent.com/198655/106982363-f5cf6400-6731-11eb-8b48-f06e064ab926.png)

**Comment by cdrch** [comment]
Just attempted to build again. No dice. Note that error CS0246 (type or namespace not found) does not appear when running it in-editor, nor does Visual Studio show issues - I can clearly see it in the solution.

**Comment by karasusan** [comment]
Sorry for the late reply.
Can I have your Unity project to reproduce the issue? Thanks

**Comment by JoseManuelRasconAlcantara** [comment]
https://drive.google.com/file/d/1XS0GhBDwX5iZdHa1e97DlcJp253hL_Nf/view?usp=sharing
Same Issue here.
Have a project where only I import webrtc-2.2.1 and the example.
Althought it doesn't matter if it's 2.2.1 or 3.X.X version.
Neither it doesn`t matter if you don't download the example, because if you are using Unity.WebRTC; in your scripts it is enough for the error to appear

**Comment by karasusan** [comment]
> https://drive.google.com/file/d/1XS0GhBDwX5iZdHa1e97DlcJp253hL_Nf/view?usp=sharing
> Same Issue here.
> Have a project where only I import webrtc-2.2.1 and the example.
> Althought it doesn't matter if it's 2.2.1 or 3.X.X version.
> Neither it doesn`t matter if you don't download the example, because if you are using Unity.WebRTC; in your scripts it is enough for the error to appear

Thanks, but the issue is not reproduced on my PC...
Can I have a Editor.log?

**Comment by JoseManuelRasconAlcantara** [comment]
Yes, her you have.
https://drive.google.com/file/d/1TRaO7DCh_wG9305xoCXhftQC1CRkbpg4/view?usp=sharing

**Comment by kannan-xiao4** [comment]
Hi @JoseManuelRasconAlcantara .
I can reproduce build error on your project.
It set build Architecture `x86`, but this plugin is only support `x86_64` on windows.
Please select  `x86_64` on build setting.

I think @cdrch has same problem.

**Comment by JoseManuelRasconAlcantara** [comment]
Thanks you @kannan-xiao4 this works for me ^^
