### ISSUE TITLE
[REQUEST] RTCDataChannel.Send with offset and length parameters

### ISSUE THREAD

**Issue by RodrigoSantiago** [Unity-Technologies/com.unity.webrtc#308]
Usually the send data functionality in bytes always allows the option to re-use the same array, avoiding unnecessary copies.

**Comment by mzandvliet** [comment]
As a workaround I've been using NativeArray's Slice and ToArray methods, something like:

`var bytes = new NativeArray<byte>(buffSize, Allocator.Temp, NativeArrayOptions.UninitializedMemory);
// fill buffer and keep track of write position
var bytesArray = bytes.slice(0, writePosition).ToArray<byte>();
channel.Send(bytesArray);
bytes.Dispose();`

**Comment by karasusan** [comment]
memo: WRS-23

**Comment by karasusan** [comment]
@RodrigoSantiago
@mzandvliet
We merged the PR #556, you can try and check on the develop branch.
Could you review it?
