### ISSUE TITLE
Stereo Audio Support

### ISSUE THREAD

**Issue by aaronerod** [Unity-Technologies/com.unity.webrtc#310]
I'm not sure if I'm missing something, but I've been searching about how to stream stereo audio from Unity but couldn't  find anything related.

Currently I'm streaming the audio from unity to my server, but It's streaming mono. So I would like to know if is there a way to use stereo or if you are planning to implement this for future releases.

**Comment by karasusan** [comment]
We will check it next month.

**Comment by aaronerod** [comment]
Awesome, thanks!
