### ISSUE TITLE
[BUG] Linux 5.10 with NVIDIA GTX 1070 - Hardware encoder is not supported

### ISSUE THREAD

**Issue by bramford** [Unity-Technologies/com.unity.webrtc#321]
`ArgumentException: Hardware encoder is not supported` when starting WebRTC on Linux 5.10 with NVIDA GTX 1070.

**To Reproduce**
1. Create new project from the HD Render Streaming template
2. Open the scene `samplescene.unity`
3. Run the webserver
4. Run the player (using the play button)
5. Error:
```
ArgumentException: Hardware encoder is not supported
Unity.WebRTC.Context.Create (System.Int32 id, Unity.WebRTC.EncoderType encoderType) (at Library/PackageCache/com.unity.webrtc@2.2.1-preview/Runtime/Scripts/Context.cs:22)
Unity.WebRTC.WebRTC.Initialize (Unity.WebRTC.EncoderType type) (at Library/PackageCache/com.unity.webrtc@2.2.1-preview/Runtime/Scripts/WebRTC.cs:272)
Unity.RenderStreaming.RenderStreaming.Awake () (at Assets/Scripts/RenderStreaming.cs:82)
```

**Environment:**
- OS: Debian GNU/Linux Bullseye (11)
- Kernel: Linux 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux
- GPU: GTX 1070 8GB (Asus ROG Strix)
- Browser: Firefox 85.0.2
- Unity Version: 2019.4.20f1
- Package Version: com.unity.template.renderstreaming-hd-2.2.1-preview.tgz

Installed Packages:
* nvidia-driver 460.39-1 (includes nvidia-vulkan* of the same version)
* libcuda1 460.39-1
* libcudart11.0 11.2.72~11.2.0-2
* libc++1:amd64 1:11.0-51+nmu4
* libc++1-11:amd64 1:11.0.1-2
* libc++abi1:amd64 1:11.0-51+nmu4
* libc++abi1-11:amd64 1:11.0.1-2

**Comment by bramford** [comment]
I tried swapping from the GTX 1070 to a GTX 980 4GB. Same issue.

Also, I tried re-configuring _Graphics API for Linux_ to `OpenGLCore`. Same issue.

**Comment by bramford** [comment]
I've now tested with 2.2.2-preview (from the unity package manger) across lots of permutations of project samples:

Pipeline | URS Package Version | URS Import | Graphics API | Scene | Result
--- | ------------- | --- | -------------------- | ------------------------------ | -------
URP | 2.2.2-preview | URP | Default (OpenGLCore) | SimpleRenderStreamingURP.unity | **Failed**
URP | 2.2.2-preview | URP | Vulkan | SimpleRenderStreamingURP.unity | **Failed**
URP | 2.2.2-preview | LegacyRP | Default (OpenGLCore) | SimpleRenderStreamingLegacyRP.unity | **Failed**
URP | 2.2.2-preview | LegacyRP | Vulkan | SimpleRenderStreamingLegacyRP.unity | **Failed**
HDRP | 2.2.2-preview | HDRP | Default (Vulkan) | SimpleRenderStreamingHDRP.unity | **Failed**
HDRP | 2.2.2-preview | HDRP | OpenGLCore | SimpleRenderStreamingHDRP.unity | **Not Supported**

Note: All failures are caused by the same exception: `ArgumentException: Hardware encoder is not supported` from the same line `Unity.WebRTC.WebRTC.Initialize`

**Comment by karasusan** [comment]
Can you check the Unity detecting the graphics driver?
You can see it in `Editor.log`.

**Comment by bramford** [comment]
This is the only mention of the GPU in `Editor.log`
```
Vulkan API version 1.1.0 (1.2.155 supported by driver)
Vulkan vendor=[NVIDIA] id=[10de]
Vulkan renderer=[GeForce GTX 1070] id=[1b81]
Vulkan device type 2
Vulkan driverversion=[0x7309c000] uint=[1930018816]
Vulkan PSO: cache data not found [path=/tmp/DefaultCompany/URPStreamingSample/vulkan_pso_cache.bin]
```

**Comment by bramford** [comment]
Actually this is also shown in `Editor.log` before the log lines from my previous comment:
```
[Vulkan init] SelectPhysicalDevice requestedDeviceIndex=-1 xrDevice=(nil)
[Vulkan init] Physical Device 0x387f081af780 [0]: "GeForce GTX 1070" deviceType=2 vendorID=10de deviceID=1b81
[Vulkan init] Physical Device 0x387f081af000 [1]: "llvmpipe (LLVM 11.0.1, 256 bits)" deviceType=4 vendorID=10005 deviceID=0
[Vulkan init] Selected physical device 0x387f081af780
[Vulkan init] Graphics queue count=1
```

**Comment by bramford** [comment]
On the same exact hardware (with a different SSD as boot/root) I installed a fresh Ubuntu 18.04.5 LTS.

The URP-based URS sample works on the above Ubuntu 18.04.5 install with OpenGL and Vulkan.

The problem must be an incompatibility in my Debian installation.

**Comment by karasusan** [comment]
@bramford 
Thanks for sharing.
I suggest using Ubuntu or CentOS. I guess Debian is not supported by Unity.
https://docs.unity3d.com/Manual/system-requirements.html

**Comment by karasusan** [comment]
I am closing this issue.
If you want our help with this topic, please reopen this issue.
Thanks.

**Comment by bramford** [comment]
So in the end the cause for this issue in Debian was quite simple:

In Debian, the default closed-source NVIDIA driver package `nvidia-driver` does not include the _NVENC_ encoding/decoding suite of libraries. Ubuntu installs this alongside the other NVIDIA drivers by default.

To install the NVIDIA encoder/decoder on Debian, just `apt-get install libnvidia-encode1`.

Problem solved.
