### ISSUE TITLE
[REQUEST] Invalid references in API documentation

### ISSUE THREAD

**Issue by gtk2k** [Unity-Technologies/com.unity.webrtc#322]
バグではないのですが、コメントでちょっと気になったので報告です。
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Runtime/Scripts/RTCPeerConnection.cs#L103
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Runtime/Scripts/RTCPeerConnection.cs#L117
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Runtime/Scripts/RTCPeerConnection.cs#L131
これらのcrefに設定されているものがコードと一致していないと思いますがどうでしょう。

**Comment by karasusan** [comment]
@gtk2k 
こちらのコメントに関する報告について、提示されたリンク先が古いので類推なのですが、
`seealso` の箇所の `cref` を指摘されていますか？

**Comment by gtk2k** [comment]
あ、はい、そうです。

**Comment by karasusan** [comment]
`seealso` は関連する機能に関するリンクを提供しています。
用法は以下の通りです。
https://docs.microsoft.com/en-us/dotnet/csharp/codedoc#seealso

例えば `IceConnectionState` と `ConnectionState` はどちらも接続状態を表すプロパティですが、
用途が異なるので注意のためにリンクしています。

**Comment by gtk2k** [comment]
なるほど、ありがとうございます。
