### ISSUE TITLE
Integration with Media Server

### ISSUE THREAD

**Issue by Dorianc4** [Unity-Technologies/com.unity.webrtc#33]
Hello! I'm new in Webrtc and the way it works; my question is; can I integrate this with a media server like Kurento or Wowza?

**Comment by sindharta** [comment]
We are not familiar with either Kurento or Wowza. Perhaps you can try and let us and the community know your findings

**Comment by karasusan** [comment]
This is a general question and you can ask questions like that on [Unity Forum](https://forum.unity.com/forums/unity-render-streaming.413/).
Thanks.

**Comment by winlinvip** [comment]
Hi, you can use [SRS](https://github.com/ossrs/srs) which is a WebRTC server, which allows you to use Unity as client and deliver streams to each others.

> PS: SRS also supports coverting WebRTC to live stream, for example, to publish Unity stream to YouTube etc.

It's very easy to use, you can start SRS by docker, and there are some examples for Unity,  for details see [srs-unity](https://github.com/ossrs/srs-unity).

Bellow are some examples:

```
Unity ---WebRTC---> SRS --WebRTC--> H5/Chrome
(WebCamera and Microphone)
```

> Note: You could use other WebRTC media server and client to replace SRS and Chrome.

https://user-images.githubusercontent.com/2777660/189331198-e045aeec-ad75-447b-8143-3b6d779e8dde.mp4

> Note: The latency is extremely low, which allows you to communicate with another Unity App. For example, you can use this mode to build a metting application by Unity.

```
Unity ---WebRTC---> SRS --WebRTC--> H5/Chrome
(Game camera and voice)
```

> Note: You could use other WebRTC media server and client to replace SRS and Chrome.

https://user-images.githubusercontent.com/2777660/189329527-f7569003-f047-449e-8f48-ec59ddee60e4.mp4

> Note: A rotating cube is in the video stream, which is also the demostration of WebRTC.

https://user-images.githubusercontent.com/2777660/189353556-047025b2-2019-4c5a-a813-7a4c888840eb.mp4

> Note: Please note that we also capture the audio of game, so when we mute the H5 player there is no audio.

```
H5/Chrome ---WebRTC---> SRS --WebRTC--> Unity
```

> Note: You could use other WebRTC media server and client to replace SRS and Chrome.

https://user-images.githubusercontent.com/2777660/189331098-bd7163cf-d6b9-480c-a204-ad8b721491b6.mp4

> Note: By converting live streaming to WebRTC, you're able to play normal stream from OBS or exists stream to Unity. For example, you can view a live sport or music by Unity.
