### ISSUE TITLE
[BUG] OnRemoveTrack never triggered

### ISSUE THREAD

**Issue by unnamed7** [Unity-Technologies/com.unity.webrtc#331]
OnRemoveTrack does not work at all in this implementation.

RTCTrackEvent class returned by OnTrack has no MediaStream array in UnityWebRTC. 
On other webrtc implementations, the event has 4 properties, 
https://developer.mozilla.org/en-US/docs/Web/API/RTCTrackEvent
But in unity, the array is missing.
https://docs.unity3d.com/ja/Packages/com.unity.webrtc@2.3/api/Unity.WebRTC.RTCTrackEvent.html

This array holds the mediaStream on the otherside, that triggers the OnRemoveTrack event but because unity lacks the stream array, we have no way to attach it! 

i.e. it goes something like this in JS,
 
```
    rtcPeerConnection.ontrack = (event) => {
        console.log("Event : Track");
    let stream = event.streams[0];  // this is the one that raises the event. OnRemoveTrackを設定するのはこのstream
    stream.onremovetrack = (evt) => { //とかなんとか// };
```
But in Unity, the event returned by the PeerConnection.OnTrack event has no MediaStream[]

Please investigate, 宜しくお願い致します。

Takashi

**Comment by karasusan** [comment]
I got your issue, thanks

**Comment by karasusan** [comment]
Fixed this issue in this PR.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/354
