### ISSUE TITLE
How to receive audio?

### ISSUE THREAD

**Issue by unnamed7** [Unity-Technologies/com.unity.webrtc#332]
Hi,

I am trying to receive audio. Sending the system microphone input was possible using the AudioFilterRead, but I can't find any documentation to receive audio streams, could you please tell me a hint? (Or it hasn't been implemented yet?!?)

Cheers,

Takashi

**Comment by karasusan** [comment]
Same issue
https://github.com/Unity-Technologies/com.unity.webrtc/issues/296
