### ISSUE TITLE
An example or Document on how to

### ISSUE THREAD

**Issue by Eelam** [Unity-Technologies/com.unity.webrtc#333]
All the examples use two WebRTC instances (pc1 and pc2) in the same App. Could you please provide an example or documentation where the same App is launched twice to test the RTC communication between them?
Thanks,

**Comment by karasusan** [comment]
Have you tried the [Unity Render Streaming](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/index.html) package?

This package might provide examples of what you need.

**Comment by Eelam** [comment]
I have tried the [Unity Render Streaming](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/index.html) and it not streaming any video. The webserver.exe is running and logging the WebSocket signalling. I have tested using Unity 2019.4.18. Here, the Unity Render Streaming package (3.0.1) installs the dependencies (WebRTC and Input System). On Unity 2020.2.2 and 2020.2.6, it does not install the dependencies. It does not state that it requires dependencies. However, I installed the dependencies manually. Still not video streaming. The console is logging ‘Signaling: WS connection closed, code: 1002’ and the webserver is logging ‘GET / 200 0.693 ms - 1715’. When I click the play icon on the ‘VideoPlayerSample’, now video stream. The web server logs the following: 
‘GET /signaling/answer?fromtime=1614860575000 200 0.340 ms - 14
GET /signaling/candidate?fromtime=1614860575000 200 0.343 ms - 17
GET / 200 0.684 ms - 1715
’
I have tested the ‘http://localhost/videoplayer/index.html’ on Firefox 86 and Chrome 89.0.4, which are logging the following console output when I click the play icon.
Firefox:
•	Uncaught TypeError: videoPlayer is undefined
    <anonymous> http://localhost/videoplayer/js/main.js:16
•	Uncaught (in promise) ReferenceError: logger is not defined
    loopGetOffer http://localhost/js/signaling.js:43
    start http://localhost/js/signaling.js:29
    setupConnection http://localhost/videoplayer/js/video-player.js:135
    setupVideoPlayer http://localhost/videoplayer/js/main.js:130
    onClickPlayButton http://localhost/videoplayer/js/main.js:63
Chrome:
•	signaling.js:43 Uncaught (in promise) ReferenceError: logger is not defined
    at EventTarget.loopGetOffer (signaling.js:43)

**Comment by karasusan** [comment]
@Eelam 
Are you trying this page?
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/sample-browserinput.html

**Comment by Eelam** [comment]
Thanks,
It is working when I started the webserver.exe using ".\webserver -w" for WebSocket signaling. This information is not on the [Tutorial page](https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/tutorial.html) ("After the download is finished and a new explorer window is opened, click on webserver.exe to start Unity RenderStreaming web server.").

**Comment by karasusan** [comment]
I got it. we will fix the document for using the command-line options
