### ISSUE TITLE
[BUG] Can't run URP Demo on MacOS nor build on Linux

### ISSUE THREAD

**Issue by xavierpuigf** [Unity-Technologies/com.unity.webrtc#336]
Hi, thanks a lot for this great work. I am trying to run one of the demos provided, but I am running into issues, both when running using the editor on a MacOS, or when running using a build in Linux.

I am using Unity 2019.4.21.f1 on a macOS 11.2.1, with Render Streaming 3.0.1-preview. I am testing the demo RenderPipeline/URP. 

When I press play in the Editor, I keep getting the error 

Signaling: Connecting WS ws://localhost
Signaling: WS connection closed, code: 1006

And when I open the webplayer, I get a dark screen, and I am unable to see any of the content.

I also tried creating a build for Linux and running there, but I get the following error in the logs
```
Unable to preload the following plugins:
libwebrtc.so
Unable to load player prefs
Plugins: Couldn't open[...]/webrtcv3_Data/Plugins/libwebrtc.so, error: [...]/webrtcv3_Data/Plugins/libwebrtc.so: undefined symbol: glCopyImageSubData
(Filename:  Line: 331)

Plugins: Couldn't open [...]/webrtcv3_Data/Plugins/libwebrtc.so, error: [...]/webrtcv3_Data/Plugins/libwebrtc.so: undefined symbol: glCopyImageSubData
(Filename:  Line: 331)

Desktop is 0 x 0 @ 0 Hz
```

Any help on any of the 2 would be greatly appreciated. Is there a docker I could use to reproduce the environment setup to test this on linux?

Thank you,
Xavier

**Comment by karasusan** [comment]
`glCopyImageSubData` is in OpenGL API, Have you installed the OpenGL libraries?

**Comment by xavierpuigf** [comment]
Thanks for your help. After using nvidia Xservers, I got around this problem in OpenGL. I am still unable to visualize anything on the web browser though, neither on MacOS nor in a Linux server, where I use an x86_64 build. 

I am running the build as 
```DISPLAY=:0 ./webrtcv3.x86_64 -batchmode```

And then call the webserver using 8180 port (different than the default 80). The Unity Log is below. When I open the web browser and click **VideoPlayer Sample** I just get a black screen. Do you have any advice on what I could try? Do I need to change some setting in the URP demo to use a different port? Using the Nvidia Xserver on the same linux machine, I can run my own Unity build and retrieve images from it, but I am failing to get the WebRTC demos to work.

Thanks a lot

```
Preloaded 'libwebrtc.so'
Display 0 'VGA-1': 1024x768 (primary device).
Desktop is 1024 x 768 @ 60 Hz
Initialize engine version: 2019.4.21f1 (b76dac84db26)
[Subsystems] Discovering subsystems at path [...]/webrtcv3_Data/UnitySubsystems
GfxDevice: creating device client; threaded=0
Renderer: llvmpipe (LLVM 10.0.0, 256 bits)
Vendor:   VMware, Inc.
Version:  3.3 (Core Profile) Mesa 20.0.8
GLES:     0
 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_gpu_shader_int64 GL_AMD_multi_draw_indirect GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enh
anced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robustness GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shade
r_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_lod GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_textu
re_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_integer_mix GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_r
gtc GL_EXT_texture_compression_s3tc GL_EXT_texture_integer GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_multimode_draw_arrays GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_MESA_ycbcr_texture GL_NV_conditional_render GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_OES_EGL_image GL_S3_s3tc
OPENGL LOG: Creating OpenGL 3.3 graphics device ; Context level  <OpenGL 3.3> ; Context handle 19834976
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
FMOD failed to initialize the output device.: "Error initializing output device. " (60) 
(Filename:  Line: 1522)

Forced to initialize FMOD to to the device driver's system output rate 48000, this may impact performance and/or give inconsistent experiences compared to selected sample rate 48000 
(Filename:  Line: 1458)

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
FMOD failed to initialize the output device.: "Error initializing output device. " (60) 
(Filename:  Line: 1522)

FMOD initialized on nosound output
Disable old input system
UnloadTime: 0.737623 ms
```

**Comment by xavierpuigf** [comment]
Hi,
To clarify, this is the demo I am trying to replicate https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/tutorial.html 

Do I need to do any change if I want to test it in a different port than the default (80)? The tutorial is set to use the editor, but is there any extra step I should do if I want to use a unity build from that project?

Thanks,
Xavier

**Comment by karasusan** [comment]
> Hi,
> To clarify, this is the demo I am trying to replicate https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/en/tutorial.html
> 
> Do I need to do any change if I want to test it in a different port than the default (80)? The tutorial is set to use the editor, but is there any extra step I should do if I want to use a unity build from that project?
> 
> Thanks,
> Xavier

Yes, you need to change the port on the `Render Streaming` component in the inspector window.

**Comment by xavierpuigf** [comment]
Thanks! I am not sure where to find the port on the Render Streaming component. I see a signaling url and other components, but not the port. Looking at RenderStreaming.cs, I also do not see where the port is set. Am I looking at the right window? Image attached.
![image](https://user-images.githubusercontent.com/4203263/111162553-a1aa7180-8572-11eb-836b-71c3616f891a.png)

**Comment by karasusan** [comment]
You can set the port number to `Signaling URL` like `ws://localhost:8080`

**Comment by xavierpuigf** [comment]
Thanks, I did setup the port this way. The unity executable does not seem to be listening to this port though. My logs are the same as above. When I check the open ports, using `lsof -i -P -n` I can see that the webserver is using the right port, but I cannot find the linux executable. My operating system is Ubuntu 18.04.5 LTS.

**Comment by karasusan** [comment]
> The unity executable does not seem to be listening to this port though. 

How about it on Unity Editor? Is this issue occurring on only Unity runtime?

Additionally, according to your log, the Unity runtime uses LLVMpipe as a graphics driver.
I want you to know this driver is poor performance.

> GfxDevice: creating device client; threaded=0
> Renderer: llvmpipe (LLVM 10.0.0, 256 bits)

**Comment by xavierpuigf** [comment]
Thanks for the note on llvmpipe! I imagine it has to do with how NVIDIA drivers are installed. Would that affect the performance of simulations running without rendering? I have been trying to increase the performance of unity simulations for some time.

Regarding the Unity Editor, in my current setup I am working on a headless remote server, where I cannot install the Unity Editor. I have been trying to run the editor on my local laptop (MacBook Pro - macOS 11.2.1), but there I am getting the following connection error, regardless of which port I use:

```
Signaling: Connecting WS ws://localhost
Signaling: WS connection closed, code: 1006
```
 
Thanks a lot for following up on this. Your package would be really useful for my work.

**Comment by karasusan** [comment]
You mean running the Unity runtime that is set the headless mode on the Linux instance, right?
In the headless mode, Unity builds the runtime excluded graphics features. So the video streaming should not work.

**Comment by xavierpuigf** [comment]
Yes, my question was whether in headless mode the graphics driver should affect performance. I imagine features like shading are still being computed in headless mode, even if not rendered?

In any case, my pervious messages are running the Unity build with graphics. I have been able to run my own Unity executables in this headless server, using an X server, but I cannot get the RenderStreaming to work. As I mentioned, I can only test in the editor with a Macbook, and there I am getting connection closed with code 1006.

**Comment by karasusan** [comment]
@xavierpuigf
Sorry for late reply.
Could you try the latest version of the package?
