### ISSUE TITLE
Linux editor, webRTC lib not compatible (crash)

### ISSUE THREAD

**Issue by antoined73** [Unity-Technologies/com.unity.webrtc#355]
First of all, thank you for all your hard work to deliver this awesome package ! It will greatly enhance and ease the devlopment of our company product.

We encountered this issue when installing the WebRTC package on the linux Unity Editor :
![bugLinux](https://user-images.githubusercontent.com/3786484/113427611-a45ff000-93d5-11eb-85c2-f964d54c0c01.PNG)

It seems that the webrtc lib references a lib not present on linux systems (libc++.so).
Tested on 2 differents Ubuntu PCs, same result.

Do you have any idea how to fix this ?
Thanks

**Comment by stevenh** [comment]
Have your tried
`sudo apt install libc++-dev`

**Comment by antoined73** [comment]
**On Ubuntu - Virtual machine :**
libc++-dev installed => Linux editor crashes on launch (the editor log says it misses the cuda lib)
libcuda1-384 installed => Editor launches, can play the scene, but the editor crashes as soon as I launch a web rtc call
I think all this problems are just limitations of VMs that does not provide the NVIDIA VIDEO CODEC SDK.

**On native Ubuntu :** 
_I'm waiting my colleague to install the libc++ on a his native linux._

Thanks for the help @stevenh !

**Comment by karasusan** [comment]
Is the Unity editor detecting the graphics driver?
It can be checked by the `Editor.log`

**Comment by karasusan** [comment]
@antoined73 
Hi, any updates? Please try the latest version of the package.
If you have no problem, I will close this ticket.

**Comment by antoined73** [comment]
I have no more this issue for a while now. I guess it has been fixed !
