### ISSUE TITLE
[BUG] Hardware encode Error occurs.

### ISSUE THREAD

**Issue by gtk2k** [Unity-Technologies/com.unity.webrtc#356]
If you have hardware encoding enabled

Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid = '0'.

Error occurs.
What could be the reason for this error in the offer's setLocalDescription?

Win10 (2004)
GPU RTX2060 Max-Q Design (Note PC)

**Comment by karasusan** [comment]
@gtk2k 
In many cases, this error occurs caused by the receiver side is not supported H.264 codec.

**Comment by gtk2k** [comment]
I understand if it happens with setLocalDescription of answer, but I don't understand that it happens with setLocalDescription of offer.

**Comment by karasusan** [comment]
なるほど。オファーの時点で発生しているということですね。
受信側のコーデックの問題ではなさそうです。失礼しました。

`WebRTC.SupportHardwareEncoder` メソッドの戻り値はどうなっていますか？


I understood. You say this error occurs when creating the offer SDP.

I guess this is not a problem with the receiver's codec.
How about the return value of `WebRTC.SupportHardwareEncoder` method?

**Comment by gtk2k** [comment]
`WebRTC.SupportHardwareEncoder` is `true`.
`WebRTC.SupportHardwareEncoder` は `true` になります

**Comment by karasusan** [comment]
オファー生成時に、ピアに受信用のトラックを追加していますか？
また、ピアに対してトラックを追加しなかった場合にはエラーは発生しますか？

**Comment by gtk2k** [comment]
オファー生成直前で、RenderTextureから生成したVideoTrackを追加してます。
```
var videoTrack = new VideoStreamTrack("VideoTrack", renderTexture);
peer.AddTrack(videoTrack);
StartCroutine(createOffer());
~
```

ピアにトラックを追加しなかった場合はエラーは発生しませんでした。

**Comment by karasusan** [comment]
ありがとうございます。
`VideoStreamTrack` をピアに追加した後で、`CreateOffer` メソッドのオプションに `offerToReceiveVideo = true` を追加すると再現しました。
解決にはハードウェアデコーダ対応が必要になりますが、まだ未対応です。
受信用と送信用でトラックを複数用意すれば回避できるかもしれません。

**Comment by gtk2k** [comment]
試してみます。

**Comment by karasusan** [comment]
恐らく、SDP を作成する前に `transceiver.Direction` に `sendonly` を指定する必要があると思います。

**Comment by gtk2k** [comment]
できました。ありがとうございます。
