### ISSUE TITLE
[BUG] About Android Support

### ISSUE THREAD

**Issue by ngreedy** [Unity-Technologies/com.unity.webrtc#363]
Hi，How can I update 2.33 to M89 in unity? I can't find M89 in Unity's Package Manager
it's only up to 2.3.3-preview

![image](https://user-images.githubusercontent.com/16276531/114519145-ae55de80-9c72-11eb-86bc-151aee055af8.png)

**Comment by karasusan** [comment]
`2.4.0-exp.1` which contains libwebrtc M89  is the next version that will be released in April.

**Comment by ngreedy** [comment]
> `2.4.0-exp.1` which contains libwebrtc M89 is the next version that will be released in April.

Got it ，3q

**Comment by jeromegauzins** [comment]
@karasusan Does the Android Support will also support Mono ? or only IL2CPP ?

**Comment by karasusan** [comment]
@jeromegauzins
We support only ARM64 for Android platform so it should be built IL2CPP.

**Comment by jeromegauzins** [comment]
> @jeromegauzins
> We support only ARM64 for Android platform so it should be built IL2CPP.

Thanks for your answer and your work🙂

I would like to understand well the limitation. Where is ARM64 is required for Android ? The native android library maybe ?

I used mono to load dll at runtime, and I would like to do WebRTC streaming, that's why I cannot build IL2CPP.

**Comment by karasusan** [comment]
The native plugin is built for only ARM64, that the why we should build IL2CPP.
