### ISSUE TITLE
No option to enter server url in VideoRecieve sample 

### ISSUE THREAD

**Issue by bharathraja** [Unity-Technologies/com.unity.webrtc#374]
There is no option to enter server URL or ip/port to listen to for receiving video stream from external source into the unity webrtc. I am trying to link gstreamer webrtc bin  to the unity webrtc. The gstreamer webrtc bin will host the video to the web-browser through the server url.  "https://github.com/centricular/gstwebrtc-demos" sendrecv demo is used for pushing the video.

**Comment by bharathraja** [comment]
Did not see the unity render streaming plugin, It is present there. Thanks.

**Comment by winlinvip** [comment]
Another solution is to use WebRTC SFU server, see https://github.com/Unity-Technologies/com.unity.webrtc/issues/33
