### ISSUE TITLE
[BUG] Android Build in  2.4.0-exp.1

### ISSUE THREAD

**Issue by ngreedy** [Unity-Technologies/com.unity.webrtc#381]
Here is my config
![B3FEB469-41F0-45fe-AE6C-D32AD6F352CF](https://user-images.githubusercontent.com/16276531/116026824-fff46500-a685-11eb-8399-973ee27b6a0e.png)

I can run in windows,
but for android , when I build and run , build failed and nothing happen

Hope that helps.

**Comment by karasusan** [comment]
I have never seen these scripts. What are these?
`UnityIOSBridgeFile_AppleLogin`
`UnityIOSBridgeFile_AuthorizeCamera`
`UnityIOSBridgeFile_AuthorizeMicrophone`
`UnityIOSBridgeFile_AuthorizeGetPhotoFromLibrary`
`UnityIOSBridgeFile_AuthorizeSavePhotoInLibrary`

**Comment by ngreedy** [comment]
sorry I got the wrong log

here is the log screenshot:

![1762D2EE-3B01-4c55-9FAE-183A7D3C42DA](https://user-images.githubusercontent.com/16276531/116038633-4359ce00-a69c-11eb-80d5-d4e51a3fa9be.png)

crash when I run the game

**Comment by ngreedy** [comment]
> @ngreedy
> I have never seen these scripts. What are these?
> `UnityIOSBridgeFile_AppleLogin`
> `UnityIOSBridgeFile_AuthorizeCamera`
> `UnityIOSBridgeFile_AuthorizeMicrophone`
> `UnityIOSBridgeFile_AuthorizeGetPhotoFromLibrary`
> `UnityIOSBridgeFile_AuthorizeSavePhotoInLibrary`

These are my code， ignore

**Comment by ngreedy** [comment]
@karasusan   my phone's cpu is not compatible ?

**Comment by karasusan** [comment]
@ngreedy

> @karasusan my phone's cpu is not compatible ?
Not sure, what is your phone?

I can see `null pointer exception` in your log. I need more detail to check it...

**Comment by ngreedy** [comment]
> @ngreedy
> 
> > @karasusan my phone's cpu is not compatible ?
> 
> Not sure, what is your phone?
> 
> I can see `null pointer exception` in your log. I need more detail to check it...

Redmi K30   cpu is arm64-v8a

**Comment by ngreedy** [comment]
> @ngreedy
> 
> > @karasusan my phone's cpu is not compatible ?
> 
> Not sure, what is your phone?
> 
> I can see `null pointer exception` in your log. I need more detail to check it...

any idea for this？

**Comment by karasusan** [comment]
@ngreedy 
Unfortunately, I have no idea right now.
We don't have Xiaomi devices to reproduce the issue.

**Comment by ngreedy** [comment]
> @ngreedy
> Unfortunately, I have no idea right now.
> We don't have Xiaomi devices to reproduce the issue.

all my android phone can not work, maybe my config is wrong or something

Here is the detail log:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2020.3.1f1c1 (3e9f4b065a9d)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'Redmi/phoenix/phoenix:10/QKQ1.190825.002/V11.0.15.0.QGHCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-04-28 15:30:34+0800
pid: 11293, tid: 11323, name: UnityMain  >>> com.DefaultCompany.Game <<<
uid: 10285
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000007742457340  x1  00000076e64756ac  x2  0000000000000013  x3  737968507465476b
    x4  00000076e6475466  x5  00000077427b7eec  x6  7665447465476b76  x7  41636f7250656369
    x8  0000007742457340  x9  0000000000000000  x10 0000000000000000  x11 0000000000000000
    x12 6563697665447465  x13 72646441636f7250  x14 0000000000000133  x15 00000000000000ff
    x16 000000760af93208  x17 00000077cfdba6c0  x18 00000000ac3b7fa9  x19 00000076610fe178
    x20 00000076e67aa7b8  x21 0000007742457340  x22 0000007742457300  x23 000000774f0f8e00
    x24 00000076610fe160  x25 00000076610fe178  x26 0000000000000000  x27 0000000000000000
    x28 0000000000000000  x29 0000007660cbdf80
    sp  00000077427b7f20  lr  00000076e60476fc  pc  0000000000000000
Failed to unwind
memory near x0 ([anon:libc_malloc]):
    0000007742457320 0000007742461720 0000000000000000   .FBw...........
    0000007742457330 00000076e18d4600 0000007609e0e200  .F..v.......v...
    0000007742457340 00000076e18d4600 00000076e19f5e00  .F..v....^..v...
    0000007742457350 00000076e18d4600 00000076e18e2000  .F..v.... ..v...
    0000007742457360 00000077424617c0 0000000000000000  ..FBw...........
    0000007742457370 0000007742462210 0000000000000000  ."FBw...........
    0000007742457380 00000076e19fb700 0000000000000000  ....v...........
    0000007742457390 00000077424621c0 0000000000000000  .!FBw...........
    00000077424573a0 00000076e18d4600 00000076e18e3800  .F..v....8..v...
    00000077424573b0 0000007742461810 0000000000000000  ..FBw...........
    00000077424573c0 0000000000000000 0000000000000000  ................
    00000077424573d0 0000007742462170 0000000000000000  p!FBw...........
    00000077424573e0 0000007742462120 0000000000000000   !FBw...........
    00000077424573f0 00000076e19fba00 0000000000000000  ....v...........
    0000007742457400 00000077424620d0 0000000000000000  . FBw...........
    0000007742457410 00000077424618b0 0000000000000000  ..FBw...........

memory near x1 (/data/app/com.DefaultCompany.Game-DAfMZBcGCmJuu3TsiYrdDQ==/lib/arm64/libunity.so):
    00000076e6475688 67616d496e696168 6b760052484b7365  hainImagesKHR.vk
    00000076e6475698 4e65726975716341 6567616d49747865  AcquireNextImage
    00000076e64756a8 75516b760052484b 6573657250657565  KHR.vkQueuePrese
    00000076e64756b8 6b760052484b746e 6973796850746547  ntKHR.vkGetPhysi
    00000076e64756c8 63697665446c6163 79616c7073694465  calDeviceDisplay
    00000076e64756d8 69747265706f7250 6b760052484b7365  PropertiesKHR.vk
    00000076e64756e8 6973796850746547 63697665446c6163  GetPhysicalDevic
    00000076e64756f8 79616c7073694465 6f7250656e616c50  eDisplayPlanePro
    00000076e6475708 4b73656974726570 7465476b76005248  pertiesKHR.vkGet
    00000076e6475718 5079616c70736944 70707553656e616c  DisplayPlaneSupp
    00000076e6475728 736944646574726f 52484b7379616c70  ortedDisplaysKHR
    00000076e6475738 69447465476b7600 646f4d79616c7073  .vkGetDisplayMod
    00000076e6475748 747265706f725065 760052484b736569  ePropertiesKHR.v
    00000076e6475758 446574616572436b 6f4d79616c707369  kCreateDisplayMo
    00000076e6475768 6b760052484b6564 6c70736944746547  deKHR.vkGetDispl
    00000076e6475778 43656e616c507961 74696c6962617061  ayPlaneCapabilit

**Comment by ngreedy** [comment]
what is your phone  can run it successful ?   I can try with it

**Comment by karasusan** [comment]
- Google Pixel 4a
- Samsung Galaxy S21 5G
- Samsung Galaxy Tab S4

**Comment by ngreedy** [comment]
> @ngreedy
> 
> * Google Pixel 4a
> * Samsung Galaxy S21 5G
> * Samsung Galaxy Tab S4

maybe u can try some other phone

I have tried all the way to run it, but still not work and crash.

which  log can I offer  to help  u  locate the problem?

**Comment by karasusan** [comment]
@ngreedy 
Right, we need more varied devices.
We might need Xiaomi Redmi series devices for testing.

**Comment by ngreedy** [comment]
I have tried Samsung  Huawei  and Pixel， still not work.

So can u tell me some way to help find the problem?

log or screenshot or something else

**Comment by karasusan** [comment]
> I have tried Samsung Huawei and Pixel， still not work.

Are these the same error on all devices?

**Comment by ngreedy** [comment]
yes, it's all cause by a null pointer dereference

here is the crash log in sumsung

![DB8DF235-E37D-45c1-A107-46A5F17A7C22](https://user-images.githubusercontent.com/16276531/117612229-6f467a80-b197-11eb-93f4-2b182ff4c635.png)

**Comment by karasusan** [comment]
@ngreedy
We have tested on Pixel 4a. 
Is it not working properly on your Pixel device?

**Comment by ngreedy** [comment]
my phone is arm64-v8a 

when I build in ARMv7 ,can run successfully  but error:
`2021-05-13 14:42:43.452 15178-15203/? E/Unity: DllNotFoundException: webrtc
        at (wrapper managed-to-native) Unity.WebRTC.NativeMethods.RegisterDebugLog(Unity.WebRTC.DelegateDebugLog)
      at Unity.WebRTC.WebRTC.Initialize (Unity.WebRTC.EncoderType type) [0x0006c] in <b25d72007def4fe48b52346336316276>:0 
      at DataChannelSample.Awake () [0x00000] in <dc9dfa199fe24e339e6a0ee6dc466853>:`

when I build in ARM64 ,it's crash ,
still  a null pointer dereference  like above 

maybe it's compatibility  problem , hope these log can help .

I give up . 

life is so hard man.

**Comment by 4litasci** [comment]
@ngreedy  I had the similar issue. Mine is gone when I remove vulkan graphic api. Can you try without vulkan api. My device is Xiaomi Mi 9T

**Comment by ngreedy** [comment]
> vulkan api

that's worked!

u r so amazing !  u know u just save my life!

thank u so much ! !

**Comment by ngreedy** [comment]
> @ngreedy I had the similar issue. Mine is gone when I remove vulkan graphic api. Can you try without vulkan api. My device is Xiaomi Mi 9T
> 
> Note: When i check auto graphics api, also can be installed succesfully. Before it was unchecked auto graphics api and Vulkan was at the top.

that's worked!

u r so amazing ! u know u just save my life!

thank u so much ! !

**Comment by karasusan** [comment]
@4litasci @ngreedy 
Thank you so much for sharing the issue.
I will check the graphics settings you mentioned.

**Comment by antoined73** [comment]
I'm on 2.4.0-exp2 with unity 2020.3.9f1.
My Android app was crashing at start. Thanks to your comment @4litasci, I managed to make it work !
Same case as you, Vulkan was on top, I checked auto graphics API and now it runs fine !
(The phone is a Huawei P30 Pro, Android 10, Huawei Kirin 980 as processor)
