### ISSUE TITLE
[BUG] Error While Building Android (unity 2019.4.8f)

### ISSUE THREAD

**Issue by ArcherFsec** [Unity-Technologies/com.unity.webrtc#387]
Unity 2019.4.8f Does not get build on android (or any other platforms)
Cant Find all references 

Error Code : CS0246 

P.S: Please Help me , I got bald Because I started to digging up my hair. I started smoking very bad and I got Lung cancer
and I going to die soon . please help me I do not want to die before fixing this bug. My wife is getting divorce because 
I cant fix this bug. she thinks I am Weak.

PS2: I told her its not a bug , its a feature...

**Comment by karasusan** [comment]
@ArcherFsec 
Which version of the package are you using?

**Comment by ArcherFsec** [comment]
> @ArcherFsec
> Which version of the package are you using?
Im using unity 2019.4.8f

**Comment by karasusan** [comment]
@ArcherFsec 
Could you give me a screenshot of the console log?

**Comment by JoseManuelRasconAlcantara** [comment]
Same here.
![Captura de pantalla 2021-05-31 111101](https://user-images.githubusercontent.com/59653352/120170304-20718b00-c201-11eb-8432-39cd9fa60dc4.png)

**Comment by karasusan** [comment]
@JoseManuelRasconAlcantara
It looks the WebRTC package is not installed correctly.

**Comment by JoseManuelRasconAlcantara** [comment]
I used the package manager to install webrtc and after I replace the webrtc 2.4.0-exp2 in to the package. It's work for me in Windows build but I need the android build. What have I do wrong?

**Comment by gtk2k** [comment]
@JoakimMellergardUnity 
Currently Android support only ARM64

**Comment by JoseManuelRasconAlcantara** [comment]
I reinstalled webrtc and now it work, thanks ^^

**Comment by karasusan** [comment]
@ArcherFsec
Can I close this ticket? Thanks.

**Comment by JoseManuelRasconAlcantara** [comment]
> @ArcherFsec Can I close this ticket? Thanks.

-Yes
