### ISSUE TITLE
Limitations and supported platforms

### ISSUE THREAD

**Issue by drejx** [Unity-Technologies/com.unity.webrtc#39]
Hello,

Regarding this note on the main page:

> This package uses GPU hardware acceleration for video encoding, so it only runs on graphics cards that support NVIDIA VIDEO CODEC SDK.

Does it mean this SDK will only run on Nvidia devices, or that it will only have hardware acceleration if an Nvidia GPU is present, but then fallback on software encoding/decoding if not present?

**Support for Platforms**
If I understand correctly this only works on Windows and Linux?  I'm interested in when support for iOS and Android is planned.  Curiously is it building the iOS and Android versions of the official Google libwebrtc library that is the main blocking item?

Thanks,
Andrej

**Comment by drejx** [comment]
Hello, just sending a friendly ping to see if anyone could reply :)

**Comment by karasusan** [comment]
Sorry for the late reply.

The current version of the package only runs on NVIDIA devices.
We are working on the feature that developers can select the encoders from options. 
In addition, we have a plan that adds the software encoder.

Next version, we will add Linux to the support platform.
I would like to support iOS and Android but these are not on our roadmap.

**Comment by drejx** [comment]
Thank you! :)
