### ISSUE TITLE
Removing Offer options for audio/video breaks my use case.

### ISSUE THREAD

**Issue by Logicator** [Unity-Technologies/com.unity.webrtc#390]
First off, thank you and your team working on this package. I look forward to its continued development!

For my issue, the removal of the options to send audio or video breaks my use case for this package. The implementation of our signaling server (mediasoup, an SFU) relies on 1-way webRTC connections with clients being either sendonly or recvonly with audio/video options on both ends. Can you please put these options back in?

Thanks again.

**Comment by gtk2k** [comment]
@Logicator
If you use addTransceiver () instead of addTrack (), you can connect in receive-only / send-only use cases.

**Comment by Logicator** [comment]
> @Logicator
> If you use addTransceiver () instead of addTrack (), you can connect in receive-only / send-only use cases.

I'll give it a shot and report back how it goes. Thanks!
