### ISSUE TITLE
[BUG] Failed to set local video description recv parameters for m-section with mid='video'.

### ISSUE THREAD

**Issue by tdowdle-aicradle** [Unity-Technologies/com.unity.webrtc#391]
**Describe the bug**

I am getting an error trying to initiate a PeerConnection with a Janus WebRTC server.  After setting the remote description, and creating an answer the following error while setting the local description:

> Error Detail Type: Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='video'.

The Answer Desc sdp consists of:

> v=0
> o=- 6233289635512951650 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE audio video
> a=msid-semantic: WMS
> m=audio 9 UDP/TLS/RTP/SAVPF 111
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:azh3
> a=ice-pwd:abcdefghijklmnop
> a=ice-options:trickle
> a=fingerprint:sha-256 5E:BC:C6:4B:3B:F7:1E:FD:55:0E:2D:BB:25:21:F9:8E:C3:34:06:87:60:C8:7A:C1:0F:1D:73:9E:73:7B:67:10
> a=setup:active
> a=mid:audio
> a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
> a=recvonly
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=fmtp:111 minptime=10;useinbandfec=1
> m=video 9 UDP/TLS/RTP/SAVPF 0
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:azh3
> a=ice-pwd:abcdefghijklmnop
> a=ice-options:trickle
> a=fingerprint:sha-256 5E:BC:C6:4B:3B:F7:1E:FD:55:0E:2D:BB:25:21:F9:8E:C3:34:06:87:60:C8:7A:C1:0F:1D:73:9E:73:7B:67:10
> a=setup:active
> **a=mid:video**
> a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
> a=recvonly
> a=rtcp-mux

**Environment:**
 - OS: iOS
 - Unity Editor
 - Unity Version 2020.3.4f1]
 - Package version [2.4.0-exp.1]

**Additional context**
I attempted to reproduce this by hardcoding the description values, but ran into "Local fingerprint does not match identity" issues.

**Comment by karasusan** [comment]
Are you trying to integrate with Janus SFU? It is so interesting for me.
I suppose you need to check the `RTCRtpTransceiver.direction` set the correct value.
And two peers must have available codecs for encoder/decoder. You can check available codecs using `RTCRtpSender.GetCapabilities()` static method.

**Comment by karasusan** [comment]
This topic might be useful for you.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/390

**Comment by tdowdle-aicradle** [comment]
> .GetCapabilities()

Thank you @karasusan  for getting back to me.

Sorry as my answer may not be as hoped.  But we are not integrating with Janus SFU.  Rather I'm just trying to retrieve a video stream from our Janus WebRTC server.

Pardon my ignorance when it comes to WebRTC, hopefully my report below will make sense.  

Once I set the remote description on the peer connection.  If I call GetTransceivers there are two available.  Checking their direction they are both set to RecvOnly.  I believe that is what I want if I'm just looking to play a video stream from Janus correct?

Because this error happens when I set the local description, the connection to the Janus stream hasn't finalized yet, so I don't have access to any tracks at that point.  It looks like the GetCapabilities call requires a track.  

Any other thoughts on what might be going on?

**Comment by gtk2k** [comment]
@tdowdle-aicradle 
If you only want to receive, I don't think you need to code anything about Transceiver. Once you've set up an OnTrack event handler for your peer, you can negotiate (offer / answer) and the OnTrack event will be called.
I think the error mentioned in the first post is probably because the codec is H264. If possible, change the video codec to VP8 and try again.

**Comment by tdowdle-aicradle** [comment]
> @tdowdle-aicradle
> If you only want to receive, I don't think you need to code anything about Transceiver. Once you've set up an OnTrack event handler for your peer, you can negotiate (offer / answer) and the OnTrack event will be called.
> I think the error mentioned in the first post is probably because the codec is H264. If possible, change the video codec to VP8 and try again.

Thank you, we are attempting to receive a H.264 encoded stream.  So H.264 decoding support is likely the issue here.

This appears to be on the roadmap:

https://github.com/Unity-Technologies/com.unity.webrtc/issues/272

Are you able to provide an estimated completion date on this?

**Comment by karasusan** [comment]
@tdowdle-aicradle
H.264 decoder is currently not supported on Linux and Windows platforms.
I can not say the completion date clearly but it should be in this year.

**Comment by AshkanZirakzadeh** [comment]
>
> H.264 decoder is currently not supported on Linux and Windows platforms.
> I can not say the completion date clearly but it should be in this year.

@karasusan 
I have tried `RTCRtpSender.GetCapabilities()` on my Android and iOS phones using 2.4.0-exp.2 with Unity 2020.8.3f1 and the only codecs they seems to support is: 

- VP8
- VP9
- rtx
- AV1X
- red
- ulpfec

Have I made a mistake somewhere or is H.264 not supported on Android/iOS either?

**Comment by Logicator** [comment]
I have a similar issue to @tdowdle-aicradle where I am using an SFU, [mediasoup](https://mediasoup.org/), and unable to receive video. The sfu is able to receive video from unity, though.

I checked and made sure the sfu is sending VP8 video and it is. I've tested sending video through multiple devices, a webcam and android device.

As @gtk2k suggested I'm not using any transceivers for the incoming video, only listening for the addtrack events, which do trigger and I handle the same as other examples.

I've tried to display the decoded video on a windows machine and an android device and it's not able to in both cases.
I set breakpoints in the WebRTC and VideoStreamTrack scripts and the updates are definitely being called. However, when outputting the stats of the incoming track I see no frames are being received. This leads me to thinking there's either an issue with the sfu not sending the video (unlikely imo), a problem with the sdp and the incoming video is not being handled appropriately, or something else I'm not thinking of...

Here is the sdp offer Unity is receiving

> v=0
o=mediasoup-client 10000 1 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-lite
a=fingerprint:sha-512 BD:4B:CD:1E:0F:FE:D6:6F:ED:59:F7:55:A0:E6:29:B2:14:27:3C:D2:27:1C:C1:6E:C8:39:C2:D9:C5:F9:16:43:42:96:EF:07:E1:EA:80:DB:AD:03:75:BE:D1:09:DF:2B:EF:86:A3:B0:44:62:C7:3E:01:6F:26:7D:B4:FB:7D:9B
a=msid-semantic: WMS *
a=group:BUNDLE 0
m=video 7 UDP/TLS/RTP/SAVPF 101 102
c=IN IP4 127.0.0.1
a=rtpmap:101 VP8/90000
a=rtpmap:102 rtx/90000
a=fmtp:102 apt=101
a=rtcp-fb:101 nack 
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 transport-cc 
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:7 urn:ietf:params:rtp-hdrext:framemarking
a=extmap:11 urn:3gpp:video-orientation
a=extmap:12 urn:ietf:params:rtp-hdrext:toffset
a=setup:actpass
a=mid:0
a=msid:78ee3461 78ee3461-video
a=sendonly
a=ice-ufrag:39obxesi4rsxa9tt
a=ice-pwd:cu9o6zt79ohmfy22xzypnwy82xqfcjfb
a=candidate:udpcandidate 1 udp 1076558079 13.82.220.53 46829 typ host
a=candidate:tcpcandidate 1 tcp 1076302079 13.82.220.53 40409 typ host tcptype passive
a=end-of-candidates
a=ice-options:renomination
a=ssrc:777834196 cname:Ms7d3Q1z3LI2keSu
a=ssrc:777834197 cname:Ms7d3Q1z3LI2keSu
a=ssrc-group:FID 777834196 777834197
a=rtcp-mux
a=rtcp-rsize

**Comment by juju812** [comment]
@tdowdle-aicradle @karasusan 
For h264 Nv decoder is currently not supported by Unity, one workaround is to **re-complie libwebrtc and add h264 software codec support**. After that when HW encoding enabled, there's **Nv HW encoder + FFmpeg SW decoder** for h264 in unity.

Here's one snippet of compile cmd to enable h264 in libwebrtc of windows:

```batch
call gn.bat gen %OUTPUT_DIR% --root="src" --args="is_debug=%%j is_clang=false target_cpu=\"%%i\" rtc_include_tests=false rtc_build_examples=false proprietary_codecs=true rtc_use_h264=true ffmpeg_branding=\"Chrome\" treat_warnings_as_errors=false symbol_level=0 enable_iterator_debugging=false"
```

BTW, compling libwebrtc really **sucks**, and it could be a long story to handle variable errors happened while compling.
