### ISSUE TITLE
[BUG] On my Android phone, the example of WebRTC running MultiplePeerConnections does not work. Can you help me see why?

### ISSUE THREAD

**Issue by laoyigrace** [Unity-Technologies/com.unity.webrtc#398]
**Describe the bug**
Android phone: Galaxy A90 5G
Android phone model: SM-A9080
Android version: Android 11
Unity webrtc version: 2.4.0-exp.1

I'm running webrtc on an android phone with multiple peer-to-peer connections and not working, can you help me see why?

The error log is as follows:
2021/05/17 16:51:51.936 818 24904 INFO SENSOR - HAL Handle _sns_client_event:660,[0][40869] Accelerated Sample [0.005,0.232,9.950]8614147778621142
2021 / 05 / 17 16:51:51.999 818 24456 information sensor-hal handle_sns_std_sensor_event: 207, optical _cct:ts=861414843617871 ns . Value = [38.000000, 38.000000, 106.000000, 72.000000, 46.000000, 127.000000, 1.000000, 0.000000, 0.000000, 11.000000]
2021 / 05 / 17 16:51:52.518 21560 21560 Information Content Capture Service Unbind from com.samsung.android.smartsuggestions.services.ContentCaptureService
2021 / 05 / 17 16:51:52.522 1062 1062 Information Activity Manager Changes 5 to 10, 7 to 0 in 10210 Caller=com.android.server.am.Oom adjuster.updateOomAdj Lock: 399 com.android.server.am.Oom adjuster.updateOomAdj Lock: 446 com.android.server.am.Oom adjuster.updateOomAdj Lock: 332 com.android.server.am.ActivityManagerService.updateOomAdj Lock: 21180 com.android.server.am.ActiveServices.remoConnection Lock: 3825 com.android.server.am.ActiveServices.unbindServiceLocked:2434 com.android.server.am.ActivityManagerService.unbindService:18063
2021 / 05 / 17 16:51:52.549 2074 2256 Debug Network Controller .SecMobileSignalController(0/2147483647)onSignalStrengths Change Level = 4
2021 / 05 / 17 16:51:52.550 2074 2256 Debugging Network Controller .SecMobileSignalController(0/2147483647) Show Emergency Signal Bar Only [true][true]
2021 / 05 / 17 16:51:52.551 2074 2256 Debug move signal icon selector getDataIconGroup(): 0
2021 / 05 / 17 16:51:52.551 2074 2256 Debug Mobile Signal Icon Selector getCMCCDataIconGroup(): 0
2021 / 05 / 17 16:51:52.551 2074 2256 Debug Mobile Signal Icon Selector getCHNDataIconGroup(): 0
2021 / 05 / 17 16:51:52.694 1062 2113 Detailed Mdnie Scene Control Service Burn _in_prevention_mode()mBrightnessAllAppServerState:true, Enabled: true, mBurnInDisableAppEnabled: false, m Auto Brightness Mode: false, m High Brightness Mode Enabled: false, mBurnInPreventionACL:false, Platform Brightness Value: 127, Burn_IN_Prevent_Support_Value: 143, mBurnIn Prevention Enable: false, mGameApp Initiator: false
2021 / 05 / 17 16:51:52.694 1062 2113 Detailed Mdnie Scenario Control Service Disable Anti-Aging Mode
2021 / 05 / 17 16:51:52.695 1062 2113 Debug Sem Display Solution Manager Service uid: 1000, pid: 1062, Name: Burn_Prevent_Off
2021 / 05 / 17 16:51:52.696 1062 2113 Debug Sem Display Solution Manager Services Where: Application Content: Default setScreenBrightnessScaleFactor(1.0), mBrightness Compensation: 1.0, PMS Value: 1.0
2021 / 05 / 17 16:51:52.696 1062 2113 Debug PowerManagerService [api] set Screen Luminance Scale Factor: Scale Factor: 1.0 (uid: 1000 pid: 1062)
2021 / 05 / 17 16:51:52.696 1062 2113 Debug Sem Display Solution Manager Service Normal Mode Setting Multi-screen Brightness, Application, Default, 1.0
2021 / 05 / 17 16:51:52.731 706 Error Audit Type = 1400 Audit (1621241512.715:20477):avc:pid=1062 com=43464D532048616E646C6572205468 Name = "Retask _cpu"dev="sysfs"ino=79257 sccontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass= File Permission =0 SEPF_SM-A9080_11_0008 Audit Filter
2021 / 05 / 17 16:51:52.732 706 Error Audit Type = 1300 Audit (1621241512.715:20477):Arch=c00000b7 syscall=56 Success = None Exit =-13 a0=ffffffff9c a1=7536f068b0 a2=0 a3=0 Project =0 ppid=748 pid=1062 aid=4294967295 uid=1000 gid=1000 Euid=1000 suid=1000 fsuid=1000 geid=1000 sgid=1000 fsgid=1000 tty= (none) ses=4294967295 Communication =43464D532048616E646C6572205468 exe="/system/bin/app_process64"subj=u:r:system_server:s0 Key = (empty)
2021 / 05 / 17 16:51:52.733 706 Error Audit Type = 1327 Audit (1621241512.715:20477): proc title = "system_server"
2021 / 05 / 17 16:51:52.935 706 Error Audit Type = 1400 Audit (1621241512.915:20478):avc:pid=1062 com=43464D532048616E646C6572205468 Name = "Retask _cpu"dev="sysfs"ino=79257 sccontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass= File Permission =0 SEPF_SM-A9080_11_0008 Audit Filtering
2021 / 05 / 17 16:51:53.345 2074 2074 Debugging system UI-operator getCarrierWifiIcon: connection info == null
2021 / 05 / 17 16:51:53.627 902 1697 Debug DlbDap2 process () Called [161500] times, input channel mask 0x3 (processing mode = 10)
2021 / 05 / 17 16:51:53.52 706 Error Audit Type = 1400 Audit (1621241513.735:20482):avc:pid=1062 com=43464D532048616E646C6572205468 Name = "Retask _cpu"dev="sysfs"ino=79257 sccontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass= File Permission =0 SEPF_SM-A9080_11_0008 Audit Filtering
2021 / 05 / 17 16:51:53.754 706 Error Audit Type = 1300 Audit (1621241513.735:20482):Arch=c00000b7 syscall=56 Success = None Exit =-13 a0=ffffffff9c a1=7536f068b0 a2=0 a3=0 Project =0 ppid=748 pid=1062 aid=4294967295 uid=1000 gid=1000 Euid=1000 suid=1000 fsuid=1000 geid=1000 sgid=1000 fsgid=1000 tty= (None) ses=4294967295 Communication =43464D532048616E646C6572205468 exe="/system/bin/app_process64

**Comment by karasusan** [comment]
Hi, I can not determine this issue from the error log.
Is this a crash bug?

This video is on my device Google Pixel 4a.
https://user-images.githubusercontent.com/1132081/118467550-d5ef0980-b73e-11eb-979b-a3571110201c.mp4

**Comment by laoyigrace** [comment]
@karasusan  Logs are mainly from Android logcat.

2021/05/17 18:59:10.545 1062 6581 Debug SemGameManager getGMSBinder(), begin
2021/05/17 18:59:10.548 1062 6581 Debug SemGameManager getGMSBinder(), successful: true
2021/05/17 18:59:10.548 1062 6581 Debug GameManagerService identifyGamePackage. com.huawei.rtcDemo, mCurrentUserId: 0, callerUserId: 0
2021/05/17 18:59:10.548 1062 6581 Debug PkgDataHelper getGamePkgData(). com.huawei.rtcDemo
2021/05/17 18:59:10.722 902 1697 Debug DlbDap2Process process() called [201500] times with input channel mask 0x3 (ProcessingMode=10)
**2021/05/17 18:59:10.756 706 706 Error audit type=1400 audit(1621249150.745:21623): avc:  denied  { read } for  pid=1062 comm=43464D532048616E646C6572205468 name="heavy_task_cpu" dev="sysfs" ino=79257 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 SEPF_SM-A9080_11_0008 audit_filtered
2021/05/17 18:59:10.756 706 706 Error audit type=1300 audit(1621249150.745:21623): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7536f068b0 a2=0 a3=0 items=0 ppid=748 pid=1062 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm=43464D532048616E646C6572205468 exe="/system/bin/app_process64" subj=u:r:system_server:s0 key=(null)
2021/05/17 18:59:10.756 706 706 Error audit type=1327 audit(1621249150.745:21623): proctitle="system_server"
2021/05/17 18:59:10.960 706 706 Error audit type=1400 audit(1621249150.945:21624): avc:  denied  { read } for  pid=1062 comm=43464D532048616E646C6572205468 name="heavy_task_cpu" dev="sysfs" ino=79257 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 SEPF_SM-A9080_11_0008 audit_filtered
2021/05/17 18:59:10.960 706 706 Error audit type=1300 audit(1621249150.945:21624): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7536f068b0 a2=0 a3=0 items=0 ppid=748 pid=1062 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm=43464D532048616E646C6572205468 exe="/system/bin/app_process64" subj=u:r:system_server:s0 key=(null)
2021/05/17 18:59:10.960 706 706 Error audit type=1327 audit(1621249150.945:21624): proctitle="system_server"
2021/05/17 18:59:11.194 1062 1987 Debug PkgPredictorService-NapPreloadController [ML] Sent pkg = com.sec.android.app.clockpackage uid: 0 type: booster**
2021/05/17 18:59:11.630 668 668 Info io_stats !@   8,0 r 161243 9919444 w 251407 10702268 d 202045 15017628 f 232746 286418 iot 427440 232365 th 102400 0 0 pt 0 inp 0 0 271946.195
2021/05/17 18:59:11.780 706 706 Error audit type=1400 audit(1621249151.765:21628): avc:  denied  { read } for  pid=1062 comm=43464D532048616E646C6572205468 name="heavy_task_cpu" dev="sysfs" ino=79257 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 SEPF_SM-A9080_11_0008 audit_filtered
2021/05/17 18:59:11.780 706 706 Error audit type=1300 audit(1621249151.765:21628): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7536f068b0 a2=0 a3=0 items=0 ppid=748 pid=1062 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm=43464D532048616E646C6572205468 exe="/system/bin/app_process64" subj=u:r:system_server:s0 key=(null)
2021/05/17 18:59:11.780 706 706 Error audit type=1327 audit(1621249151.765:21628): proctitle="system_server"
2021/05/17 18:59:11.899 2074 2074 Debug SystemUI-Operator getCarrierWifiIcon : connectionInfo == null
2021/05/17 18:59:11.909 1062 1887 Debug InputReader Btn_touch(4): value=1 when=271946.473903
