### ISSUE TITLE
[BUG] [iOS] Multiple errors when validating on TestFlight

### ISSUE THREAD

**Issue by vl4dimir** [Unity-Technologies/com.unity.webrtc#404]
**Describe the bug**
The package works as expected when running on an iOS device, however when submitting the built app to TestFlight it gets rejected with multiple validation errors:

<img width="623" alt="testflight-error-1" src="https://user-images.githubusercontent.com/206409/118803176-5464bc00-b8a3-11eb-8ba0-4c783f157117.png">
<img width="624" alt="testflight-error-2" src="https://user-images.githubusercontent.com/206409/118803224-62b2d800-b8a3-11eb-858a-341661ef9296.png">
<img width="606" alt="testflight-error-3" src="https://user-images.githubusercontent.com/206409/118803237-68a8b900-b8a3-11eb-81bc-35b74b40d63e.png">

This is a showstopper on iOS. The app can not be submitted to the App Store if it can't get through validation.

**To Reproduce**

1. Build any iOS project with com.unity.webrtc included.
2. Archive the build in Xcode (menu: Product → Archive).
3. In organizer, select the archive file and click the Validate button, then click through the dialogs (you need a valid Apple Developer account for this).

**Expected behavior**

The validation passed without any errors and warnings and is accepted by TestFlight.

**Environment (please complete the following information):**
 - OS: iOS
 - Unity Version: 2020.3.7f1
 - Package version: 2.3.3-preview

**Comment by karasusan** [comment]
Thanks. I am checking it.

**Comment by karasusan** [comment]
There is a fix for one of them.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/384

**Comment by karasusan** [comment]
I fixed the bitcode error
https://github.com/Unity-Technologies/com.unity.webrtc/pull/405

**Comment by karasusan** [comment]
@vl4dimir 
This framework contains the x86_64 architecture for iOS simulator, so you must run the command below.
We will add this to the package document.
 
```
lipo -remove x86_64 Runtime/Plugins/iOS/webrtc.framework/webrtc -o Runtime/Plugins/iOS/webrtc.framework/webrtc
```

**Comment by karasusan** [comment]
Related issue.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/405
