### ISSUE TITLE
[BUG]unable to run webrtc demo on an android phone

### ISSUE THREAD

**Issue by laoyigrace** [Unity-Technologies/com.unity.webrtc#407]
**Describe the bug**
Android phone: Galaxy A90 5G
Android phone model: SM-A9080
Android version: Android 11
Unity webrtc version: 2.4.0-exp.1

I'm running webrtc on an android phone with multiple peer-to-peer connections and not working, can you help me see why?

not found webrtc, Do you need to perform any configuration during compilation?

2021/05/25 17:19:57.535 9832 20091 Error Unity Unable to find webrtc
2021/05/25 17:19:57.565 9832 20091 Error Unity DllNotFoundException: webrtc
2021/05/25 17:19:57.565 9832 20091 Error Unity   at (wrapper managed-to-native) Unity.WebRTC.NativeMethods.RegisterDebugLog(Unity.WebRTC.DelegateDebugLog)
2021/05/25 17:19:57.565 9832 20091 Error Unity   at Unity.WebRTC.WebRTC.Initialize (Unity.WebRTC.EncoderType type) [0x0007f] in D:\work\unity\1111111\Library\PackageCache\com.unity.webrtc@2.4.0-exp.1\Runtime\Scripts\WebRTC.cs:333 
2021/05/25 17:19:57.565 9832 20091 Error Unity   at MultiplePeerConnectionsSample.Awake () [0x00001] in D:\work\unity\1111111\Assets\Samples\WebRTC\2.4.0-exp.1\Example\MultiplePeerConnections\MultiplePeerConnectionsSample.cs:31 
2021/05/25 17:19:57.565 9832 20091 Error Unity  
2021/05/25 17:19:57.565 9832 20091 Error Unity (Filename: D Line: 0)

**Comment by karasusan** [comment]
Could you share the screenshot of the player settings?
You can check the player settings in the sample project here.
https://github.com/Unity-Technologies/com.unity.webrtc/tree/develop/WebRTC~

**Comment by laoyigrace** [comment]
@karasusan I see. Thank you.
Scripting Backend needs to be changed from Mono to IL2CPP and ARM64 needs to be selected.
