### ISSUE TITLE
[BUG] Crash App Encoder Error

### ISSUE THREAD

**Issue by gtk2k** [Unity-Technologies/com.unity.webrtc#408]
(日本語で失礼します)

Oculus Questで使用するとエンコードエラーが発生しアプリがクラッシュします。

エンコーダータイプ：Software
デバイス：Oculus Quest
Unity Version: 2019.4.16f1
WebRTC For Unity: 2.4.0-exp.1
(ちなみに送信側でビットレートを設定してます。maxBitrate = 25000 * 1000 (約2.5Mbps))

添付したファイルを見ていただくとわかるように、
```
C2DColorConvert unknown format passed for luma alignment number
```
というエラーが大量に発生

動作としては、受信した映像は表示されているので一見問題なさそうに見えるのですが、裏では上記のエラーが発生し続け、約1分くらいたつとアプリがクラッシュして落ちます。

[crash.log](https://github.com/Unity-Technologies/com.unity.webrtc/files/6554644/crash.log)

**Comment by karasusan** [comment]
@gtk2k 
Oculus Quest 2 ではなくて、Oculus Quest ですかね？
今週月曜に 2.4.0-exp.2 を配布したので、同じ結果になるか確認していただけると助かります。

**Comment by gtk2k** [comment]
@karasusan 
ありがとうございます。

Quest 2ではなくQuestです。
exp.2にアップデートして試してみます。

**Comment by gtk2k** [comment]
exp.2 にアップデートしたら問題解消しました。
お騒がせしました。
