### ISSUE TITLE
Referenced images missing in Plugin~/README_EN.md

### ISSUE THREAD

**Issue by drejx** [Unity-Technologies/com.unity.webrtc#41]
Hello,

Just a note that the images referenced in this readme are missing:

https://github.com/Unity-Technologies/com.unity.webrtc/blob/release/1.0.2/Plugin~/README_EN.md

Cheers,
Andrej

**Comment by karasusan** [comment]
Thanks, I will fix it

**Comment by drejx** [comment]
Hi just sending a friendly ping about this :)

**Comment by karasusan** [comment]
Thank you for your ping!
This issue is already fixed it on the branch https://github.com/Unity-Technologies/com.unity.webrtc/pull/43 
Sorry to keep you waiting but we are preparing to release the new version package.
