### ISSUE TITLE
[BUG] Error building webrtc app for android 

### ISSUE THREAD

**Issue by bharathraja** [Unity-Technologies/com.unity.webrtc#416]
[log.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/6598145/log.txt)
Getting unable to find webrtc library error, i am trying to build unity webrtc-2.4.0-exp-2. I tried removing and reinstalling the webrtc package couple of times. But still getting same error. I have attached the log text.

**Comment by karasusan** [comment]
@bharathraja 
Are you building it with arm64?
It looks the issue is from the build settings.

**Comment by bharathraja** [comment]
yeah, i use ill2cpp and arm64

**Comment by bharathraja** [comment]
i tried in another device, its working in it. maybe some issues is there with rooted device that i was testing previously on.
