### ISSUE TITLE
[HELP] Remote connection not work

### ISSUE THREAD

**Issue by JoseManuelRasconAlcantara** [Unity-Technologies/com.unity.webrtc#423]
I have a rendering stream made with webrtc, using the MediaSteramScene example as a reference and Photon engine as signaling. when I connect two PCs in the same router, it works perfectly but it doesn't work if the PCs have different router.

The connection works exactly the same as when it works fine and run all the code, then OnIceConnectionChange state stay in Checking and after a few seconds change to Failed.

This also happens to me when I try to connect computer with my Android device using in the same Router.

Have I to open some port or something?
I don't know if this is the right place to ask this but please help me.

Environment:
 - OS: [Windows]
 - Unity Version [2019.4.27f1]
 - Package version [2.4.0-exp.2]

**Comment by karasusan** [comment]
This document might be useful for you. 
https://docs.unity3d.com/Packages/com.unity.renderstreaming@3.0/manual/turnserver.html

You can ask your question in this forum, someone could answer it. 
https://forum.unity.com/forums/unity-render-streaming.413/

**Comment by karasusan** [comment]
@JoseManuelRasconAlcantara
Can I close this ticket? Thanks.

**Comment by JoseManuelRasconAlcantara** [comment]
Yes
