### ISSUE TITLE
[BUG] Windows - Failed to set local video description 

### ISSUE THREAD

**Issue by unnamed7** [Unity-Technologies/com.unity.webrtc#435]
I get this error everytime;

Unity.WebRTC.RTCError : InternalError : Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.

It only happens when webrtc is initialized with the default EncoderType.Hardware. If I use EncoderType.Software, it works.

I tested it on a razer laptop with Intel HD630 + GTX1060 and another laptop with UHD630 + RTX2070, both results the same exact error on set local offer. 
As I reported some months ago, it used to assert when trying to use NVIDIA, I guess it was trying to use the first device it finds. The problem has fixed but the same problem may still be there for encoding, I guess it tries to use HD630/UHD630 instead of GTX/RTX again.

**Comment by gtk2k** [comment]
I have the same problem.

**Comment by karasusan** [comment]
> I guess it tries to use HD630/UHD630 instead of GTX/RTX again.

That's strange.
The package uses the same NVIDIA GPU that used by the Unity Editor. Can you check which graphics driver is used by the Unity editor?

**Comment by gtk2k** [comment]
As a supplement,
In my case it worked with hardware encoding just a little while ago.
Currently, there is an error in setting up the local offer.
What I did just before the problem occurred was a GPU driver update and CUDA Toolkit 10.1 installation.
I tried downgrading the GPU driver, but the symptomatology did not improve.

**Comment by ThomasJones** [comment]
I also have this issue between two Windows machines, both with NVIDIA RTX 2080 TI GPUs. I experience this issue both on 2.3.3-preview and 2.4.0-exp.3 versions. I've NEVER been able to get hardware encoding to work between these two machines, but software encoding does work. I also do happen to have the CUDA 10.2 and 11.2 toolkits installed on one of the machines.

A few questions - is bi-directional hardware encoding capable of working? If so, are there work-arounds for NVIDIA GPU's? Seems from various threads about hardware encoding problems there may be various work arounds?

**Comment by karasusan** [comment]
@ThomasJones

The hardware encoder on windows is the H264 codec but the package has not supported the h.264 decoder on windows yet.
As you can see below, the h.264 decoder is supported on macOS, iOS, Android.
://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/index.html

**Comment by karasusan** [comment]
Same issue #272.
