### ISSUE TITLE
[BUG] Use Hardware Encoder Resolution.

### ISSUE THREAD

**Issue by gtk2k** [Unity-Technologies/com.unity.webrtc#436]
On the hardware encoder, 3840x2160 works without error, but with 3840x3840 I get a C++ runtime error and the app (editor) crashes.

com.unity.webrtc Ver: exp.3
OS: Win10
Unity: 2019.4
GPU: GeForce RTX 3070 Laptop

**Comment by karasusan** [comment]
Thanks, The limitation of the resolution depends on the graphics card. I will make the API to get the values of the limitation.

**Comment by gtk2k** [comment]
By changing the h264 profile level to NV_ENC_LEVEL_AUTOSELECT, it now works with 3840x3840.

**Comment by karasusan** [comment]
@gtk2k 
This is great news, thanks for the sharing.
