### ISSUE TITLE
How can I show the video stream from the pc2 track in MediaStreamSample?

### ISSUE THREAD

**Issue by SHanDesign1993** [Unity-Technologies/com.unity.webrtc#44]
after pc2 OnTrack callback, pc2 got the MediaStreamTrack from RTCTrackEvent, but  didn't I put the stream on a plane or something?

**Comment by karasusan** [comment]
Could you tell me more detail about your issue?
Are you testing a sample scene?

**Comment by SHanDesign1993** [comment]
@karasusan  I used MediaStream scene as a streamer, and I got my viewer in another unity project, after I finish establishing the PeerConnection, How did I get the actual texture of frames to put on a UI element from MediaStream class?

**Comment by karasusan** [comment]
I see this is a known issue.
The feature receiving video streaming on Unity is not implemented yet. You need browsers to receive a video stream.
We are working on that but we can not clear when it will be released.

**Comment by Buguito** [comment]
Hi there. I've implemented my own signaling server with NodeJS & Socket.IO. Everything is good, i'm receiving video tracks to the browser (actually i'm streaming the camera). But how do i render on a texture an incoming MediaStreamTrack.

I do receive them on the OnTrack delegate, but i don't seem to find a way to get to any decoded video data such as a RenderTexture or Texture of some sort.

In other words, this only is usefull for sending video tracks and displaying them on a browser which i succesfully did but not the other way around?

The RTCEvent only hass acceso to the MediaStreamTrack, which in turn does not expose anything useful.

If anyone knows how to at least render incoming video to a Texture would be super appreciated. I'll keep on investigating.

Thanks.
Warm Regards, Alan

**Comment by karasusan** [comment]
> In other words, is this only usefull for sending video tracks and displaying them on a browser which i succesfully did but not the other way around?

Yes, the latest version of the package does not support the decoder feature.

**Comment by Buguito** [comment]
Thanks @karasusan for replying. I've downloaded the source and i'm installing the SDK's and tools required to compile so i can dig around and understand the native calls side i couldn't see before with only the runtime scripts.

I'm willing to spend some time and try to implement the decoding part. Would you say that giving the foundation provided so far, it's a hard but possible task or i would encounter too many issues along the road? In general terms that is.

Thanks again!
Warm Regards, Alan

**Comment by karasusan** [comment]
In general terms, it is so difficult to implement the decoding part yourself.
You can find the implementation as OSS on GitHub so I suggest that you try them.
But I am not sure the combination works well.

**Comment by Buguito** [comment]
Thank you karasusan, i've managed to start receiving the I420 Frames by hooking up at the library at the OnTrack callback (and recompiling the lib of crouse).

`void PeerConnectionObject::OnTrack(rtc::scoped_refptr<webrtc::RtpTransceiverInterface> transceiver)
{
    if (onTrack != nullptr)
    {
        onTrack(this, transceiver.get());

        webrtc::VideoTrackInterface* videoTrack = nullptr;
        webrtc::MediaStreamTrackInterface* track = transceiver.get()->receiver()->track().get();
        if ((m_remote_video_observer != nullptr) && (track != nullptr))
        {
            if (track->kind() == "video")
            {
                videoTrack = static_cast<webrtc::VideoTrackInterface*>(track);
                videoTrack->AddOrUpdateSink(m_remote_video_observer, rtc::VideoSinkWants());
            }
        }
    }
}`

And tha video observer class has an OnFrame handler that recieves the VideoFrame so i get to sent the data down the lines.

`void VideoObserver::SetVideoCallback(DelegateOnRemoteI420FrameReady callback)
{
    std::lock_guard<std::mutex> lock(mutex);
    OnI420FrameReady = callback;
}

void VideoObserver::RemoveVideoCallback()
{
    OnI420FrameReady = nullptr;
}

void VideoObserver::OnFrame(const webrtc::VideoFrame& frame)
{
    std::unique_lock<std::mutex> lock(mutex);        

    if (!OnI420FrameReady)
        return;
    
    rtc::scoped_refptr<webrtc::VideoFrameBuffer> buffer(
        frame.video_frame_buffer());

    if (buffer->type() != webrtc::VideoFrameBuffer::Type::kI420A)
    {
        rtc::scoped_refptr<webrtc::I420BufferInterface> i420_buffer =
            buffer->ToI420();            

        OnI420FrameReady(m_owner, i420_buffer->DataY(), i420_buffer->DataU(),
            i420_buffer->DataV(), nullptr, i420_buffer->StrideY(),
            i420_buffer->StrideU(), i420_buffer->StrideV(), 0
            frame.width(), frame.height());

    }
    else
    {
        // The buffer has alpha channel.
        const webrtc::I420ABufferInterface* i420a_buffer = buffer->GetI420A();

        OnI420FrameReady(m_owner, i420a_buffer->DataY(), i420a_buffer->DataU(),
            i420a_buffer->DataV(), i420a_buffer->DataA(),
            i420a_buffer->StrideY(), i420a_buffer->StrideU(),
            i420a_buffer->StrideV(), i420a_buffer->StrideA(),
            frame.width(), frame.height(), frame.height() * i420a_buffer->StrideY(), frame.height() * i420a_buffer->StrideU(),
            frame.height() * i420a_buffer->StrideV(), frame.height() * i420a_buffer->StrideA());
    }
}`

On the other hand, and besides this new add on, i'm having a specific issue. That OnTrack callback is not fired if i'm starting the negotiation from Unity => Webrowser. I don't get the tracks being sent by the browser (and i inspected the PeerConnection on the browser side, everything looks good, it has a Sender for each track.

If the browser is the one creating the offer and i respond from Unity with the answer and so on, i do get the incoming video tracks Webrowser => Unity.

I think it might be something related to the comments placed on the PeerConnectionObject.h

> // This is called when signaling indicates a transceiver will be receiving
        // media from the remote endpoint. This is fired during a call to
        // SetRemoteDescription. The receiving track can be accessed by:
        // |transceiver->receiver()->track()| and its associated streams by
        // |transceiver->receiver()->streams()|.
        // Note: This will only be called if Unified Plan semantics are specified.
        // This behavior is specified in section 2.2.8.2.5 of the "Set the
        // RTCSessionDescription" algorithm:
        // https://w3c.github.io/webrtc-pc/#set-description
        void OnTrack(rtc::scoped_refptr<webrtc::RtpTransceiverInterface> transceiver) override;

Could you elaborate on that comments on the header a little bit if you have a few minutes? I'm going insane, i don't know why it's not firing up when creating the SDP Offer from Unity and setting ;(

Thanks and keep up this great job!

Regards, Alan

**Comment by Buguito** [comment]
So i did some testing, and it seems that when Unity is the one creating the SDP Offer we get Transceivers in sendonly direction and not sendrcv por (?). And i get Bundle 0 1 2 instead of 0 1. I've stripped down the SDP for readability.

```
-----------------------------------------------------------
Negotiation #1: Chrome (OFFERS) - Unity (RESPONDS)
Outcome: Success. Both parties recieved their remote tracks
Notice: "sendrcv" Unified Plan (?)
-----------------------------------------------------------

Chrome Sends (SdpOffer)

a=group:BUNDLE 0 1
a=msid-semantic: WMS I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV
m=audio 53329 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
a=mid:0
a=sendrecv
a=msid:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV dd9ab9b9-eb75-41e0-8711-28461c766876
a=ssrc:1759965807 cname:V9BS/J6pe/B1LaFW
a=ssrc:1759965807 msid:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV dd9ab9b9-eb75-41e0-8711-28461c766876
a=ssrc:1759965807 mslabel:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV
a=ssrc:1759965807 label:dd9ab9b9-eb75-41e0-8711-28461c766876

m=video 53332 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114 115 116
a=mid:1
a=sendrecv
a=msid:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV e17280b4-5ac4-412b-a63c-abf925e83aed
a=ssrc-group:FID 3272418253 939051246
a=ssrc:3272418253 cname:V9BS/J6pe/B1LaFW
a=ssrc:3272418253 msid:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV e17280b4-5ac4-412b-a63c-abf925e83aed
a=ssrc:3272418253 mslabel:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV
a=ssrc:3272418253 label:e17280b4-5ac4-412b-a63c-abf925e83aed
a=ssrc:939051246 cname:V9BS/J6pe/B1LaFW
a=ssrc:939051246 msid:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV e17280b4-5ac4-412b-a63c-abf925e83aed
a=ssrc:939051246 mslabel:I2uKo4LzjzurFKjNMSEcQ0DNNu1hj2sOdETV
a=ssrc:939051246 label:e17280b4-5ac4-412b-a63c-abf925e83aed

Unity Responds (SdpAnswer)

a=group:BUNDLE 0 1
a=msid-semantic: WMS audiostream videostream
m=audio 61198 UDP/TLS/RTP/SAVPF 111 110
a=mid:0
a=sendrecv
a=msid:audiostream 0eea4a0f-1e72-4ff0-ab48-496b39b1719f
a=ssrc:3239901191 cname:IBANZi7ZtdlNy8uH
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 114 115 116
a=mid:1
a=sendrecv
a=msid:videostream ea5567d8-d826-4632-8737-d196f6a7306b
a=ssrc-group:FID 1795659568 4053278682
a=ssrc:1795659568 cname:IBANZi7ZtdlNy8uH
a=ssrc:4053278682 cname:IBANZi7ZtdlNy8uH

-----------------------------------------------------------
Negotiation #2 Unity (OFFERS) - Chrome (RESPONDS)
Outcome: Failure. Only Chrome get's Unitys Remote Tracks. 
Failure: Method not fired -> void PeerConnectionObject::OnTrack(rtc::scoped_refptr<webrtc::RtpTransceiverInterface> transceiver)
Notice: "sendonly" (?)
-----------------------------------------------------------

Unity Sends (SdpOffer)

a=group:BUNDLE 0 1 2
a=msid-semantic: WMS audiostream videostream
m=video 62715 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 103 104
a=mid:0
a=sendonly
a=msid:videostream Streaming_Cam_A
a=ssrc-group:FID 1843658317 3185461729
a=ssrc:1843658317 cname:YAlqQZoh8g4SoHHt
a=ssrc:1843658317 msid:videostream Streaming_Cam_A
a=ssrc:1843658317 mslabel:videostream
a=ssrc:1843658317 label:Streaming_Cam_A
a=ssrc:3185461729 cname:YAlqQZoh8g4SoHHt
a=ssrc:3185461729 msid:videostream Streaming_Cam_A
a=ssrc:3185461729 mslabel:videostream
a=ssrc:3185461729 label:Streaming_Cam_A
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 103 104
a=mid:1
a=sendonly
a=msid:- 6bcb113b-26c9-425c-8ecd-11c919d351a3
a=ssrc-group:FID 776503957 1142334552
a=ssrc:776503957 cname:YAlqQZoh8g4SoHHt
a=ssrc:776503957 msid:- 6bcb113b-26c9-425c-8ecd-11c919d351a3
a=ssrc:776503957 mslabel:-
a=ssrc:776503957 label:6bcb113b-26c9-425c-8ecd-11c919d351a3
a=ssrc:1142334552 cname:YAlqQZoh8g4SoHHt
a=ssrc:1142334552 msid:- 6bcb113b-26c9-425c-8ecd-11c919d351a3
a=ssrc:1142334552 mslabel:-
a=ssrc:1142334552 label:6bcb113b-26c9-425c-8ecd-11c919d351a3
m=audio 9 UDP/TLS/RTP/SAVPF 111 110
a=mid:2
a=sendonly
a=msid:audiostream audio
a=ssrc:776692745 cname:YAlqQZoh8g4SoHHt
a=ssrc:776692745 msid:audiostream audio
a=ssrc:776692745 mslabel:audiostream
a=ssrc:776692745 label:audio

Chrome Responds (SdpAnswer)

a=group:BUNDLE 0 1 2
a=msid-semantic: WMS om04uRIPoun9OYllfJNBydSrOADo45zqpGWY
m=video 62712 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 103 104
a=mid:0
a=recvonly
a=msid:om04uRIPoun9OYllfJNBydSrOADo45zqpGWY 0a372dbc-f2fd-466f-82a8-0c61e13defaf
a=ssrc-group:FID 1569796864 1816861518
a=ssrc:1569796864 cname:f41IWccL+zzr8xzl
a=ssrc:1816861518 cname:f41IWccL+zzr8xzl
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 103 104
a=mid:1
a=recvonly
m=audio 9 UDP/TLS/RTP/SAVPF 111 110
a=mid:2
a=recvonly
a=msid:om04uRIPoun9OYllfJNBydSrOADo45zqpGWY 784c03f5-1039-4f6c-a244-625cd8608d23
a=ssrc:2361298178 cname:f41IWccL+zzr8xzl
```

**Comment by Buguito** [comment]
Hi guys, hope you doing good,

I was able to fetch the incoming I420 Frames by adding a VideoSinkInterface object to the VideoTrack with AddSink(..) and getting the OnFrame callback for converting back to RGB.

I'm trying to do similar with incoming audio, but the OnData(const void* audio_data, int bits_per_sample, int sample_rate, size_t number_of_channels, size_t number_of_frames), method of my attached AudioSinkInterface to the track is not being called.

I googled quite a bit and i found out that if i call the NeedMorePlayData(..) on the AudioTransport we get on the DummyAudioDevice upon callback registration, then the OnData gets called at the sink.

Is that the way to go? Don't quite understand why the AudioSinkInterface method is not being called every 10ms as it's supposed to be and i have to trigger it via AudioTransport.

Any help would be appreciated.

Thanks!!!

**Comment by mickeyvanolst** [comment]
Hey @Buguito I'm curious to hear about your attempts at getting Audio input from webRTC. Did you manage to get it working in the end?

**Comment by karasusan** [comment]
We have a plan which developers can implements  a video streaming viewer on Unity.

**Comment by 8o8inCodes** [comment]
@karasusan so does it mean that this project doesn't support Unity to Unity webcam streams yet?
I am just having a hard time adding the webcam to the webrtc track.. If it's possible, is there a guide for it somewhere?

**Comment by karasusan** [comment]
@8o8inCodes 
Unity to Unity streams is not supported yet.
In our plan we will support that on the end of October.

**Comment by bisc67** [comment]
@karasusan @Buguito 

Can you share the code you currently have? I have had some experience with writing an android/windows(ffmpeg) cross decoder library. 

Regards,

Biscuit.

**Comment by karasusan** [comment]
The initial version of the decoder will be released on October, it only support codec VP8 and VP9. 
Unfortunately the decoder is not work with hardware encoder (because it uses H.264).

**Comment by lstemple** [comment]
Hi @Buguito 

I appreciate that it has been some time, but would you be willing to share your experience of implementing the audio interface on the receiving side? 
I too would like to have Unity-to-Unity real time audio via this plugin, and unfortunately I cannot wait until it is officially supported within the roadmap due to the time constraints of my project.

Kind regards,
Lloyd

**Comment by Buguito** [comment]
Hi everyone. I'll see what i can post. I've implemented both bidirectional audio / video (Web Browser - Unity). For decoding the video , you need to decode de I420 frames basically and map the resulting RGBA data to a texture which you then apply to a material. For encoding the audio from Unity to the other side, you need to basically mix the samples of unity audio mixer and the webcam audio track if you want to use a webcam inside unity (it was my case).

I'll see if a can give you guys a package ready to use, at least unitil they release their implementation.

Warm Regards, Alan

**Comment by aaronerod** [comment]
@mickeyvanolst  I managed to send audio from Unity emitter to Unity receiver. Probably it's not the best way, but I achieve it by sending the audio data through the dataChannel. 
I just converted the float array received on the OnAudioFilterRead callback to byte array and did the opposite on the receiver. Then I used the received data to create an AudioClip. 
I'm still trying to improve it because the sound is distorted but I think it's an interesting workaround. 

Can Anyone point me in the right direction in order to create an AudioClip with the float array?

**Comment by 8o8inCodes** [comment]
> I'll see if a can give you guys a package ready to use, at least until they release their implementation.
> 
> Warm Regards, Alan

Hey, any update on that?

**Comment by karasusan** [comment]
This PR is merged into develop branch and we will release it as a new version 2.2 in this month.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/181

Can I close this issue?
The issue page about audio renderer opened in other place. You can discuss about that.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/196

Please post issues if you have another one.

**Comment by 8o8inCodes** [comment]
> @8o8inCodes
> Unity to Unity streams is not supported yet.
> In our plan we will support that on the end of October.

Can I open this issue so we will know when it's released? Or can you give us the name of the update to look forward to?

**Comment by karasusan** [comment]
@8o8inCodes
Next version 2.2 will be released by the end of October.
OK, I will announce when we release it on this page.

**Comment by karasusan** [comment]
We released the new version 2.2 contained the fix of the issue reported here.

**Comment by 8o8inCodes** [comment]
> We released the new version 2.2 contained the fix of the issue reported here.
> You can download the new version from Unity Package Manager.

OMG Thank you so much! Will try it out today!! Thank you, good work everyone!

**Comment by aaronerod** [comment]
@karasusan do I need to have a newer unity version? 
I'm using 2019.3.0f6 and the last version I can see is 2.0.5.

Btw, thanks for your this package!

**Comment by 8o8inCodes** [comment]
> @karasusan do I need to have a newer unity version?
> I'm using 2019.3.0f6 and the last version I can see is 2.0.5.
> 
> Btw, thanks for your this package!
@aaronerod 
You can copy the repository URL (git@github.com:Unity-Technologies/com.unity.webrtc.git), and press on the "+" button top right of the package manager, and click on "Add package from GIT"
Then give it a minute to update.

![image](https://user-images.githubusercontent.com/16385213/97463793-cba72280-1948-11eb-84a2-b9c164da0ea0.png)

**Comment by codymartin2005** [comment]
Is only video supported at this time or can we send/receive audio?

**Comment by lstemple** [comment]
> Is only video supported at this time or can we send/receive audio?

Audio send/receive is not yet supported. 

However, I raised a new issue specific to the audio interface so the discussion can continue over there: #196

**Comment by tdowdle-aicradle** [comment]
Is there an example somewhere that demonstrates how to receive/render a video stream?

**Comment by rollersteaam** [comment]
@Buguito Heya! I hope you're doing well.

There's enough information across the docs and issues to get video send/receive and audio send working, but audio receive is a complete dead-end in the project's current state (a little strange for a WebRTC library, but I digress), do you have any insights, code, or just anything at all to help with receiving audio?

About to start off on the journey of implementing receive natively myself and would rather not drown in the Mariana Trench, so to speak.
