### ISSUE TITLE
[BUG] Validating app for TestFlight problem 

### ISSUE THREAD

**Issue by seyedMaziyar** [Unity-Technologies/com.unity.webrtc#447]
**Describe the bug**
There is a problem when validating the app in Xcode.  validating the app for uploading to the apple server caused an error. "Code signing "webrtc.framework" failed."

I try to manually sign the bundle with codesign command but surprisingly it says "webrtc. bundle: is already signed"
I also change {other code signing flags} to {--deep} but problem remain.

**To Reproduce**
1. Build unity targeting iOS.
2. Archive the app in Xcode.
3. Validate the app in organizer in Xcode. 

**Expected behavior**

**Screenshots**
<img width="745" alt="Screen Shot 2021-06-29 at 5 27 27 PM" src="https://user-images.githubusercontent.com/38826069/123802076-204bd480-d900-11eb-91bc-8a14ad6c4c22.png">

**Environment (please complete the following information):**
 - OS: macOS version 11.4
 - Unity Version 2019.419.f1
 - Package version 2.4.0-exp.3

**Additional context**
There is no problem with building for my local iOS device.

**Comment by karasusan** [comment]
Related issue
https://github.com/Unity-Technologies/com.unity.webrtc/issues/404

Could you try the `lipo` command following below the page?
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/index.html

**Comment by seyedMaziyar** [comment]
Thank you so much.  :)
