### ISSUE TITLE
[BUG] BuildProcessor error on start

### ISSUE THREAD

**Issue by gft-ai** [Unity-Technologies/com.unity.webrtc#448]
**Describe the bug**
When I open the project there is an immediate error:

> Library/PackageCache/com.unity.webrtc@2.4.0-exp.3/Editor/BuildProcessor.cs(31,69): error CS0619: 'AndroidSdkVersions.AndroidApiLevel21' is obsolete: 'Minimum supported Android API level is 22 (Android 5.1 Lollipop). Please use AndroidApiLevel22 or higher'

I am guessing this is has got to do with the fact that I am using the **_latest beta version of Unity_**?

**To Reproduce**
open up a project and install any of webrtc 2.4.0 version.
*webrtc 2.3.x versions are fine.

**Expected behavior**
No error on start

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20
 - Unity Version: 2021.2.0b1
 - Package version: 2.4.0-exp.*

**Additional context**
N/A

**Comment by karasusan** [comment]
Could you check the setting below? Please set the newer version.
![image](https://user-images.githubusercontent.com/1132081/123886418-5897f500-d98a-11eb-8951-20ebbfa6f445.png)

**Comment by gft-ai** [comment]
Hi,

I had not installed Android Build Support module because I do not need to build my app for Android. But I now have installed both Android and IOS build support modules.

I have checked the settings and it didn't even have Android API level 21 in the selection - I only have new versions (from level 22 to level 30). 

The error: 

> error CS0619: 'AndroidSdkVersions.AndroidApiLevel21' is obsolete: 'Minimum supported Android API level is 22 (Android 5.1 Lollipop). Please use AndroidApiLevel22 or higher'

 is still there no matter which API level I choose for any of the 2.4.0 webrtc versions.

**Comment by karasusan** [comment]
Sure.
I am checking the beta version of Unity Editor.

**Comment by karasusan** [comment]
This issue is reproduced on Unity2021.2.
I am fixing it but the fix will be released for the next package release.

**Comment by gft-ai** [comment]
@karasusan Thank you for fixing the issue.

Would you be able to give me a rough timeline of the next package release, please? Thank you!

**Comment by karasusan** [comment]
@gft-ai 
The next release is scheduled at the end of July.

**Comment by gft-ai** [comment]
Great thank you! I will close this issue!
