### ISSUE TITLE
[REQUEST]I want to ask if H.264 is supported in com.unity.webrtc

### ISSUE THREAD

**Issue by PoRain** [Unity-Technologies/com.unity.webrtc#454]
I know that com.unity.webrtc supports VP8 now, but I can't find the support information of H.264 in unity.
thanks.

**Comment by PoRain** [comment]
I mean the H.264 software encoder or H.264 hardware encoder on android

**Comment by karasusan** [comment]
Hi, I guess almost all Android devices support H.264 hardware encoder.
What device are you using? and can you attach the error log, please?

**Comment by PoRain** [comment]
Sorry, there is a problem in my previous description. At present, I have not encountered any Android devices that are not suitable for H.264 hardcodec, but I am looking forward to the support of H.264 softcodec. Thank you for your reply

**Comment by PoRain** [comment]
for the develop branch that you recently submitted, I can't run audiosample.cs normally. The specific performance is that I can't run audiosample.cs until the_ PC1 = new rtcpeerconnection (Ref configuration) ", unity crash. I guess there's a problem with the C # interface "contextcreatepeerconnectionwithconfig"， because when i uses the "_ pc1 = new rtcpeerconnection() ", unity will not break

**Comment by juju812** [comment]
See https://github.com/Unity-Technologies/com.unity.webrtc/issues/391
Maybe re-compliation of libwebrtc should be considered for many people asking for h264 software codec

**Comment by karasusan** [comment]
Can we close this ticket? Thank you.

**Comment by PoRain** [comment]
Sorry for my late reply. You can close this ticket, and for this problem, it works well for H.264 hardware encode/decode in our device now.
