### ISSUE TITLE
[REQUEST] Setting Video Encoder Framerate

### ISSUE THREAD

**Issue by keepingitneil** [Unity-Technologies/com.unity.webrtc#462]
Didn't see a ticket for this but I noticed in the docs that maxFramerate on the encoder is not supported.

At the very least it would be nice be able to set an ideal framerate during webrtc initialize.

At most, it would be cool to be able to tell the encoder when a new frame has come in to prevent double frames or skipped frames on render textures when the framerate is intended to be lower than the game fps.

Is there any way to cap the framerate today?

**Comment by karasusan** [comment]
I fixed this issue a half year ago, it might be worked.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/183

I will add the sample to check this feature and fix the docs. Thank you for telling to me.

**Comment by keepingitneil** [comment]
Appreciate it, I have been trying to do something like this to get it to work:
` 
if(parameters.encodings.Length > 0)
                {
                    parameters.encodings[0].maxBitrate = (ulong?)bitrate;
                    parameters.encodings[0].minBitrate = (ulong?)bitrate;
                    parameters.encodings[0].maxFramerate = 30;
                    transceiver.Sender.SetParameters(parameters);
                    break;
                }
`

but it still goes far above 30 as confirmed by the RTC stats on the sending side and chrome://webrtc-internals on the receiving side

**Comment by karasusan** [comment]
OK, I will check the issue. Thanks.

**Comment by pilzinho** [comment]
> Appreciate it, I have been trying to do something like this to try to get it to work:
> ` if(parameters.encodings.Length > 0) { parameters.encodings[0].maxBitrate = (ulong?)bitrate; parameters.encodings[0].minBitrate = (ulong?)bitrate; parameters.encodings[0].maxFramerate = 30; transceiver.Sender.SetParameters(parameters); break; }`
> 
> but it still goes far above 30 as confirmed by the RTC stats on the sending side and chrome://webrtc-internals on the receiving side

I have the same issue. Setting maxFramerate this way doesn't work for me. It will always encode in the FPS of the application which is typically 60fps what is very bad for performance especially when having multiple connections.

**Comment by karasusan** [comment]
@keepingitneil @pilzinho 
I reproduced it but have currently not found the workaround for the issue.

**Comment by karasusan** [comment]
Related issue
#632

**Comment by karasusan** [comment]
@keepingitneil
You can test this fix on the develop branch. Thank you.
