### ISSUE TITLE
[REQUEST] How to get logs genereated by libwebrtc

### ISSUE THREAD

**Issue by juju812** [Unity-Technologies/com.unity.webrtc#471]
**Is your feature request related to a problem? Please describe.**
Hi, @karasusan 

I want to ask how to get logs genereated by libwebrtc. 
For I didn't find any implementation of `rtc::Log` related, I guess that logs of libwebrtc is streamed to `stderr` by default. But either in `Editor.log` or `Player.log` I can't find any contents of `stderr`.

Currently I implemented `rtc::LogSink` interface to stream logs to a hard-coded file and make it inuse by `rtc::LogMessage::AddLogToStream` . For logs of libwebrtc is quite useful while troubleshooting, in my view a more completed solution is needed here.

**Describe the solution you'd like**
Expose user interface and register C# callback to `rtc::LogSink`, so log behavior of libwebrtc can be customized.

**Describe alternatives you've considered**
Redirect `stderr` to any existing Unity logs

**Comment by juju812** [comment]
Here's one temp implementation to redirect webrtc logs to unity

https://github.com/juju812/com.unity.webrtc/commit/3ebdaae65aa4e239346202c7aaac8edf7e060f0d

**Comment by karasusan** [comment]
@juju812 
Thanks for your feedback and creating the PR.
We are checking the change.
