### ISSUE TITLE
[REQUEST]Audio playback out of sync

### ISSUE THREAD

**Issue by PoRain** [Unity-Technologies/com.unity.webrtc#477]
I want to try the remote synchronous playback of audio,PC2(PC1) is a chrome client.

When I push the stream to chrome, there is a delay in playing. I think it may be caused by the interval between unity collecting audio, which means that the data sent by unity is always out of date.I solved this problem by updating the acquisition position of the microphone in update () to synchronize the acquisition and transmission.

But when I choose to use unity to play and chrome to push streaming, the playback delay of unity is about 1 s.How should unity use unity.webrtc to solve this problem?

**Comment by keepingitneil** [comment]
Are all of the media streams you want to be synced on the same peer connection?

**Comment by PoRain** [comment]
> Are all of the media streams you want to be synced on the same peer connection?

Yes, I plan to synchronize audio and video on the same peer-to-peer connection, but this is the work of RTCP. The problem I found is that unity has a large buffer during acquisition and playback, resulting in a waste of time. I have solved this problem, and the delay is about 250ms, but it is still a long time

**Comment by karasusan** [comment]
@PoRain
We know the issue that Unity has the delay for playing audio from buffers, but not found the workaround yet.

**Comment by howard-stearns** [comment]
@karasusan Is there a separate ticket that is tracking the "delay for playing audio from buffers"? 

We are experiencing something like this, and I'd like to find out whatever you have on this so we can determine whether what we're seeing is the same. It would also be nice to compare workarounds. Or should we do that here?

**Comment by karasusan** [comment]
@howard-stearns
There is no ticket for that. Could you make it as a new one?

**Comment by howard-stearns** [comment]
@karasusan - Posted as https://github.com/Unity-Technologies/com.unity.webrtc/issues/525

**Comment by karasusan** [comment]
@PoRain
We fixed the latency of audio streaming for the next release. This should be released next week.

**Comment by karasusan** [comment]
@howard-stearns
@PoRain
@keepingitneil
We released the new version 2.4.0-exp.5.
Please check it out and if your issue is not solved, please notify me.
