### ISSUE TITLE
[BUG] When video track.InitializeReceiver is set to the gameobject, it is not rendering properly

### ISSUE THREAD

**Issue by bharathraja** [Unity-Technologies/com.unity.webrtc#488]
I tried applying the recieved video track to game object, it is showing washed out gray colors and improper rendering of the image. But the same when applied over a rawImage.texture is showing correct video frame. I am using latest webrtc plugin 2.4.0_exp-3.

sample code:
```
[SerializeField] private GameObject DestinationImage;
public Renderer rend;
remoteConnection.OnTrack = e => { receiveStream.AddTrack(e.Track);};
receiveStream = new MediaStream();
receiveStream.OnAddTrack = e =>
{
          if (e.Track is VideoStreamTrack track)
          {
		var videoTrack = (VideoStreamTrack) e.Track;
		rend = DestinationImage.GetComponent<Renderer>();
		rend.material.mainTexture = videoTrack.InitializeReceiver(4096,2048);
		StartCoroutine(WebRTC.Update());
          }
};
```

**Comment by karasusan** [comment]
@bharathraja 
Could you upload a screenshot? thanks.

**Comment by karasusan** [comment]
@bharathraja 
Is it the same error?
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/374

**Comment by bharathraja** [comment]
I guess this is different from above specified issue (Unity-Technologies/UnityRenderStreaming#374), as it is the same when run in the windows, android platform.

Screenshots:

This is the washed out image:
![webrtc_wrong_output](https://user-images.githubusercontent.com/866896/126445235-68d37294-be54-46ef-a96a-ceebbdbf7d95.PNG)

This is the original frame on flat rawimage:
![correctOuput](https://user-images.githubusercontent.com/866896/126445523-63efc39a-7f41-4bbd-8c39-285a8bab7f42.PNG)

**Comment by bharathraja** [comment]
solved the error. it is due to the different tilting factor, it is working good after changing to skybox/panaroma
