### ISSUE TITLE
Error when the built app is run on a different machine [BUG]

### ISSUE THREAD

**Issue by gft-ai** [Unity-Technologies/com.unity.webrtc#491]
**Describe the bug**
When I run the built app on the machine I built the app on it runs fine.
When I run the same built app on a different machine it errors with the following:
```
DllNotFoundException: webrtc assembly:<unknown assembly> type:<unknown type> member:(null)
```

**To Reproduce**
1. build an app using RenderStreaming & WebRTC (a very simple one)
2. copy and paste the build directory to another computer
3. run the app

**Expected behavior**
No error

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20
 - Unity Version: 2021.2.0b2
 - Package version: 2.4.0-exp.3 

**Additional context**
In the Player.log file the following stands out:
```
Plugins: Couldn't open /home/gft-ai/Downloads/Telegram Desktop/testapp/app_Data/Plugins/libwebrtc.so, error: libc++.so.1: cannot open shared object file: No such file or directory

Fallback handler could not load library /home/gft-ai/Downloads/Telegram Desktop/testapp/app_Data/MonoBleedingEdge/x86_64/webrtc
Fallback handler could not load library /home/gft-ai/Downloads/Telegram Desktop/testapp/app_Data/MonoBleedingEdge/x86_64/libwebrtc.so
```

**Comment by gft-ai** [comment]
This is an example screenshot of the error on the built app on a different machine.

The start button is supposed to bring up video a stream and the stop button is of course supposed to stop the stream.
All of this works find on the same machine the app is built on. But does not work on a different machine.

![photo_2021-07-27_20-14-47](https://user-images.githubusercontent.com/84541184/127198595-9c5e4523-9d8d-4e09-8d1b-080d4d19fde8.jpg)

**Comment by karasusan** [comment]
Could you try the command below? Thanks.
```
sudo apt install -y libc++1 libc++abi1
```
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/index.html

**Comment by gft-ai** [comment]
Thank you that gets rid of the problem - sorry I had completely forgotten about those dependencies.

But now the app doesn't even start - I double click on the app to launch but then the window pops up for a split second and it closes (it's crashing on start basically). I checked the Player.log and it says:
```
implib-gen: libcuda.so: failed to load library: libcuda.so: cannot open shared object file: No such file or directory
```
My guess is that my other machine doesn't have a GPU and therefore I don't have libcuda installed on that machine. But I don't understand why it wouldn't even start now but it did before.

**Comment by gft-ai** [comment]
I have also tried it with the "Receiver" example from RenderStreaming. Built on one machine and transferred the files to the other and the problem still exists. (the same error as the above [comment)](https://github.com/Unity-Technologies/com.unity.webrtc/issues/491#issuecomment-888123927)
