### ISSUE TITLE
Unable to add package [com.unity.webrtc@2.4.0-exp.4]

### ISSUE THREAD

**Issue by EphTron** [Unity-Technologies/com.unity.webrtc#495]
Hi, when I am trying to add the latest package as described in the install package section (currently 2.4.0-exp.4)
Unity shows the following error messages:

  [Package Manager Window] Unable to add package [com.unity.webrtc@2.4.0-exp.4]:
  Package [com.unity.webrtc@2.4.0-exp.4] cannot be found

  [Package Manager Window] Cannot perform upm operation: Unable to add package [com.unity.webrtc@2.4.0-exp.4]:
  Package [com.unity.webrtc@2.4.0-exp.4] cannot be found [NotFound].

  [Package Manager Window] Error adding package: com.unity.webrtc@2.4.0-exp.4.

Is that a connection issue on my side? Installing older versions works without a problem.

**Describe the bug**

**To Reproduce**
1. Window > Package Manager > Add package from git URL...
2. Enter com.unity.webrtc@2.4.0-exp.4
3. ---> Error

**Environment (please complete the following information):**
 - OS: Windows
 - Unity Version: 2020.3.4f
 - Package version: 2.4.0-exp.4

**Additional context**
I tried it with a Unity project where WebRTC 2.4.0-exp.3 was installed and also with a new project. Both does not seem to work.

**Comment by karasusan** [comment]
@EphTron 
`2.4.0-exp.4` is not published yet.
It should be released next week (I am working to fix bugs just now 😅 ).

**Comment by tomires** [comment]
Hello @karasusan ,
I just wanted to ask about ETA for 2.4.0-exp.4 (milestone still lists 7/23 as the due date). We are waiting for audio support, so that we can complete our transition from VoxImplant.

Thank you :)

**Comment by karasusan** [comment]
@EphTron, @tomires
We released the latest version `2.4.0-exp.4` last week.
Sorry for waiting long time.

**Comment by AndrewMeadows** [comment]
For the record: it is possible to add the package at a specific commit using an URL with the following form:

https://github.com/Unity-Technologies/com.unity.webrtc.git#e5ef0b98f893d44b88863db39b700e71d19462f0

**Comment by kannan-xiao4** [comment]
This issue already fixed, I close this.
