### ISSUE TITLE
CaptureStream() bitrate parameter effect nothing

### ISSUE THREAD

**Issue by orangeagain** [Unity-Technologies/com.unity.webrtc#498]
https://github.com/Unity-Technologies/com.unity.webrtc/blob/20d70a56c482a81a0207d49e1d1da6a9c8c104d6/Runtime/Scripts/VideoStreamTrack.cs#L195
[Removes bitrate parameter from CameraExtension capture methods](https://github.com/Unity-Technologies/com.unity.webrtc/pull/211)

may I curious why not delete it?

**Comment by karasusan** [comment]
Yes, it should be deleted.

**Comment by karasusan** [comment]
memo: WRS-223

**Comment by karasusan** [comment]
This issue has already been fixed this PR.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/783
