### ISSUE TITLE
[BUG] Entry Point Not Found Exception

### ISSUE THREAD

**Issue by AshkanZirakzadeh** [Unity-Technologies/com.unity.webrtc#502]
**Describe the bug**
Attempting to create a new RTCPeerConnection throws an exception: 
`EntryPointNotFoundException: PeerConnectionRegisterOnRemoveTrack`

**To Reproduce**
1. Put M92 Release into project
2. Attempt to create new RTCPeerConnection();

**Screenshots**
![9774ecf165](https://user-images.githubusercontent.com/22134504/128258345-343f6e41-28a5-45c5-9dd3-77e05f812642.png)

**Environment (please complete the following information):**
 - OS: iOS, Windows, Android
 - Unity Version: 2020.3.8f1
 - Package version: M92 Source Code (https://github.com/Unity-Technologies/com.unity.webrtc/releases/tag/M92)

**Additional context**
Out of curiosity I commented out the line that causes Entry Point Not Found which will allow me to create a peer connection anyway, but a different EntryPointNotFoundException get thrown.
It seems to mostly function, I was able to receive a webrtc stream on Windows and Android despite the errors, however it will not build for iOS due to linker error below.

![12ec5a4ee8](https://user-images.githubusercontent.com/22134504/128257797-51ea8458-31d4-4906-9490-8816037ee795.png)
<img width="359" alt="Screen Shot 2021-08-04 at 5 40 12 PM" src="https://user-images.githubusercontent.com/22134504/128258866-15daa884-fc6e-4f90-a187-974837f9c070.png">

**Comment by karasusan** [comment]
Please download the package from Unity Package Manager.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/install.html

**Comment by AshkanZirakzadeh** [comment]
> 
> 
> Please download the package from Unity Package Manager.
> https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/install.html

Does this mean that 2.4.0-exp.4/M92 is not ready to be used as seen in #495 ?

Mainly trying to use exp.4/M92 since audio rendering is important.

**Comment by karasusan** [comment]
@AshkanZirakzadeh
Hi, we released the latest version `2.4.0-exp.4` last week.
Please let you try it. Thanks.

**Comment by AshkanZirakzadeh** [comment]
Hello, I have tried it with 2.4.0-exp.4 but I continue to get the same errors on iOS.
<img width="726" alt="Screen Shot 2021-08-30 at 2 30 15 PM" src="https://user-images.githubusercontent.com/22134504/131387816-3ffb93e7-90d2-4741-a703-5f9b8fb61cf2.png">

**Comment by karasusan** [comment]
Looks like Unity can not detect plugin file.
Is it possible to build the sample scenes for macOS?
You can follow the instruction here.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/sample.html

**Comment by kannan-xiao4** [comment]
@AshkanZirakzadeh 
Is this problem still happening?
If not, this issue will be closed.

**Comment by AshkanZirakzadeh** [comment]
> @AshkanZirakzadeh Is this problem still happening? If not, this issue will be closed.

Sorry for leaving the issue open for so long.
I moved on to a different project and haven't tried since.
When I have time to come back to this I will re-open the issue if it's still happening.
