### ISSUE TITLE
[REQUEST] Validation of VideoStreamTrack's label

### ISSUE THREAD

**Issue by stef-t** [Unity-Technologies/com.unity.webrtc#505]
Hey,

I've stumbled upon the following problem: The `RTCPeerConnection.SetRemoteDescription` was throwing the error
> RTCErrorException: Expected format "msid:\<identifier\>[ \<appdata\>]".

After some digging, I've realized that the name of the camera gameobject, that is passed to `CameraExtension.CaptureStreamTrack` and returns a `VideoStreamTrack` object, must not contain white-spaces! That is, because this name is used as part of a SDP like for example so: 
```
... 
a=msid:- Peer1
...
```

A white-space as part of the name of the camera gameobject would result in the following _malformed_ SDP:
```
... 
a=msid:- Peer 1
...
```
Note the white-space between _Peer_ and _1_!

Now after reading my description of the problem, this is straightforward, but to reduce friction for developers I propose adding a validation to the label parameter that is passed to a `VideoStreamTrack` constructor -- in the actual constructor or any of its base classes or wherever it makes the most sense.

This validation might do the following:
* make sure that the passed label is valid by removing any characters that would make it a malformed label like, e.g., white-spaces
* print a warning that clearly states what characters must not be part of a camera gameobject's name

This problem might be avoided completely by using, e.g., a randomly generated valid label. I'm not sure if a reference to the camera via its name is required.

As a first time user of this package this was a very frustrating experience as it was not clear to me that a gameobject's name in a scene has any influence on the behaviour of the actual WebRTC connection establishment.

For completeness, I'm using:
* Version 2.4.0-exp.3
* Unity 2020.3.13f1

Kind regards.

**Comment by karasusan** [comment]
This issue was fixed below. The next version *2.4.0-exp.4* contains this fix which will be released this week. 
https://github.com/Unity-Technologies/com.unity.webrtc/pull/439

**Comment by stef-t** [comment]
I see, thank you!
