### ISSUE TITLE
[BUG]Failed to set local video description recv parameters for m-section with mid='0'.

### ISSUE THREAD

**Issue by ninefiveseven** [Unity-Technologies/com.unity.webrtc#506]
Windows now does not support hard decoding and cannot set the VideoReceive property of RTCOfferOptions to false as before, so now Windows cannot use hardware mode at all should be an error

Failed to set local video description recv parameters for m-section with mid='0'.

**Comment by karasusan** [comment]
Same issue
https://github.com/Unity-Technologies/com.unity.webrtc/issues/391

**Comment by WeiRU087** [comment]
I get the same errror of "... with mid='0" when setting LocalDescription after calling CreateAnswer. Is this the problem of H264 codecs? But both initializing with EncoderType Hardware of Software dose not work. Below is the answer created:

> v=0
o=- 4313809724711225444 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 98 99 100
c=IN IP4 0.0.0.0
b=AS:15000
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:RQFn
a=ice-pwd:dxQ/71FqFC0zodObIusG+my4
a=ice-options:trickle
a=fingerprint:sha-256 AA:51:B8:6E:55:49:A9:76:65:E5:22:28:61:15:C2:2C:D3:1F:2F:0C:FC:8C:48:10:B1:12:32:2F:7C:F3:A7:1D
a=setup:active
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:98 red/90000
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 ulpfec/90000
m=audio 9 UDP/TLS/RTP/SAVPF 111 110
c=IN IP4 0.0.0.0
b=AS:15000
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:RQFn
a=ice-pwd:dxQ/71FqFC0zodObIusG+my4
a=ice-options:trickle
a=fingerprint:sha-256 AA:51:B8:6E:55:49:A9:76:65:E5:22:28:61:15:C2:2C:D3:1F:2F:0C:FC:8C:48:10:B1:12:32:2F:7C:F3:A7:1D
a=setup:active
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;sprop-stereo=1;stereo=1;useinbandfec=1
a=rtpmap:110 telephone-event/48000
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
b=AS:15000
a=ice-ufrag:RQFn
a=ice-pwd:dxQ/71FqFC0zodObIusG+my4
a=ice-options:trickle
a=fingerprint:sha-256 AA:51:B8:6E:55:49:A9:76:65:E5:22:28:61:15:C2:2C:D3:1F:2F:0C:FC:8C:48:10:B1:12:32:2F:7C:F3:A7:1D
a=setup:active
a=mid:2
a=sctp-port:5000
a=max-message-size:262144

**Comment by WeiRU087** [comment]
The offer received is below

> v=0
o=- 4562756484283730810 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS primary_stream
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:qxXK
a=ice-pwd:w//sREANs10xMKnBEa5gn/fW
a=ice-options:trickle
a=fingerprint:sha-256 94:76:1F:39:09:F6:E6:54:01:30:22:F1:62:4B:C8:42:A0:55:B4:D6:4D:7A:57:3B:B4:17:CE:6E:00:BA:EF:B8
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:primary_stream primary_video
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 red/90000
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 ulpfec/90000
a=ssrc-group:FID 2770762975 1672213143
a=ssrc:2770762975 cname:hbDIuhSYVbuQL27G
a=ssrc:2770762975 msid:primary_stream primary_video
a=ssrc:2770762975 mslabel:primary_stream
a=ssrc:2770762975 label:primary_video
a=ssrc:1672213143 cname:hbDIuhSYVbuQL27G
a=ssrc:1672213143 msid:primary_stream primary_video
a=ssrc:1672213143 mslabel:primary_stream
a=ssrc:1672213143 label:primary_video
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 110
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:qxXK
a=ice-pwd:w//sREANs10xMKnBEa5gn/fW
a=ice-options:trickle
a=fingerprint:sha-256 94:76:1F:39:09:F6:E6:54:01:30:22:F1:62:4B:C8:42:A0:55:B4:D6:4D:7A:57:3B:B4:17:CE:6E:00:BA:EF:B8
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:primary_stream primary_audio
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:110 telephone-event/48000
a=ssrc:510659546 cname:hbDIuhSYVbuQL27G
a=ssrc:510659546 msid:primary_stream primary_audio
a=ssrc:510659546 mslabel:primary_stream
a=ssrc:510659546 label:primary_audio
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:qxXK
a=ice-pwd:w//sREANs10xMKnBEa5gn/fW
a=ice-options:trickle
a=fingerprint:sha-256 94:76:1F:39:09:F6:E6:54:01:30:22:F1:62:4B:C8:42:A0:55:B4:D6:4D:7A:57:3B:B4:17:CE:6E:00:BA:EF:B8
a=setup:actpass
a=mid:2
a=sctp-port:5000
a=max-message-size:262144

**Comment by WeiRU087** [comment]
After checking the log, the reason is my another peer only supports H264.
I have solved this problem by rebuilding the package with H264 supported, as said here :https://github.com/Unity-Technologies/com.unity.webrtc/issues/391#issuecomment-879518381.

**Comment by kannan-xiao4** [comment]
https://github.com/Unity-Technologies/com.unity.webrtc/issues/391 was closed.
This issue already fixed. I close this issue.
