### ISSUE TITLE
[REQUEST] Receive incoming video streams at their native resolution

### ISSUE THREAD

**Issue by nathanael-omnivor** [Unity-Technologies/com.unity.webrtc#507]
Currently, it appears that the only way to access the incoming video streams is by calling `InitializeReceiver(int width, int height)` on the `VideoStreamTrack`, providing your own `width` and `height`.

It would be great if we could access the incoming video at its native resolution, rather than provide a resolution manually. Or, at least provide a way to query for the video resolution, and then construct the receiver `Texture` using the existing method.

One complication is that the sending side's WebRTC implementation may dynamically change the resolution of the video it is sending, in which case the video received by Unity.WebRTC will change size as well. In this case, the receiver `Texture` would need to be updated to reflect the new resolution.

**Comment by karasusan** [comment]
Thanks for your feedback. 
We will check your suggestion.

**Comment by kannan-xiao4** [comment]
memo: WRS-139

**Comment by karasusan** [comment]
@nathanael-omnivor
This issue is fixed by the next release which will release next week.

**Comment by karasusan** [comment]
@nathanael-omnivor
We released the new version 2.4.0-exp.5.
Please check it out and if your issue is not solved, please notify me.
