### ISSUE TITLE
[BUG] You should set a real GOP length or expose SetKeyframe

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#514]
Probably the reason why the hardware encoder is so rough out of the box...

The visual quality is much better in Furioos, have you been using the hardware encoder there?

Package version 2.4.0-rc4

**Comment by karasusan** [comment]
Is this issue related? 
https://github.com/Unity-Technologies/com.unity.webrtc/issues/205

Sorry to have kept you waiting long time to use more stable hardware encoder.
We will start to fix the issue in this year.

**Comment by doctorpangloss** [comment]
For some reason in Unity 2021, hardware encoding got so bad it is totally unusable, both in 2.3.3 and 2.4.0.

I haven't tried reverting yet to 2020 because it's a huge headache for my project.

A lot of stuff is wrong with the hardware encoder right now but it's the only way forward.

The software encoder for example doesn't work unless the width is a multiple of 64.

**Comment by karasusan** [comment]
@doctorpangloss 
Could you tell me more detail?
It is my first time to hear that difference of stability between 2020 and 2021.

**Comment by doctorpangloss** [comment]
Let's stay focused on this bug. I am still figuring out what exactly the issue is since I am doing something pretty advanced. However you definitely want to set a real GOP length.

**Comment by doctorpangloss** [comment]
> @doctorpangloss
> Could you tell me more detail?
> It is my first time to hear that difference of stability of the package between 2020 and 2021.

So specifically I do not believe there is an issue between 2020 and 2021 anymore. Sorry about that.

My own `SetKeyframe` as a render event is working well.

**Comment by doctorpangloss** [comment]
> The visual quality is much better in Furioos, have you been using the hardware encoder there?

I see now that Furioos uses a VDI approach.
