### ISSUE TITLE
[BUG] The software encoder only works for widths that are a multiple of 64 pixels

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#520]
2.4.0-exp.4

Has existed since 2.0.0.

**Comment by kannan-xiao4** [comment]
@doctorpangloss 
Sorry for the late reply.
In the latest Package, could you tell me which platform, which graphics API, which codec (VP8, VP9, AV1)?

**Comment by doctorpangloss** [comment]
VP8

**Comment by kannan-xiao4** [comment]
please more detail,  OS, Unity version and  resolution that occurred in your environment

**Comment by kannan-xiao4** [comment]
@doctorpangloss 
I checked this problem and reproduce with DX12 on windows only.
Are you same environment ?

**Comment by doctorpangloss** [comment]
That's correct, although I have experienced this bug for a very long time.

**Comment by kannan-xiao4** [comment]
@doctorpangloss 
Thanks. I'm investigating this issue

memo: WRS-124

**Comment by karasusan** [comment]
This issue is fixed by https://github.com/Unity-Technologies/com.unity.webrtc/pull/708 .
Please wait for the next release.

**Comment by doctorpangloss** [comment]
Wait? I `pull` the code right out of your computer, before you've even `push`ed it.
