### ISSUE TITLE
[BUG] libwebrtc is picking totally garbage bitrates through DummyVideoEncoder

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#521]
Whatever it is doing, it is choosing frame rates and bitrates that are complete garbage. On a local device, a basically empty HDRP scene, it should easily choose much higher framerates than 14 and bitrates higher than 2.5mpbs on an RTX 3090.

Commenting out `DummyVideoEncoder::SetRates` does **not** improve the situation, even when the NvEncoder is being asked, according to logs, to encode at much higher bitrates and framerates.

**Comment by doctorpangloss** [comment]
By comparison, the software encoder easily chooses 10mbps+ and the right framerates, so it's a *huge* puzzle to me why hardware encoder has been so hobbled.

**Comment by Ziriax** [comment]
@doctorpangloss Why was this closed? Is it solved in the latest version?
