### ISSUE TITLE
[BUG] MediaStreamTrack Enabled=false causes Editor to Crash

### ISSUE THREAD

**Issue by vmohan7** [Unity-Technologies/com.unity.webrtc#523]
**Describe the bug**

When trying to pause the media track using enabled=false at runtime, this causes the Editor to completely crash. This was noticed when using the StreamSourceBase script that is part of the Unity Render Streaming. 

**To Reproduce**

Once the browser and editor are connected in Unity Render Streaming, disable any MediaStreamTrack as follows

source.Track.Enabled = false;

At runtime, this causes the editor to crash and I am seeing this in the error logs

webrtc.dll caused an Access Violation (0xc0000005)
  in module webrtc.dll at 0033:02ced7c3.

**Expected behavior**

Editor to not crash

**Environment (please complete the following information):**
 - OS: Windows
 - Unity Version 2019.4.28
 - Package version 2.3.3-preview

**Comment by karasusan** [comment]
Could you try the latest version 2.4.0-exp.4?

**Comment by vmohan7** [comment]
> Could you try the latest version 2.4.0-exp.4?

Just pulled 3.1.0-exp.1 of Render Streaming and still see the same crash when disabling the stream track. What is interesting is on the render streaming package, it seems that webrtc 2.4.0-exp.4 is mentioned as a dependency in the package file; however Unity was only pulling 2.4.0-exp.3.

However, when I explicitly pull 2.4.0-exp.4 I see the following compile errors, which suggests that 2.4.0-exp.4 isn't compatible with 3.1.0-exp.1 ?

```
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\CameraStreamer.cs(55,24): error CS7036: There is no argument given that corresponds to the required formal parameter 'height' of 'VideoStreamTrack.VideoStreamTrack(IntPtr, int, int, GraphicsFormat)'
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\AudioStreamer.cs(14,13): error CS0234: The type or namespace name 'Audio' does not exist in the namespace 'Unity.WebRTC' (are you missing an assembly reference?)
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\AudioStreamer.cs(19,29): error CS0234: The type or namespace name 'Audio' does not exist in the namespace 'Unity.WebRTC' (are you missing an assembly reference?)
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\AudioStreamer.cs(25,13): error CS0234: The type or namespace name 'Audio' does not exist in the namespace 'Unity.WebRTC' (are you missing an assembly reference?)
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\Signaling\WebSocketSignaling.cs(144,45): warning CS0168: The variable 'e' is declared but never used
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\Signaling\HttpSignaling.cs(141,45): warning CS0168: The variable 'e' is declared but never used
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\Signaling\HttpSignaling.cs(160,45): warning CS0168: The variable 'e' is declared but never used
Library\PackageCache\com.unity.renderstreaming@3.1.0-exp.1\Runtime\Scripts\Signaling\HttpSignaling.cs(191,41): warning CS0168: The variable 'e' is declared but never used
```

**Comment by karasusan** [comment]
> However, when I explicitly pull 2.4.0-exp.4 I see the following compile errors, which suggests that 2.4.0-exp.4 isn't compatible with 3.1.0-exp.1 ?
I fixed the issue in this PR but not released it yet.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/512

**Comment by vmohan7** [comment]
fyi, this can now be tested publicly here and just requires swapping out the Track.Enabled line and then calling the ViewStream method. 
 https://github.com/FusedVR/VRStreaming/blob/38d3423e44884db185cf6249e79d0471d46eccd1/Runtime/Scripts/ClientStreams.cs#L59

**Comment by karasusan** [comment]
@vmohan7 
Sorry for your inconvenience. Thanks for sharing.
It is so helpful if you confirm #512 fixes your issue.

**Comment by karasusan** [comment]
Could you reproduce this issue with the latest version?
I want to close it if you have no problem. Thanks.
