### ISSUE TITLE
DllNotFoundException on Linux

### ISSUE THREAD

**Issue by mukaschultze** [Unity-Technologies/com.unity.webrtc#526]
**To Reproduce**
1. Import the package as a dependency on linux

**Expected behavior**
It should find the required DLL

**Logs**

```log
Plugins: Couldn't open /home/muka/repos/unity-webrtc-debug/Library/PackageCache/com.unity.webrtc@2.4.0-exp.4/Runtime/Plugins/x86_64/libwebrtc.so, error: libc++.so.1: cannot open shared object file: No such file or directory
```
```log
DllNotFoundException: Packages/com.unity.webrtc/Runtime/Plugins/x86_64/libwebrtc.so
Unity.WebRTC.WebRTC.Dispose () (at Library/PackageCache/com.unity.webrtc@2.4.0-exp.3/Runtime/Scripts/WebRTC.cs:394)
Unity.WebRTC.WebRTC.OnBeforeAssemblyReload () (at Library/PackageCache/com.unity.webrtc@2.4.0-exp.3/Runtime/Scripts/WebRTC.cs:305)
UnityEditor.AssemblyReloadEvents.OnBeforeAssemblyReload () (at /home/bokken/buildslave/unity/build/Editor/Mono/AssemblyReloadEvents.cs:15)
```

**Environment (please complete the following information):**
 - OS: Manjaro/Linux
 - Unity Version **2020.3.18f1**
 - Package version tested on **2.4.0-exp.3** and **2.4.0-exp.4**

**Comment by mukaschultze** [comment]
Installing `libc++` from AUR fixes this issue.

**Comment by karasusan** [comment]
> Installing libc++ from AUR fixes this issue.
Yes, some package need to be installed.

https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/index.html#requirements

**Comment by kannan-xiao4** [comment]
@mukaschultze Can we close this issue?
