### ISSUE TITLE
[BUG] Code signing does not work for framework (Test Flight)!

### ISSUE THREAD

**Issue by tomires** [Unity-Technologies/com.unity.webrtc#530]
**Describe the bug**

When pushing app to Test Flight, I receive the following message indicating that webrtc.framework is not signed.

`Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "webrtc.framework" failed." UserInfo={NSLocalizedDescription=Code signing "webrtc.framework" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}`

**To Reproduce**
1. Create a blank Unity project
2. Import WebRTC package and examples
3. Set platform to iOS
4. Make a build
5. In Xcode, select Product -> Archive, Distribute
6. Receive error message
<img width="761" alt="Screenshot 2021-09-13 at 9 41 53 10" src="https://user-images.githubusercontent.com/7209990/133043743-fdff00e1-da95-4216-81dc-40f1e695fcf0.png">

**Expected behavior**
For code signing to be completed successfully.

**Environment (please complete the following information):**
 - OS: macOS, building for iOS
 - Unity Version 2020.3.0f1
 - Xcode 12.5.1
 - Package version 2.4.0-exp4

**Comment by karasusan** [comment]
@tomires 
Please follow this note in this document.
You need to remove x86_64 architecture from the binary in the framework.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/index.html#requirements

**Comment by tomires** [comment]
Thank you for a prompt reply! We already have a routine for stripping unrelated architectures in our CD pipeline, so it did not cross my mind this could be an issue. I will try running the lipo command as mentioned in the docs and get back to you.

**Comment by tomires** [comment]
It works! Thanks for your support!
