### ISSUE TITLE
[BUG] iOS Error when render streaming is closed and reopened

### ISSUE THREAD

**Issue by mksbamford** [Unity-Technologies/com.unity.webrtc#531]
**Describe the bug**
On iOS when I close a connection and start a new one, I get an instance has been disposed error. 

**To Reproduce**
RenderStreaming.Run(...);
RenderStreaming.Stop();
RenderStreaming.Run(...);

**Expected behavior**
No error.

**Screenshots**
![IMG_E435138A2D1C-1](https://user-images.githubusercontent.com/2213612/133116432-7b7440c1-8e7b-4c10-af03-9f663488ffbd.jpeg)

**Environment (please complete the following information):**
 - OS: iOS
 - Unity Version 2019.4.19f1
 - WebRTC Package version 2.4.0-exp.3
 - RenderStreaming Package version 3.1.0-exp.1

**Comment by karasusan** [comment]
This issue seems happened in Unity Render Streaming package, not WebRTC.

**Comment by karasusan** [comment]
I do move this issue to the other repository.

**Comment by karasusan** [comment]
I moved it here. So I closed this issue.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/529
