### ISSUE TITLE
case new project vs. old project

### ISSUE THREAD

**Issue by LluisTrapeCasanovas** [Unity-Technologies/com.unity.webrtc#537]
Hi, 
I will explain my experience with a new project and an old one for android device.

Last mounth i created a new project for learn webRTC in 2021.1.17f1 version.
webrtc crashed when started app in android(IL2CCP), i downgrading veresion to 2020.3.19f1
i uncheked armv7, and remove vulcan option, and work good.

Today i implement webrtc in old project, this project works with ILCPP. this project was created in 2020.1.17f1 I think remember, or in 2019... but don't remember the exact version.
i compile the project but i dont remeber unchek arm7, and i don't remember remove vulcan option and works good!!
i find vulcan option and i don't find it.

I don't know if this can help with the development of this library. For this I explain my experience. 

Although I think it is not related to webRTC, i couldn't use c# HttpWebRequest for call api signaling in learn project,
but old project call other api with c# HttpWebRequest, and work good.

**Comment by karasusan** [comment]
That sounds strange...
The latest WebRTC package is supported Android Vulkan with ARM64 option.

Our testing on Unity2021 is not enough but Unity2020 should be OK.

**Comment by kannan-xiao4** [comment]
@LluisTrapeCasanovas 
Does it occur with the latest version?
In the latest version, we have confirmed that 2021 works on Android.
