### ISSUE TITLE
[BUG] Audio performance Always later than the video texture. 

### ISSUE THREAD

**Issue by IdolMenendez** [Unity-Technologies/com.unity.webrtc#538]
**Describe the bug**
I want to build a One-One video app. And I need to Add Video and Audio Track On the same time at one peerconnection.
So the problem occurs. Audio performance Always later than the video texture. 
Is this a Bug? I saw another Issue #477 mentioned about it. Is there any plan to Solve it?

**Comment by karasusan** [comment]
@IdolMenendez
Thanks for your reporting.
We know this issue and some people reported details of that.
Of course we have a plan to fix this near future, and it is so helpful for us if you post the detail of your issue to the page below.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/525

**Comment by karasusan** [comment]
@IdolMenendez
We released the new version 2.4.0-exp.5.
Please check it out and if your issue is not solved, please notify me.
