### ISSUE TITLE
[BUG] Unable to connect manually without using ICE

### ISSUE THREAD

**Issue by maeln** [Unity-Technologies/com.unity.webrtc#539]
**Describe the bug**
The application I am currently working on use its own way to share the SDP between two peer to establish the WebRTC connection. We are currently using this method with a webapp implementation and its working fine. It is based on a custom JSON-based RPC system.

We want to be able to do the same in Unity using your library. We don't have an issue creating an offer and sending it to our peer, but it seems that, when receiving the peer answer SDP and calling `SetRemoteDescription` with it, the connection doesn't start ( the `ConnectionState` of our `RTCPeerConnection` stays at `NEW` ).

We still receive a Video track, but no video seem to be streamed. Also, the WebRTC stats window become empty after this step (only display the peer with no info).

Here is how we more or less setup our system :

```
public class WebRtcVideo : MonoBehaviour
{
    public delegate void onRTCSessionDescriptionCallback(RTCSessionDescription sdp);

    [SerializeField] private RawImage RtImage;
    [SerializeField] private Vector2Int streamSize = new Vector2Int(640, 480);

    private RTCPeerConnection peerConnection;
    private MediaStream receiveVideoStream;

    private DelegateOnTrack DelegateOnTrack;
    public onRTCSessionDescriptionCallback OnOffer;

    private RTCSessionDescription answerSdp;
    private RTCSessionDescription offerSdp;


    private void Awake()
    {
        WebRTC.Initialize();
    }

    public void Start()
    {
       [...]

        // initialize webrtc stuff
        peerConnection = new RTCPeerConnection();
        peerConnection.AddTransceiver(TrackKind.Video);
        peerConnection.OnConnectionStateChange = state =>
        {
            Debug.Log($"Connection state change {state}");
        };

        peerConnection.OnIceCandidate = candidate =>
        {
            Debug.Log($"CANDIDATE: {candidate}");
        };

        DelegateOnTrack = e =>
        {
            if (e.Track is VideoStreamTrack video && !video.IsDecoderInitialized)
            {
                RtImage.texture = video.InitializeReceiver(streamSize.x, streamSize.y);

                receiveVideoStream = e.Streams.First();
                receiveVideoStream.OnRemoveTrack = ev =>
                {
                    RtImage.texture = null;
                    ev.Track.Dispose();
                };
            }
        };

        peerConnection.OnTrack = DelegateOnTrack;

        OnOffer = desc =>
        {
            offerSdp = desc;
        };

        StartCoroutine(WebRTC.Update());
        StartCoroutine(CreateOfferAsync());
    }

    [...]

    // This will be called after the create on offer, once the 
    // user has clicked on a button to call and RPC on the remote server
    // that will triggger it to send us an SDP
    void handle_answer(JsonRpcResult res)
    {
        // Get our remote peer SDP from a json
        var offerString = Encoding.UTF8.GetString(Convert.FromBase64String(res.result));
        var answer = JsonUtility.FromJson<SdpOffer>(offerString);

        answerSdp = new RTCSessionDescription();
        answerSdp.type = RTCSdpType.Answer;
        answerSdp.sdp = answer.sdp;
        peerConnection.SetRemoteDescription(ref answerSdp);

        Debug.Log(peerConnection.ConnectionState); // Still == NEW 

        connect_video(); // This function call a RPC to ask our peer to start to send us video
    }

    public async void OnApplicationQuit()
    {
        WebRTC.Dispose();
    }

    private IEnumerator CreateOfferAsync()
    {
        Debug.Log("Create offer");
        var opCreateOffer = peerConnection.CreateOffer();
        yield return opCreateOffer;

        if (opCreateOffer.IsError)
        {
            yield break;
        }
        var offerDesc = opCreateOffer.Desc;
        yield return peerConnection.SetLocalDescription(ref offerDesc);
        OnOffer(offerDesc);
    }

    public void CreateOffer()
    {
        StartCoroutine(CreateOfferAsync());
    }

    public string b64(string str)
    {
        byte[] bytesToEncode = Encoding.UTF8.GetBytes(str);
        return Convert.ToBase64String(bytesToEncode);
    }
}
```

The whole idea of this code is that the offer will be created as soon as the program start.
At some point, the user should click on a button on the UI which will call a custom RPC which will trigger the `handle_answer` function.
After this function is called, we should have exchanged our SDP and the connection should be established, but it doesn't seen so. The `peerConnection.ConncetionState` is still `NEW` and the video track we receive seems to be empty / have the status `ENDED`.

Cannot we setup our connection manually (without ICE) using the `SetLocalDescription` & `SetRemoteDescription` ?
Is there an known bug concerning this ? 
Or is a step missing ?

**Environment (please complete the following information):**
 - OS: Mac OS, Android
 - Unity Version 2020.3
 - Package version 2.4.0-exp.4

**Comment by karasusan** [comment]
@maeln
I think it is not working without exchanging ICE candidate.
Have you tried it with exchanging ICE candidate?

**Comment by maeln** [comment]
@karannayee  Thank you for your answer. 
I added  `AddIceCandidate` on the `OnIceCandidate` callback like so :
```
peerConnection.OnIceCandidate = candidate =>
        {
            Debug.Log("CANDIDATE");
            Debug.Log(candidate);
            peerConnection.AddIceCandidate(candidate);
        };
    ```
    
    But still no dice :/ . Am I missing something ? I do get some candidate.

**Comment by julienkay** [comment]
It seems you're adding the ICE candidates to your local PeerConnection object. When implementing the session negotation, [this article](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling#exchanging_ice_candidates) helped me understand things better. Essentially each peer is supposed to send the ICE candidates to the other peer which then calls AddIceCandidate. (Similar to how you currently exchange the offer/answer SDP).

**Comment by karasusan** [comment]
@julienkay
Thanks, you are right.

@maeln
Have you solved your issue?
