### ISSUE TITLE
[BUG] Outdated docs on Audio Streaming?

### ISSUE THREAD

**Issue by streunerlein** [Unity-Technologies/com.unity.webrtc#543]
**Describe the bug**
The reference talks about Audio Streaming on https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/audiostreaming.html using `Audio.CaptureStream` which I cannot find any documentation nor source for this API. Is this outdated or just wrong docs? What is the current state-of-the-art for Audio Streaming with UnityWebRTC?

**Comment by streunerlein** [comment]
@karasusan Don't worry, it's no problem at all! Thanks for the sample link, I've followed the samples and was able to create audio streaming. I was hoping this docs points to an API I have missed or misunderstood, because I am currently fighting weird problems with streaming microphone input to multiple peers.

**Comment by crosf32** [comment]
@karasusan 

Hi, I'm having so much trouble to figure out how to stream the whole scene audio ! As it was working in version 2.2.1 (using com.unity.renderstream as well)
The doc hasn't been updated yet and the Audio class has disappeared ..

We can stream Audio only from an AudioSource component (which is working for the Microphone)
but not for the whole scene.

I've tried to generate an AudioClip Combined from all the AudioSources in the scene and to apply it to an AudioSource to try to stream it but it doesn't work ..

What am i supposed to do ?

Thanks !

**Comment by karasusan** [comment]
`AudioListener` call [`OnAudioFilterRead`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnAudioFilterRead.html) method same as `AudioSource`.
You can use the whole scene audio if you implements `OnAudioFilterRead`.

old: 
https://github.com/Unity-Technologies/com.unity.webrtc/blob/e900f5cd777484d25b20074aff854aea402b0ea4/Samples~/MediaStream/MediaStreamSample.cs#L260-L263

new:
https://github.com/Unity-Technologies/com.unity.webrtc/blob/e1550d6e4772c59add97f865d3dcee7f0f85d6de/Runtime/Scripts/AudioStreamTrack.cs#L238

**Comment by crosf32** [comment]
Oh ok, Thank you !

**Comment by karasusan** [comment]
Of course, we will update docs next month. Sorry for too late!

**Comment by karasusan** [comment]
memo: WRS-164

**Comment by karasusan** [comment]
Fixed docs in this PR #621

**Comment by karasusan** [comment]
@streunerlein
We released the new version 2.4.0-exp.5.
Please check it out and if your issue is not solved, please notify me.
