### ISSUE TITLE
[BUG] Sending Stereo Audio produces mono clip on some peers

### ISSUE THREAD

**Issue by streunerlein** [Unity-Technologies/com.unity.webrtc#548]
**Describe the bug**
Sending stereo audio from one peer to other peers results in some peers receiving a mono clip, some receiving a stereo clip.

**To Reproduce**
Same reproduction as in #545

**Expected behavior**
All receiving peers should receive a stereo clip if one is sent

**Additional information**
 The order of peer connection seems to play a role. E.g. when Peer A connects to a peer B and a peer C (order of `new RTCPeerConnection`) and sending stereo audio both, it is peer C that receives only a mono clip.

**Environment (please complete the following information):**
 - OS: Mac & Windows
 - Unity Version 2020.3 & 2021.2
 - Package version 2.4.0-exp.4

**Comment by kannan-xiao4** [comment]
@streunerlein 
Can I close this issue on this side?
(same issue discussion proceed on https://github.com/Unity-Technologies/com.unity.webrtc/issues/545)

**Comment by streunerlein** [comment]
@kannan-xiao4 I can‘t really say, @karasusan thinks this is a separate issue (https://github.com/Unity-Technologies/com.unity.webrtc/issues/545#issuecomment-948437469)

**Comment by karasusan** [comment]
memo: WRS-216

**Comment by karasusan** [comment]
This issue should be fixed in #603.

**Comment by karasusan** [comment]
@streunerlein
We released the new version 2.4.0-exp.5.
Please check it out and if your issue is not solved, please notify me.
