### ISSUE TITLE
[BUG] Average or Max Bitrate Encoding Setting is ignored in one of several network routing scenarios

### ISSUE THREAD

**Issue by yvanzine** [Unity-Technologies/com.unity.webrtc#550]
Encoding thread and Rendering thread appear to be coupled. When you increase Unity rendering framerate ( or leave it unbounded ), the encoding framerate goes up to rendering framerate. **When bitrate is controlled with the help of Encoding Parameters (in my experience with com.unity.webrtc framerate cannot be controlled), it is possible to limit bitrate in most cases. We are seeing a strange case where bitrate is bounded with Encoding Parameters, but webrtc traffic is routed in such a way that causes webrtc library to ignore max or average bitrate encoding setting and follow the encoding framerate, which as I mentioned follows the rendering framerate.** As a result, I see 130-150 fps in webrtc traffic. This causes the encoder to pump out too much data and the unity web client to be overwhelmed with traffic. The artifacts, referenced in this ticket (https://github.com/Unity-Technologies/com.unity.webrtc/issues/205), are visible as a result of this unbounded bitrate.

The unpopular solution is to limit rendering framerate of Unity to 30 or 60 Hz but it works. Is there a discussion to find a way to decouple encoding thread and render thread to avoid these unfortunate circumstances? Have you ever seen bitrate parameter ignored in some network routing scenarios and not others?

**Environment**
 - OS: Ubuntu 20.04
 - Browser chrome
 - Unity Version 2020.3.19.f1
 - Package version [2.3.3-preview]

**Comment by kannan-xiao4** [comment]
memo: WRS-171

**Comment by karasusan** [comment]
memo: WRS-229

**Comment by karasusan** [comment]
Related issue
#632

**Comment by karasusan** [comment]
@yvanzine
This issue would be fixed in this PR #728. Already merged the fix to the develop branch. Could you check this?

**Comment by karasusan** [comment]
@yvanzine
I am waiting for your response. Thank you.

**Comment by yvanzine** [comment]
@karasusan 

I will check this and get back to you next.

**Comment by yvanzine** [comment]
@karasusan 
We can close this ticket, the webrtc bitrate is now respected.
