### ISSUE TITLE
[BUG]: macos与pico neo3建立通信失败

### ISSUE THREAD

**Issue by cameIz** [Unity-Technologies/com.unity.webrtc#572]
### Package version

2.4.0-exp.4

### Environment

```markdown
* OS:MacOS 11.6 Intel Core i7
* Unity version:2020.3.25
* pico neo3 android10
```

### Steps To Reproduce

经历OnNegotiationNeeded回调
和六次OnIceCandidate回调
没有OnConnectionStateChange和OnIceConnectionChange
未建立起数据传输通道和音频通道

### Anything else?

webtrc初始化时应该选择硬解码还是软解码
是否为兼容问题，具体问题需要如何定位

**Comment by karasusan** [comment]
@cameIz
Maybe there is no encoder that two peers can use.

**Comment by cameIz** [comment]
@karasusan 
尝试了一下两台pico neo3进行webrtc连接 从log上看与之前效果一样，没建立起通道

**Comment by cameIz** [comment]
![image](https://user-images.githubusercontent.com/58520712/147223654-5247af1a-4a05-4491-a2df-2b93ebe0b9eb.png)
OnNegotiationNeeded和OnIceCandidate的回调log中，能不能提供一些定位问题的方向

**Comment by cameIz** [comment]
@karasusan 我使用相同设备硬解码已经跑通了语音和数据的传输，感谢解答
