### ISSUE TITLE
[REQUEST]: Stream audio from Audio Listener

### ISSUE THREAD

**Issue by BoyBouw** [Unity-Technologies/com.unity.webrtc#596]
### Is your feature request related to a problem?

With the removal of the Audio class, I believe it is currently not possible to stream audio from an Audio Listener. 

With older versions, it was possible to use `CaptureStream` to stream the audio from the entire scene. I used this because my audio comes from the Android Native Videoplayer and Audio sources without a clip. I tried setting the incoming data of `OnAudioFilterRead` to my `MediaStreamTrack` using `setData`, but this does not seem to do the trick. Docs are also unclear about the unit of sample rate in this method, but I assumed Hz. 

### Describe the solution you'd like

Reintroducing the Audio class would make things a lot easier I think. 

### Describe alternatives you've considered

I cannot go back to a previous version of WebRTC, because it crashes when building to Android, possibly related to #387.

**Comment by karasusan** [comment]
I created this PR for this issue. Could you review it?
https://github.com/Unity-Technologies/com.unity.webrtc/pull/595

**Comment by BoyBouw** [comment]
> @BoyBouw I created this PR for this issue. Could you review it? #595

Will do asap, thanks!

**Comment by BoyBouw** [comment]
I tried to test this, but I fail to understand how it should work with AudioListeners. I can't pass an AudioListener as a parameter in the AudioStreamtrack. I also can't use an audioSource, because I use the Android NativeVideoPlayer. 

Can you provide a sample code of how to stream audio from an AudioListener?

**Comment by karasusan** [comment]
Sure, we will make the sample.

**Comment by karasusan** [comment]
I fixed the document to describe how to send audio using `AudioStreamTrack` with `AudioListener`.

**Comment by BoyBouw** [comment]
With the latest documentation I was able to get this to work properly, thanks. I was using the setData method in the Update method instead of the onAudioFilterRead method directly(main thread instead of audio thread) , which resulted in choppy sounds. You van close this ticket.

**Comment by avicarpio** [comment]
I'm trying to use this to create an AudioStreamTrack of my own and use it in my own way, instead of sending it. It is really simple for a VideoStreamTrack:

`        VideoStreamTrack videoTrack = mainCam.CaptureStreamTrack(1920, 1080);
`

But for AudioStreamTrack I can't get it, and even less if I want to take the information from an AudioListener. 

Any advice?

Thank you very much
