### ISSUE TITLE
[BUG]: Latest develop branch version has significantly regressed in audio quality, send & receive audio has become choppy

### ISSUE THREAD

**Issue by rollersteaam** [Unity-Technologies/com.unity.webrtc#602]
### Package version

2.4.0-exp.5

### Environment

```markdown
* OS: Windows 10
* Unity version: Unity 2021.1.19f1
```

### Steps To Reproduce

1. Build your Unity WebRTC project to an Android and run it, checkout the latest commit in `develop` or checkout the commit `a8881cd4b06d740c999c885e6b5837b41d1b2d81` (the most recent commit I use in my test).
2. Connect to the same WebRTC call as your WebRTC browser (in my case, it is a different client that doesn't use this library, but implements the WebRTC protocol).
3. Perform an audio check. The Android project's receiving audio should be very choppy, and the browser side receiving audio should also be very choppy.
4. Optional: Check out commit `2b34a3a0066ae35a9e93d53a9ac899f214a4c44b` and repeat the whole test. Audio should have zero choppiness and be mostly smooth.

### Current Behavior

The Unity WebRTC project's send and receive audio is very choppy. It seems to take too long to send a frame of audio, as if it was trying to do it on the main thread and other Unity priorities like rendering were trying to happen first.

In the below audio tests, I do an audio check at 50% phone volume, 0% phone volume and 100% phone volume. Please note that phone volume is also creating large white noise from what seems like speaker feedback due to the onboard mic, which motivated me to file the noise suppression issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/587. Using a bluetooth headset creates no white noise.

Audio test of the latest `develop` commit `a8881cd4b06d740c999c885e6b5837b41d1b2d81` (14th January 2022): https://www.loom.com/share/881e98f06d004927bd49c06b9d4cf656

Audio test of commit `2b34a3a0066ae35a9e93d53a9ac899f214a4c44b` (18th October 2021): https://www.loom.com/share/32f925920f274b6bb3e94fd2358a7dbe

### Expected Behavior

No send and receive audio choppiness. Ideally, also little to no white noise on 50% - 100% phone volume.

### Anything else?

Other clients in the WebRTC call hear the same audio quality (and artifacts) from the Unity WebRTC participant.

Perhaps relevant to note, this WebRTC setup is client-server where each participant receives all data from just one participant.

**Comment by karasusan** [comment]
@rollersteaam 
Thanks for reporting. We will fix the issue soon.

**Comment by karasusan** [comment]
There are changes relating audio below.
- feat: Upgrade libwebrtc m92 ([#560](https://github.com/Unity-Technologies/com.unity.webrtc/pull/560))
- feat: Improve audio playback stability using streaming AudioClip ([#541](https://github.com/Unity-Technologies/com.unity.webrtc/pull/541))
- fix: Reduce audio latency using buffer position from attached AudioSource ([#565](https://github.com/Unity-Technologies/com.unity.webrtc/pull/565))

**Comment by rollersteaam** [comment]
@karasusan Yeah it's between those two commits :) If it's useful for you, I can `git bisect` to find the commit that caused it?

**Comment by karasusan** [comment]
This bug is in this commit [`ec1934d`](https://github.com/Unity-Technologies/com.unity.webrtc/commit/ec1934d35ec7b1e35ed2348d5c4f3f02faee2603)

I am checking this code.

**Comment by karasusan** [comment]
@rollersteaam
I found multiple issues for audio streaming and I am fixing them.

this branch is for one of fixes.
https://github.com/Unity-Technologies/com.unity.webrtc/tree/fix/audiostream-latency

**Comment by karasusan** [comment]
I fixed this issue.
Please try that if you can. 
We will release the new version which contains this fix next week.
