### ISSUE TITLE
[REQUEST]: Need a way to adjust the bitrate after the initialization of the encoder parameters.

### ISSUE THREAD

**Issue by xiaolongrenlzj** [Unity-Technologies/com.unity.webrtc#607]
I am looking for a way to control the bitrate during the play mode after the encoder parameters are initialized. I tried the function ChangeVideoParameters. It only worked for initializing the encoder parameters. Is it possible to change the bitrate after initialization? 
Thanks in advance!

**Comment by karasusan** [comment]
Are you using the WebRTC package? if so, please check the `Bandwidth` scene in the package sample.
https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/manual/sample.html

**Comment by karasusan** [comment]
@xiaolongrenlzj
Any questions?

**Comment by xiaolongrenlzj** [comment]
Still trying to use the WebRTC package. Thanks anyway.
