### ISSUE TITLE
Enable build on unsupported platforms

### ISSUE THREAD

**Issue by De-Panther** [Unity-Technologies/com.unity.webrtc#61]
Currently the stream server supports only Unity Editor on windows and x64 builds on windows.
Unity.WebRTC.Runtime.asmdef defines support for all the platforms, so if we try to build the project for WebGL and the package is included, we get build errors.

Setting Unity.WebRTC.Runtime.asmdef to support only Editor and Windows 64-bit(and later add more supported platforms when they'll be supported), will allow us to build a project without the need to remove the package.

Thanks

![image](https://user-images.githubusercontent.com/4749703/73261832-8bf2b500-41d5-11ea-81f5-ec9903e6ab45.png)

**Comment by karasusan** [comment]
Definitely. I will fix that.
Thanks for your contribution!

**Comment by De-Panther** [comment]
Thanks

**Comment by karasusan** [comment]
Fixed it in this PR.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/68
