### ISSUE TITLE
[REQUEST]: Ability to commit frames on the user side.

### ISSUE THREAD

**Issue by gtk2k** [Unity-Technologies/com.unity.webrtc#624]
### Is your feature request related to a problem?

Currently, I am involved in the development of an application for eyeglass-type AR devices called Nreal, but Nreal has a camera and can acquire the image of the camera, but the image is Texture 2D type in frame units. It is a specification to acquire with.
In order to pass this video to Unity WebRTC, it is necessary to create a RenderTexture and perform processing such as drawing (Blit) Texture2D every frame on the RenderTexture.
Inside Unity WebRTC, the frame image is acquired from RenderTexture and passed to the encoder, so if there is a function that allows the user to commit the frame, the two processes of drawing to RenderTexture and acquiring the frame image from RenderTexture can be skipped. Then I thought.

(翻訳が不安なので日本語のテキストも追加します)
ユーザー側でフレームのコミットができる機能をリクエストします。

現在Nrealという眼鏡型ARデバイス向けのアプリの開発に携わっているのですが、Nrealにはカメラが搭載されており、(SDKで)カメラの映像を取得することができるのですが、映像はフレーム単位でTexture2D型で取得するという仕様となっております。
この映像をUnity WebRTCに渡すにはRenderTexture作成し、RenderTextureに毎フレームTexture2Dを描画(Blit)するなどの処理を行う必要があります。
Unity WebRTC 内部ではRenderTextureからフレーム画像を取得してエンコーダーに渡しているので、もしユーザー側でフレームをコミットできる機能があれば、RenderTextureへの描画およびRenderTextureからフレーム画像取得の２つの処理はスキップできるのではと思った次第です。

**Comment by karasusan** [comment]
[`VideoStreamTrack(Texture, bool)`](https://docs.unity3d.com/Packages/com.unity.webrtc@2.4/api/Unity.WebRTC.VideoStreamTrack.html#Unity_WebRTC_VideoStreamTrack__ctor_Texture_System_Boolean_) のコンストラクタであれば Texture を引数に渡せるので、`Texture2D` を直接渡せそうな感じがしますがどうでしょうか。

**Comment by gtk2k** [comment]
そうでした。検証してみます。

**Comment by karasusan** [comment]
@gtk2k
検証どうでしたか？
特に問題なければチケットをクローズしたいと思います。

**Comment by gtk2k** [comment]
返事が遅くなり申し訳ございません。
Texture2D をもとに VideoStreamTrack を作成して送信できました。
ただ、もとのテクスチャーのフォーマットが RGB24 であるため、BGRA32 に変換する必要がありました。
