### ISSUE TITLE
[BUG]: PCOnTrack & PCOnRemoveTrack bad endure GC collection -> weakReferences corrupted in table context

### ISSUE THREAD

**Issue by RiccardoCalcagno** [Unity-Technologies/com.unity.webrtc#631]
### Package version

2.4.0-exp.5

### Environment

```markdown
OS: Windows 10 Pro
Unity version: 2020.3.23f1
From Editor
```

### Steps To Reproduce

Environment: Application that manages 2 or more Peerconnections (the bug is present even with only two peers). There is a lot of asynchronicity, and many coroutines undergoing in the same thread (the main thread). 

Configuration: Setted the PCOnTrack property of the PeerConnection with a body in wich there are:
1) An access to a field (as the id) of the track arrived as an argument of the RTCTrackEvent.
2) a call (at the end of the delegate) of the: GC.Collect(). (Here I'm forcing it. However, autonomous calls to GC collection could occur in this time).

Run: 
1) A remote new track reaches the WebRTC level (triggering the native delegate: DelegateNativeOnTrack). 
2) My access to the id of the track did not cause any error. I verified that checking with the debugger the content of the Context.table (without access to its runtime calculated properties) -> the library methods added properly the transceiver receiver and track to the table.
2) Exiting the delegate, the execution returns to the PCOnTrack static method. Here, when the process tries to access again the track, shows up the following problem : 
The pointer of the RTCRtpReceiver related to the track is present in the table but it has no object (as Target) of type RTCRtpReceiver.

I think this means that before the second reading was made the GC Collector had altered the weakReferences of the receviver, setting its isAlive to false so now I have in the table a corrupted Receiver

Possible solution??
Couldn't we just remove the RefCountedObject objects from the table when the become not more alive?

### Anything else?

First relevant stack call in RTCPeerConnection.cs
![First relevant stack call](https://user-images.githubusercontent.com/63152853/154707624-894728dd-6f85-47aa-bf2a-f1866a225cfb.PNG)

Second and Third relevant stack calls in RTCTrackEvent class of MediaStreamTrack.cs
![Second and Third relevant stack calls](https://user-images.githubusercontent.com/63152853/154708247-3df4e1ce-9292-4e14-a5ea-7ab5c7e3eecc.PNG)

Fourth relevant stack call in RTCRtpTransceiver.cs
![Fourth relevant stack call](https://user-images.githubusercontent.com/63152853/154708657-5ec830e5-5dc9-4d3d-9be1-9a8968150f8d.PNG)

Last failing stack call in WebRTC.cs
![Last failing stack call](https://user-images.githubusercontent.com/63152853/154708886-265b4e3b-14d4-44a0-a1cc-9192bd07ad42.PNG)

**Comment by RiccardoCalcagno** [comment]
Or maybe we can switch two istruction in PCOnTrack delegate:
`        [AOT.MonoPInvokeCallback(typeof(DelegateNativeOnTrack))]
        static void PCOnTrack(IntPtr ptr, IntPtr transceiver)
        {
            WebRTC.Sync(ptr, () =>
            {
                if (WebRTC.Table[ptr] is RTCPeerConnection connection)
                {
                    var e = new RTCTrackEvent(transceiver, connection);
                    connection.OnTrack?.Invoke(e);
                    connection.cacheTracks.Add(e.Track);
                }
            });
        }`
the two istructions are:
`                   connection.OnTrack?.Invoke(e);
                    connection.cacheTracks.Add(e.Track);
`

----------------------------------------------------------------------------

And in a way little similar it should be done even in the PCOnRemoveTrack delegate:
`
        [AOT.MonoPInvokeCallback(typeof(DelegateNativeOnRemoveTrack))]
        static void PCOnRemoveTrack(IntPtr ptr, IntPtr receiverPtr)
        {
            WebRTC.Sync(ptr, () =>
            {
                if (WebRTC.Table[ptr] is RTCPeerConnection connection)
                {
                    var receiver = WebRTC.FindOrCreate(
                        receiverPtr, _ptr => new RTCRtpReceiver(_ptr, connection));
                    if(receiver != null)
                        connection.cacheTracks.Remove(receiver.Track);
                }
            });
        }
`
adding the receiver to a cache before using the istruction:
`var receiver = WebRTC.FindOrCreate(
                        receiverPtr, _ptr => new RTCRtpReceiver(_ptr, connection));
`
I don't know if these are usefull or correct suggestion, please forgive me if they are not

**Comment by RiccardoCalcagno** [comment]
What do you think about the following solution?

In this static method:
![Last failing stack call](https://user-images.githubusercontent.com/63152853/154708886-265b4e3b-14d4-44a0-a1cc-9192bd07ad42.PNG)
we could change the first if condition `Context.table.ContainsKey(ptr)` with: `Context.table.ContainsKey(ptr) || Context.table[ptr] == null` 
because it become null when GC Collect erase its value trurning its IsAlive field in false

**Comment by RiccardoCalcagno** [comment]
I know but after the GC.Collect() it still finds a weakReference inside the table with the same Prt, not Alive anymore. 
Might it be added a second time in a second moment?
Can I please ask you If the error occurs even in your environment (with the configuration implying the GC.Collect) ?

**Comment by karasusan** [comment]
@RiccardoCalcagno
I wrote this test. As you said, the issue is reproduced. Thanks.
I am considering how to solve the issue.
``
        [UnityTest]
        [Timeout(5000)]
        public IEnumerator GCCollect()
        {
            GameObject obj = new GameObject("audio");
            AudioSource source = obj.AddComponent<AudioSource>();
            var test = new MonoBehaviourTest<SignalingPeers>();

            var track = new AudioStreamTrack(source);
            var sender = test.component.AddTrack(0, track);
            yield return test;
            GC.Collect();
            var receivers = test.component.GetPeerReceivers(1);
            Assert.That(receivers.Count(), Is.EqualTo(1));
            var receiver = receivers.First();
            var audioTrack = receiver.Track as AudioStreamTrack;
            Assert.That(audioTrack, Is.Not.Null);

            test.component.Dispose();
            UnityEngine.Object.DestroyImmediate(test.gameObject);
            UnityEngine.Object.DestroyImmediate(obj);
        }
```

**Comment by karasusan** [comment]
memo: WRS-320
