### ISSUE TITLE
[BUG]: "Fuzzy Pulse" at start of, and intermittently during webrtc session

### ISSUE THREAD

**Issue by yvanzine** [Unity-Technologies/com.unity.webrtc#632]
### Package version

Others

### Environment

```markdown
My environment:
Linux, Ubuntu 20.04
Chromium 96.
Unity Version [e.g. 2020.3.24f1]
Packages:
[com.unity.webrtc 2.3.3-preview]
[UnityRenderStreaming 3.0.1-preview]
[NVidia Encoder 6.2 upgraded]
```

### Steps To Reproduce

Hi,

I would like to report two specific issues with respect to quality of image, most noticeably, 1) at start up and frequently 2) throughout the webrtc session.

Issue 1) and 2) can be handled differently if they are caused by separate issues, which I suspect.

I will be attaching a video to demonstrate the artifact here. Please ignore the flickering of top half of the video, it is a video capture software artifact. My apologies for poor quality of video capture. Basically, pay attention to bottom left of the screen and you will notice "Fuzzy Pulse" at about 28 seconds in, where pixels flicker in a section of the screen.

https://user-images.githubusercontent.com/19309404/154748797-49e4bdf8-8e20-4932-ad76-c613928d0266.mp4

https://user-images.githubusercontent.com/19309404/154769821-18be6d24-ec91-4dbb-8d4f-98b382887f81.mp4

The issue can be described as "fuzzy pulse" where webrtc bitrate oscilates and the resolution of parts of the image falls and rises very quickly. Once the target bitrate is achieved, this issue is still visible, but less frequently. This issue can be mitigated by setting a low framerate (as low as 5 fps, but it depends on the user's connection) initially but even at low fps it still persists after some time. 

Sometimes I suspect bitrate dips below to a level where "fuzzy pulse" is visible again.

I want to point out that BUG #205 is a different issue. The "data-moshing" from #205 is related to this issue but mostly it happens because the bitrate is either capped at max 2.5Mbps ( see #552 ) or there is not enough bandwidth and smearing will happen if the framerate is constant. 

The #205 Author alludes very extensively to manual/custom control of framerate and references Unreal's control scheme, which I believe is sufficient to minimize most "data-moshing" issues. I currently control framerate similarly (as opposed to Unreal, I simply set the Unity Render Framerate, because Unity does webrtc work on Main thread ) and it eliminates almost all artifacts except the artifact I am discussing here, the "fuzzy pulse".

I have tried to work around this issue extensively by:

1) setting min bitrate to a higher value, e.g. 25000000 which as I verified passes min bitrate to the Hardware Encoder but it does not bring about the instant jump of bitrate discussed and marked resolved in #191 

2) modifying NVidia (Hardware) Encoder settings which does not bring about any improvement.

These are the (ideal) encoder settings I configured and concluded that this bug does not go away by simply modifying Nvidia Encoder settings:

High quality Tuning Info
Rate control mode = CBR
Medium VBV buffer size (1 second)
B Frames*
Look-ahead
B frame as reference
Finite GOP length (2 seconds)
Adaptive quantization (AQ) enabled**

### Current Behavior

"Fuzzy Pulse" is visible at start and during webrtc connection.

### Expected Behavior

"Fuzzy Pulse" should not be present.

**Comment by karasusan** [comment]
@yvanzine 
To control the encoding framerate, are you changing the code to run video capturing process on the worker thread instead of the main thread?
We have same idea to implement controlling encoding framerate.

**Comment by yvanzine** [comment]
@karasusan 

In order to limit framerate I use the following code on main thread:

```
// cap render framerate in order to cap webrtc framerate
QualitySettings.vSyncCount = 0;  // VSync must be disabled
Application.targetFrameRate = Convert.ToInt32(fps); 
```

**Comment by karasusan** [comment]
@yvanzine
`Application.targetFramerate` is for controlling rendering frequency, not encoding count per seconds.
We have not supported changing the encoding framerate yet.

**Comment by yvanzine** [comment]
@karasusan 

In Unreal pixel streaming, framerate is controlled by the render thread framerate I believe. Since unity does not have render thread, Application.targetFramerate is the next best thing.

**Comment by karasusan** [comment]
memo: WRS-229

**Comment by doctorpangloss** [comment]
Removing the `SetStreamState` line in `SetRates` is one part of fixing https://github.com/Unity-Technologies/com.unity.webrtc/issues/632 . The other part is to get rid of the bitrate adjuster since it's redundant. I observed and fixed the fuzzy pulses this way.

**Comment by yvanzine** [comment]
@doctorpangloss 

Thanks!

What is the process of getting rid of bitrate adjuster?

**Comment by doctorpangloss** [comment]
I go in and delete its usages everywhere lol. But you will get an issue using the `parameters` bitrates, which is due to the network bandwidth estimator (`bwe`) being wrong for some reason

**Comment by yvanzine** [comment]
@doctorpangloss we need the bandwidth estimator. I will let you know if SetStreamState call removal makes any difference.

**Comment by karasusan** [comment]
@doctorpangloss @yvanzine
Thank you for sharing, it is so helpful!

**Comment by yvanzine** [comment]
@karasusan @doctorpangloss 

I think @doctorpangloss is testing with the latest 2.4.0-exp.7 where I am using 2.3.3-preview in production because I cannot afford yet to take the risk of running with framerate degradation of recent releases. Having said that, I am  able to run 2.4.0-exp.7 in software only, vp8 with some loss of functionality. I am also on linux+vulkan and I was not able to let client negotiate to run in hardware h264, even though vulkan and NVEncoder initialize correctly. Long story short and I think I will file a bug separately.

On the subject of removing SetStreamState in the older 2.3.3-preview, it does not do anything useful. I more and more believe bitrate adjuster may be a promising suspect of the "fuzzy pulse" as it does look like an artifact of bitrate oscillation, @doctorpangloss may have the evidence of what I have been looking for.

**Comment by doctorpangloss** [comment]
![WebRTC Bitrate Management](https://user-images.githubusercontent.com/2229300/165393322-31b77b8f-5359-4be8-ae09-4adeb4b74669.png)

@karasusan this is what I suggest you modify the NvEncoderImpl to do:
 1. Available network bandwidth is the minimum of the actual network bandwidth and the negotiated maximum bandwidth as per the SDPs.
 2. libwebrtc calls `SetRates` whenever it observes a change in available network bandwidth, passing its suggested, desired bitrate as `parameters.bitrate`.
 3. Pass `parameters.bitrate` to the bitrate adjuster's target bitrate.
 4. Set `rcParams.averageBitrate` (i.e. the CBR rate) to the adjusted bitrate from the bitrate adjuster.
 5. Feed back the frames to bitrate adjuster so that it can correctly calculate how much NVENC overshoots its requested bitrate.

**Comment by yvanzine** [comment]
@doctorpangloss It is a long topic of discussion what should be done to create a balanced control scheme. Just adjusting bitrate is not good, because resolution drops and pixelation gets out of hand. Some automatic adjustment of bitrate/bandwidth is healthy but instead client should have a three-part API: bitrate/resolution/framerate. When network conditions change, custom bitrate/resolution/framerate adjustment must occur. In Unreal, there is a custom framerate control scheme but in the browser you can get an easy win by allowing the client to also set resolution and save bandwidth.

**Bitrate/Resolution/Framerate Controls on the client**

WebRTC package does not work well without having the ability to control all three aspects of graphics streaming at the application level. We have had to use workarounds to achieve some level of control. While user network traffic conditions change frequently and drastically, Render Streaming/WebRTC in Unity assumes that high quality connection will be provided, but we must operate in public cloud environments and share networking with other browser applications and having ideal network conditions is not possible.
 
We choose picture quality over responsiveness in a video streaming profile of WebRTC.  Even 5 frames per second perfect image is sometimes acceptable versus a smeared 30 fps image.  Such experience can be accommodated by lowering framerate when network degrades at a desired moment. 

Additionally, in web browser environment we require to dynamically change resolution of the canvas all the time, aka resize the window.

Bitrate must also be allowed to be controlled or capped based on **type** of image being shown (e.g. solid colors vs noisy image, more or less constant over time), in order to save bandwidth shared with other applications.

If we create an API first, instead of deciding what to do (admit it is difficult to decide for all use-cases), we let clients control these aspects of streaming outside of com.unity.webrtc/UnityRenderStreaming and take responsibility for these decisions.

**Comment by karasusan** [comment]
@yvanzine
The following is the implementation status of the API for controlling the three indicators mentioned above.
The bitrate is controlled by `maxBitrate` / `minBitrate`. The resolution is controlled by using the `scaleResolutionDownBy` parameter, which is not yet supported by NvEncoder. The framerate is currently dependent on Unity's `Application.maxFramerate` and is not variable.
Currently our priority is to implement the API on the WebRTC package side; implementation in Unity Render Streaming will follow.

**Comment by karasusan** [comment]
@doctorpangloss
I make sense your suggestion. It is so helpful the figure you made.

**Comment by doctorpangloss** [comment]
This issue is resolved for me in 2.4.0-exp.8, and the bitrate estimator appears to be used correctly!

**Comment by yvanzine** [comment]
@doctorpangloss @karasusan 

Yes, for me as well.

**Comment by karasusan** [comment]
@doctorpangloss
I added the framerate control for NvCodec in this version. This might be what you want.
