### ISSUE TITLE
[BUG]: When source Miccrophone AudioSource is muted, only muted sound will be received at the receive side

### ISSUE THREAD

**Issue by ysheung** [Unity-Technologies/com.unity.webrtc#637]
### Package version

2.4.0-exp.6

### Environment

```markdown
* OS:Windows10
* Unity version:Unity 2020.3.19f1
```

### Steps To Reproduce

1. Import Unity WebRTC 2.4.0-exp.6 into a new Unity 2020.3.19f1 project.
2. Import the Unity WebRTC 2.4.0-exp.6 samples.
3. Open the Audio scene in the sample.
4. Play the scene.
5. Click the checkbox of Mic, select the mic you are using.
6. Click Start, then click Call.
7. Audio from the mic can be heard in this phrase.
8. Mute the AudioSource by check the checkbox mute in AudioSource - Input 's audiosource.
9. Nothing could be heard.

### Current Behavior

In Unity WebRTC 2.4.0-exp.6, when the Audio Source for capture mic audio is muted, no sound could be heard in the receiving side. 
We tried to check the audio sample length and it returns 0.

### Expected Behavior

In Unity WebRTC 2.4.0-exp.4, when the Audio Source for capture mic audio is muted, the sound from the mic could be heard in the receiving side.

### Anything else?

I have tested 2.4.0-exp.5 that should have the same problem as 2.4.0-exp.6, not sure what cause this because seems the audio part has changed a lot during some bug fix about the stereo/mono problem and the latency problem.

The SetTrack() method seems directly apply the audio source received to the audio source component, is there any workaround to let us mute the Audio Source for capturing mic?

We have also tried to set that audio source to 3D sound and move it away far enough away from the audio listener on camera but that just have the same result that muting the audio source, no sound is received on the receiving side.

Right now the behavior doesn't allow us to mute the mic Audio Source that will make the communication behavior degrade for the app we are developing.

**Comment by karasusan** [comment]
＠ysheung
Hi, we changed the implementation about the audio input, so we need to cut off the audio for loopback.
We made a sample describing how to use the microphone for audio input. This sample is in the Unity Render Streaming 3.1.0-exp.3 which will release soon.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/657

**Comment by ysheung** [comment]
> @ysheung Hi, we changed the implementation about the audio input, so we need to cut off the audio for loopback. We made a sample describing how to use the microphone for audio input. This sample is in the Unity Render Streaming 3.1.0-exp.3 which will release soon. [Unity-Technologies/UnityRenderStreaming#657](https://github.com/Unity-Technologies/UnityRenderStreaming/pull/657)

Thank you for the reply.
We are looking forward to check the sample in Unity Render Streaming 3.1.0-exp.3.
Is there any updated released date?
We would also try to copy those related class to have a try in our current code.
Thank you very much.

**Comment by ysheung** [comment]
> @ysheung Hi, we changed the implementation about the audio input, so we need to cut off the audio for loopback. We made a sample describing how to use the microphone for audio input. This sample is in the Unity Render Streaming 3.1.0-exp.3 which will release soon. [Unity-Technologies/UnityRenderStreaming#657](https://github.com/Unity-Technologies/UnityRenderStreaming/pull/657)

We have checked the Unity Render Streaming 3.1.0-exp.3.
Which I think MicrophoneStreamSender.cs is the part you want us to check in the sample.
As I see right now it requires the Unity Render Streaming Package for it because of the StreamSenderBase and StreamReceiverBase defination is not there. And couple callbacks isn't defined too.

Does it mean right now the Unity WebRTC package needs the Unity Render Streaming Package for muting the mic?
Is it possible to provide a sample that only requires the Unity WebRTC package?

Thank you very much.

**Comment by karasusan** [comment]
@ysheung
Do you think we should fix the issue in the WebRTC package?
It is possible for us.

**Comment by karasusan** [comment]
memo: WRS-230

**Comment by ysheung** [comment]
> @ysheung Do you think we should fix the issue in the WebRTC package? It is possible for us.
For those projects already working with the WebRTC package only, I think the answer is yes since there isn't any workaround to fix the mic problem with the current released version.
Thank you very much.

**Comment by dl4mmers** [comment]
Hey,

we also updated our iOS application to work with WebRTC 2.4.0-exp.6 and encountered this problem. In version 2.4.0-exp.4 audio connection, as well as mute and unmute, worked well, except for a big delay and sometimes duplicate output of some parts of the recorded microphone input. After updating to version WebRTC 2.4.0-exp.4, the audio connection seems complete unusable, because we cannot mute InputAudioSource and as a result, the recorded input is always being output on the speaker of the same device. This generates an echo and the receiving peer only hears loud noise. 

It would be very nice if this issue could be fixed, so that the recorded input can be muted on the sending peer (like in 2.4.0-exp.4) without the receiving peer hearing nothing.

**Comment by karasusan** [comment]
@dl4mmers
Sure. I understood.
Is it no problem to make mute the loopback of microphone as default?

**Comment by dl4mmers** [comment]
@karasusan 
I think this should be default and it should be controllable via AudioSource. For local testing the loopback is good for verifying that the microphone works, but for production builds, the local loopback should be deactivatable via `AudioSource.Mute` prop without having the receiving side hearing nothing.

**Comment by karasusan** [comment]
@dl4mmers
AudioSource.mute property have to be enabled to stream audio because the feature use `MonoBehaviour.OnAudioFilterRead` API.

Maybe We add the property to enable/disable loopback audio on the component.

**Comment by dl4mmers** [comment]
@karasusan 
Ah okay, then new property to control loopback sounds good 👍

**Comment by SaIG** [comment]
Is there something we can do in the meantime? 
I tried reading directly from the Mic AudioClip and set Data to sourceaudiostream ... but i only get some kind of looped audio or distorted audio ... maybe i oversaw something while implementing ... if you thing this way could work i'd love some feedback on how to get it right


`    int pos = 0;
    int lastPos = 0;
    private void UpdateAudio()
    {
        if (MicrophoneClip == null || sourceAudioStreamTrack == null)
            return;

        if ((pos = Microphone.GetPosition(currenMicDeviceName)) > 0)
        {
            if (lastPos > pos) lastPos = 0;

            if (pos - lastPos > 0)
            {
                // Allocate the space for the sample.
                float[] sample = new float[(pos - lastPos) * MicrophoneClip.channels];

                // Get the data from microphone.
                MicrophoneClip.GetData(sample, pos); // -> result in less audio transmitted and somehow distorted?!
                //MicrophoneClip.GetData(sample, 0); // -> results in one second looped audio transmitted


                sourceAudioStreamTrack.SetData(sample, MicrophoneClip.channels, MicrophoneClip.frequency);
                
            }
        }`

**Comment by karasusan** [comment]
@SaIG
I recommend that you use `MonoBehaviour::OnAudioFilterRead` method to capturing audio
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Runtime/Scripts/AudioCustomFilter.cs#L44-L47

**Comment by ysheung** [comment]
@karasusan
Thank you for the status update.
Could we know when will be 2.4.0-exp.7 release ?
Early May? Mid May? Late May?
We are waiting for this version update for our app to release.
Thank you very much.

**Comment by karasusan** [comment]
@ysheung
We planned the release date on May 20th.

**Comment by ysheung** [comment]
> @ysheung We planned the release date on May 20th.

Appreciate for the release date update.
We have been started to test the new feature and so far it stopped the mic loopback without any problem.
Thank you.
