### ISSUE TITLE
[BUG]: MSAA with Forward Rendering in HDRP causes a flickering rescaling of the stream

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#639]
### Package version

2.4.0-exp.6

### Environment

```markdown
* OS: Windows 10
* Unity version: 2021.2
```

### Steps To Reproduce

1. Create a Forward rendering HDRP scene with MSAAx2 or higher enabled.
2. Observe the stream flickers between the correct scale and a much larger scale.

### Current Behavior

Flickering between a correctly scaled picture and a weirdly overlarge picture.

### Expected Behavior

MSAA should probably work, not sure why it wouldn't. Is the antialiasing property on the render texture relevant?

**Comment by karasusan** [comment]
memo: WRS-252

**Comment by doctorpangloss** [comment]
In a few weeks I'll have time for a reproduction. MSAA is important.

**Comment by karasusan** [comment]
Is this a same issue?
https://forum.unity.com/threads/msaa-with-render-texture-on-hdrp.1118305/

**Comment by doctorpangloss** [comment]
Exploring some fixes this week - I will try what the user said.

**Comment by doctorpangloss** [comment]
Resolved in 2.4.0-exp7

**Comment by doctorpangloss** [comment]
I can reproduce this in a scene that uses Low Resolution Transparent via a VFX graph particle effect. Pretty tricky. I'll prepare a reproduction for you soon.

**Comment by karasusan** [comment]
Could you share the video recording the issue?

**Comment by doctorpangloss** [comment]
> @doctorpangloss
> Could you share the video recording the issue?

I'll do it before the week ends. I will discuss with my Unity support, maybe we can setup a meeting and I'll share my work with you.

**Comment by karasusan** [comment]
@doctorpangloss
I am waiting for sharing the video, thanks.

**Comment by doctorpangloss** [comment]
This has been resolved! Thank you
