### ISSUE TITLE
[BUG]: GetStats Causing Memory Leak

### ISSUE THREAD

**Issue by AustinMathuw** [Unity-Technologies/com.unity.webrtc#678]
### Package version

2.4.0-exp.6

### Environment

```markdown
* OS: Windows 10
* Unity version: 2021.1.13f1
```

### Steps To Reproduce

1. Open the Stats sample scene from the provided Samples.
2. Modify [line 284 of StatsSample.cs](https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Samples~/Stats/StatsSample.cs#L284) to `yield return new WaitForSeconds(0.0f);` to speed up the memory leak.
- **NOTE:** This step only amplifies the leak, we also saw the leak occuring when there is no change to this file.
4. Open Task Manager.
5. Run the Stats scene and watch the memory steadily go up in Task Manager.

### Current Behavior

I first saw this in my own scene in which I wanted to see realtime WebRTC stats in a text box. After some work, we noticed that the memory usage kept going up at every call to the GetStats() method. We confirmed this behaviour first by removing everything in our method but the single call to GetStats, then moving to see if we could replicate in the Stats sample scene.

After about 10 minutes of running the Stats sample with the calls to the GetStats() method happening as fast as possible, we saw that a little over 2000 MB of memory leaked.

### Expected Behavior

We expect that there is no memory leak from calling the GetStats method.

### Anything else?

We tested a build on Android and Windows with both experiencing a memory leak. Further, the memory is only released when the play session is over.

**Comment by kannan-xiao4** [comment]
@AustinMathuw 
Thanks you for reporting. We will check this issue.
memo: WRS-283

**Comment by kannan-xiao4** [comment]
Fixed in https://github.com/Unity-Technologies/com.unity.webrtc/pull/816
