### ISSUE TITLE
[BUG]: Crash when rendering multiple (10+) video streams at once

### ISSUE THREAD

**Issue by marcin-aicradle** [Unity-Technologies/com.unity.webrtc#681]
### Package version

2.4.0-exp.5

### Environment

```markdown
* OS: Windows10
* Unity version:2020.3.32f1
```

### Steps To Reproduce

1. Open multiple (10+) connections (RTCPeerConnection) to different cameras.
2. Render video from all of them.
3. The issue is frequent but does not happen every time

The result:

Crash!!!
...
========== OUTPUTTING STACK TRACE ==================

0x00007FFB5CA00720 (webrtc) GetUpdateTextureFunc
0x00007FFB5CA00648 (webrtc) GetUpdateTextureFunc
0x00007FFB5C9FF28C (webrtc) GetUpdateTextureFunc
0x00007FFB5C9FB1BA (webrtc) GetUpdateTextureFunc
0x00007FFB5D8EE146 (webrtc) GetUpdateTextureFunc
0x00007FFB5D3C7611 (webrtc) GetUpdateTextureFunc
0x00007FFB5D3D49FE (webrtc) GetUpdateTextureFunc
0x00007FFB5D3D96EA (webrtc) GetUpdateTextureFunc
0x00007FFB5CA32A4B (webrtc) GetUpdateTextureFunc
0x00007FFB5CA2FF0B (webrtc) GetUpdateTextureFunc
0x00007FFB5CA31388 (webrtc) GetUpdateTextureFunc
0x00007FFB5CA305B8 (webrtc) GetUpdateTextureFunc
0x00007FFB5CA32BA3 (webrtc) GetUpdateTextureFunc
0x00007FFBB8E57034 (KERNEL32) BaseThreadInitThunk
0x00007FFBB92E2651 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

I wonder if `GetUpdateTextureFunc ` should not have a lock before `s_context = context;` ?

**Comment by karasusan** [comment]
Surely I haven't check the situation you saying. 😅 
I will add the test case. Thank you.

**Comment by marcin-aicradle** [comment]
Actually, it can crash with only a single camera.
Any idea why this can happen?

**Comment by marcin-aicradle** [comment]
I was able to get a better stack trace:

========== OUTPUTTING STACK TRACE ==================

0x00007FFD52BF0B50 (webrtc) rtc::webrtc_checks_impl::UnreachableCodeReached
0x00007FFD52BF0A78 (webrtc) rtc::webrtc_checks_impl::FatalLog
0x00007FFD52BEF6BC (webrtc) rtc::webrtc_checks_impl::LogStreamer<>::Call<>
0x00007FFD52BEB53A (webrtc) rtc::webrtc_checks_impl::FatalLogCall<0>::operator&<>
0x00007FFD53ADEF26 (webrtc) webrtc::internal::VideoQualityObserver::OnDecodedFrame
0x00007FFD535B83E1 (webrtc) webrtc::internal::ReceiveStatisticsProxy::OnDecodedFrame
0x00007FFD535C57CE (webrtc) std::_Tree<std::_Tmap_traits<__int64,unsigned __int64,std::less<__int64>,std::allocator<std::pair<__int64 const ,unsigned __int64> >,0> >::erase<std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<__int64 const ,unsigned __int64> > > >,0>
0x00007FFD535CA4BA (webrtc) rtc::webrtc_logging_impl::LogStreamer<rtc::webrtc_logging_impl::Val<9,char const * __ptr64>,rtc::webrtc_logging_impl::Val<1,int>,rtc::webrtc_logging_impl::Val<9,char const * __ptr64>,rtc::webrtc_logging_impl::Val<1,int>,rtc::webrtc_logging_impl::Val<9,char const * __ptr64>,rtc::webrtc_logging_impl::Val<1,int>,rtc::webrtc_logging_impl::Val<9,char const * __ptr64>,rtc::webrtc_logging_impl::Val<1,int>,rtc::webrtc_logging_impl::Val<9,char const * __ptr64>,rtc::webrtc_logging_impl::Val<7,double>,rtc::webrtc_logging_impl::Val<9,char const * __ptr64>,rtc::webrtc_logging_impl::Val<3,__int64>,rtc::webrtc_logging_impl::Val<9,char const * __ptr64>,rtc::webrtc_logging_impl::Val<13,rtc::webrtc_logging_impl::LogMetadata> >::Call<rtc::webrtc_logging_impl::Val<7,double> >
0x00007FFD52C22F8B (webrtc) rtc::Thread::QueuedTaskHandler::OnMessage
0x00007FFD52C2044B (webrtc) rtc::Thread::Dispatch
0x00007FFD52C218C8 (webrtc) rtc::Thread::ProcessMessages
0x00007FFD52C20AF8 (webrtc) rtc::Thread::Run
0x00007FFD52C230E3 (webrtc) rtc::Thread::PreRun
0x00007FFDB96A7034 (KERNEL32) BaseThreadInitThunk
0x00007FFDB9F02651 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

Any idea what's the reason?
thx

**Comment by marcin-aicradle** [comment]
Ok, I found the reason.
The crash was related to the fact I was using a debug version of the plugin, which is bound to a debug version of the webrtc library which in debug mode throws such exceptions (https://github.com/mozilla/libwebrtc/blob/075db397562d14e8bd472428763d50b5e8e9c17e/video/video_quality_observer.cc#L242) when the incoming video stream is not perfect.
