### ISSUE TITLE
[BUG]: Vulkan plugin method used doesn't allow for other plugins

### ISSUE THREAD

**Issue by bpepers-me** [Unity-Technologies/com.unity.webrtc#686]
### Package version

2.4.0-exp.6

### Environment

```markdown
* OS: Linux
* Unity version: 2021.2
```

### Steps To Reproduce

1. Unpack the attached archive
2. Follow instructions in the README
3. Will show that unable to intercept Vulkan initialization for more than 1 graphics plugin between WebRTC and this plugin

### Current Behavior

Both plugins can't intercept the Vulkan initialization.

### Expected Behavior

Multiple plugins should be able to intercept the Vulkan initialization.

### Anything else?

Attachment is here: https://drive.google.com/file/d/1OpWpEM9g2qQ2O7eI1FXKpNaGwRCH2bHF/view?usp=sharing

This issue was also investigated internally by the ISS team and this is what they found:

It is possible to intercept Vulkan initialization in more than one graphics plugin using the newer interface: IUnityGraphicsVulkanV2​

To demonstrate this, I made some modifications to the GfxPluginVulkan.cpp source file you sent and tested it to make sure it works:
Line 18 has been changed to use IUnityGraphicsVulkanV2 instead of IUnityGraphicsVulkan
Line 20 has been changed to use the AddInterceptInitialization method instead of the InterceptInitialization method which allows you to specify a priority. I set the priority to 5 in my example which worked for me but you may need to modify this to suit your project.

The new DLL I built from the modified file is called GfxPluginVulkan.dll and is in the Plugins folder that I've attached and outputs its log to plugin2.log. I left your original GfxPluginVulkan1.dll for testing which uses your original script that uses the old interface.

The new VulkanV2 interface is compatible with the old one as InterceptInitialization always uses the max priority value stored in kUnityVulkanInitCallbackMaxPriority, so as long as the priority of each plugin initialization is different, both will be initialized. More information about the AddInterceptInitialization method can be found in the comments from line 243 in IUnityGraphicsVulkan.h. 

It appears that the Render Streaming Package uses uses the old interface so I can submit a bug report to remedy this in the future if you would like me to?

**Comment by karasusan** [comment]
Thanks for reporting your issue.
I fixed the issue before reporting this issue, so I will check whether it works correctly with your use-case.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/683

**Comment by foijord** [comment]
Hi, I believe this issue can be closed. Using the newer API allows for multiple plugins, as long as max priority is not used.
