### ISSUE TITLE
[BUG]: m_encodeConfig.encodeCodecConfig.h264Config.level = m_level causes NV_ENC_ERR_INVALID_PARAM

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#702]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS: Windows 11
* Unity version: 2021.2.15f1 DX11
```

### Steps To Reproduce

1. Build and run a debug build of the library on an NVIDIA GPU equipped Windows computer.
2. Select an H264 codec for the transceiver. I chose one using `codec.sdpFmtpLine.Contains("profile-level-id=420033")`
3. Observe a crash on line 251 of NvCodec.cpp due to an NV_ENC_ERR_INVALID_PARAM.

By process of elimination, this line was the invalid parameter:
https://github.com/Unity-Technologies/com.unity.webrtc/blob/306cb714903b5e50711008a75885c2d59806ba93/Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp#L127

It appears all the profile IDs are incorrectly decoded as level `NV_ENC_LEVEL_H264_31` and this results in a crash.

Additionally, I tried upgrading (and patching) to the latest NVIDIA Codec SDK and CUDA 11, and neither fixed the issue.

### Current Behavior

A crash.

### Expected Behavior

Correctly initializing the codec.

### Anything else?

2.4.0-exp7 is a tremendous update.

**Comment by doctorpangloss** [comment]
When debugging, I observed that in the constructor here
https://github.com/Unity-Technologies/com.unity.webrtc/blob/306cb714903b5e50711008a75885c2d59806ba93/Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp#L48
`m_level` is always being decoded as `NV_ENC_LEVEL_H264_31`, which doesn't sound right to me. I stepped through the profile generation here:
https://github.com/Unity-Technologies/com.unity.webrtc/blob/306cb714903b5e50711008a75885c2d59806ba93/Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp#L71
And it's definitely emitting `NV_ENC_LEVEL_H264_52`.

**Comment by karasusan** [comment]
The constructor is called from the encoder factory class below.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/306cb714903b5e50711008a75885c2d59806ba93/Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp#L96

The profile level is contained in the SDP which the result of the negotiation between peers.

**Comment by doctorpangloss** [comment]
This is a pretty mysterious one. It reminds me of the Metal bug I saw - it felt like the debugger was lying to me. Maybe I am using it incorrectly, or the error is a red herring?

**Comment by doctorpangloss** [comment]
Apple Silicon M1 Max and iPhone 12 Pro.

**Comment by karasusan** [comment]
memo: [WRS-316](https://jira.unity3d.com/browse/WRS-316)

**Comment by doctorpangloss** [comment]
Resolved
