### ISSUE TITLE
[BUG]: SetRates is called a lot, causing a flickering in the stream due to SetStreamState(true);

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#703]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS: Windows 11
* Unity version: 2021.2.15f1
```

### Steps To Reproduce

1. Observe SetRates is called a lot and the stream appears to flicker into a low-resolution appearance.
2. Removing `SetStreamState(true);` (i.e., not forcing an IDR frame) fixes the issue.

### Current Behavior

A flicker every 2-3s of a low resolution picture.

### Expected Behavior

Clean stream.

**Comment by karasusan** [comment]
Could you point me where `SetRates` is? Is it native code?

**Comment by doctorpangloss** [comment]
https://github.com/Unity-Technologies/com.unity.webrtc/blob/306cb714903b5e50711008a75885c2d59806ba93/Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp#L435

**Comment by doctorpangloss** [comment]
Removing this `SetStreamState` line is one part of fixing https://github.com/Unity-Technologies/com.unity.webrtc/issues/632 . The other part is to get rid of the bitrate adjuster since it's redundant. I observed and fixed the fuzzy pulses this way.

**Comment by karasusan** [comment]
@doctorpangloss
OK, I will check it.
What resolution are you testing?

**Comment by karasusan** [comment]
memo: WRS-300

**Comment by doctorpangloss** [comment]
> @doctorpangloss
> OK, I will check it.
> What resolution are you testing?

A weird one: 1408x2204.

I do see "unsupported" errors due to the profile/level check but there's a lot of weird stuff going on.

**Comment by karasusan** [comment]
@doctorpangloss
What kind of weird stuff?

**Comment by karasusan** [comment]
@doctorpangloss
This issue is already fixed. Can I close the issue?

**Comment by karasusan** [comment]
@doctorpangloss
We haven't reproduced the issue yet. I need to make the environment that is easier to reproduce the issue. 
Do we need to set the GOP length and removing the keyframe request?

**Comment by doctorpangloss** [comment]
This issue is resolved, I have narrowed down a reproducible one in 2.4.0-exp.8
