### ISSUE TITLE
[BUG]: The WebRTC Stats window errors with BadImageFormatException: Method has zero rva

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#706]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS: Windows 11
* Unity version: Unity 2021.2.15f1
```

### Steps To Reproduce

1. Open the stats window.
2. Observe the error in the current behavior in the console.

### Current Behavior

```
BadImageFormatException: Method has zero rva
Unity.WebRTC.RTCStatsReport..ctor (System.IntPtr ptr) (at com.unity.webrtc/Runtime/Scripts/RTCStats.cs:794)
Unity.WebRTC.RTCStatsReportAsyncOperation+<>c.<.ctor>b__4_1 (System.IntPtr ptr_) (at com.unity.webrtc/Runtime/Scripts/WebRTC.AsyncOperation.cs:43)
Unity.WebRTC.WebRTC.FindOrCreate[T] (System.IntPtr ptr, System.Func`2[T,TResult] constructor) (at com.unity.webrtc/Runtime/Scripts/WebRTC.cs:740)
```

### Expected Behavior

The stats window should work.

**Comment by karasusan** [comment]
memo: [WRS-303](https://jira.unity3d.com/browse/WRS-303)

**Comment by doctorpangloss** [comment]
I received another error message about `[DllImport]`, now I have to reproduce it and I'll update the ticket. Maybe it is working on your end, I could modified something and accidentally broke this.

**Comment by doctorpangloss** [comment]
This was my error.
