### ISSUE TITLE
[BUG]: RTCErrorException:Missing steam ID in msid attribute

### ISSUE THREAD

**Issue by Deepslient** [Unity-Technologies/com.unity.webrtc#710]
### Package version

2.4.0-exp.6

### Environment

```markdown
* OS:
* Unity version:2020.3.16
```

### Steps To Reproduce

after get the sdpoffer

### Current Behavior

when setremotedescription the issues occurs

### Expected Behavior

normal

### Anything else?

![1651028922(1)](https://user-images.githubusercontent.com/25860422/165431982-1f797f0b-6e87-4481-9489-baea2c5e395d.png)

**Comment by Deepslient** [comment]
anyone else help me

**Comment by karasusan** [comment]
@Deepslient
Could you tell me more detail to reproduce the issue?
