### ISSUE TITLE
[BUG]: iOS build with XCode 13.3

### ISSUE THREAD

**Issue by marcin-aicradle** [Unity-Technologies/com.unity.webrtc#719]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS:
* Unity version:
```

### Steps To Reproduce

I've made some modifications in the plugin and wanted to build it for different platforms.
I'm using XCode 13.3.1 and I was able to build it for macOS but I'm no able to build it for iOS.
I'm getting linker error:
`ld: framework not found ApplicationServices`

The build is successful only when I exclude arm64 architecture.
I wonder if you encountered such issue?
I'd appreciate any advice.

**Comment by karasusan** [comment]
@marcin-aicradle 
We are using the same version of XCode for build plugin.
It seems CMake cache for macOS is remained in your working directory. Please try to clean up your working directory and run the command below again.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/BuildScripts~/build_plugin_ios.sh

**Comment by marcin-aicradle** [comment]
Yes, that solves the issue. Thanks a lot!
