### ISSUE TITLE
I need the iframe of the video in H264 encoding format, otherwise my mobile device cannot view the image of unity. In addition, when I switch the unity picture to the mobile picture, the unity picture will get stuck.

### ISSUE THREAD

**Issue by EricUUU** [Unity-Technologies/com.unity.webrtc#730]
### Is your feature request related to a problem?

I need the iframe of the video in H264 encoding format, otherwise my mobile device cannot view the image of unity. In addition, when I switch the unity picture to the mobile picture, the unity picture will get stuck.

### Describe the solution you'd like

When I want to encode, there is an I-frame request. When I-frame message is decoded, I-frame is sent

### Additional context

![QQ截图20220518154757](https://user-images.githubusercontent.com/9947921/168986085-1d625a00-f85e-4284-816e-85b30a1598c5.jpg)

**Comment by EricUUU** [comment]
When I use VP8 format coding, the function I want is OK, but there are some problems with I-frame request in H264.

**Comment by EricUUU** [comment]
@karasusan  Help me

**Comment by karasusan** [comment]
@EricUUU
How do I test your issue?

**Comment by EricUUU** [comment]
![KeyFrame](https://user-images.githubusercontent.com/9947921/169185477-e505ba88-21f0-4562-bdd3-92bdbf379ad8.jpg)

**Comment by EricUUU** [comment]
![KeyFrame](https://user-images.githubusercontent.com/9947921/169185543-f92eb8b6-6cf5-48c6-a1d1-f2ed52ca8988.jpg)
[077:589](packet_buffer.cc:304): Received H.264-IDR frame (SPS: 0, PPS: 0). Treating as key frame since WebRTC-SpsPpsIdrIsH264Keyframe is disabled @karasusan

**Comment by EricUUU** [comment]
H264 no keyframe request and keyframe message @karasusan
