### ISSUE TITLE
I need H264 encoder to add key frames, and decoder to listen for key frame messages and key frame methods

### ISSUE THREAD

**Issue by EricUUU** [Unity-Technologies/com.unity.webrtc#732]
### Is your feature request related to a problem?

I'm always frustrated when [...]

### Describe the solution you'd like

I need H264 encoder to add key frames, and decoder to listen for key frame messages and key frame methods

### Describe alternatives you've considered

I need H264 encoder to add key frames, and decoder to listen for key frame messages and key frame methods

**Comment by karasusan** [comment]
@EricUUU
Is it the same issue? If so, please close old one.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/730

**Comment by EricUUU** [comment]
> 
OK, but you have to help me, brother

**Comment by EricUUU** [comment]
> @EricUUU 是同一个问题吗？如果是这样，请关闭旧的。 #730

OK, but you have to help me, brother @karasusan

**Comment by EricUUU** [comment]
hi @karasusan

**Comment by karasusan** [comment]
@EricUUU
We don't have a plan to support sending the key frame intentionally. I would like to know how you use the feature.
