### ISSUE TITLE
[BUG]: Unity Editor crashed when running sample scene

### ISSUE THREAD

**Issue by ysheung** [Unity-Technologies/com.unity.webrtc#734]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS:Windows10
* Unity version:Unity 2020.3.19f1
```

### Steps To Reproduce

1.Open a new Unity 2020.3.19f1 project.
2.Add UnityWebRTC 2.4.0-exp.7 package to the project
3.Import the samples from Package Manager.
4.Open the MediaStream scene.
5.Play the MediaStream scene on Unity editor.
6.Unity editor crashed with error message like [below.]
7.Same behaviour if we build the scene as an exe.

### Current Behavior

The samples scene is not able to be played on editor or as a built unity player, which came with error message.

### Expected Behavior

The samples scene should be able to be played on editor or as a built unity player without error message.

### Anything else?

![crasherrormessage](https://user-images.githubusercontent.com/44356157/170184948-53f51b5d-d474-4ea4-91a8-c1ffc833e9ec.png)
This problem happened on one of our PC, but fine on some other PC.
The sample is fine when the project was using 2.4.0-exp.4 2.4.0-exp.5 2.4.0-exp.6.
This problem happens since we updated to 2.4.0-exp.7 or just pull the latest version from this git.
It said it is about the runtime library, so we capture the runtime library installed on that pc as reference.
![runtime](https://user-images.githubusercontent.com/44356157/170189506-f0ea6e0f-3f3d-463b-8b36-f6a873f1251d.png)
Is there any details about the required windows runtime library for 2.4.0-exp.7 ?
Thank you very much.

**Comment by ysheung** [comment]
We have checked that there isn't any crash log output since that error message popup when run it on editor.
We can provide the log that output from the built player but it is just abort when the error popup.
Please check it.
Thank you very much.
[Player.log](https://github.com/Unity-Technologies/com.unity.webrtc/files/8768786/Player.log)

**Comment by ysheung** [comment]
We also have another PC that gives different behaviour that it was crashed without that error message.
And here is the log file
[Player_2.log](https://github.com/Unity-Technologies/com.unity.webrtc/files/8768810/Player_2.log)
[error_2.log](https://github.com/Unity-Technologies/com.unity.webrtc/files/8768811/error_2.log)

**Comment by karasusan** [comment]
@ysheung
Could you try to upgrade the graphic driver?

**Comment by ysheung** [comment]
[NVIDIA System Information 05-25-2022 16-51-54.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/8769114/NVIDIA.System.Information.05-25-2022.16-51-54.txt)
Here is the system info from the pc creahed with editor.
We are trying to update it.
Is there specific graphic board requirements for 2.4.0-exp.7?

**Comment by ysheung** [comment]
@karasusan 
The pc came with error popup windows works fine now with the latest nvidia driver version 512.78.
We are trying to update another pc to solve the crash problem.
It will be thankful to know the minimum requirement of graphic board and drivers.
Thank you very much.

**Comment by ysheung** [comment]
@karasusan 
The second pc crashed with different behavior is working fine with the nvidia driver version 512.78 too.
Seems the 2.4.0-exp.7 will need specific support by the graphic driver.

**Comment by karasusan** [comment]
@ysheung
Thanks for sharing the detail of issue.
I am sure that we need to avoid the crash caused by the NVIDIA driver version.

**Comment by karasusan** [comment]
memo: WRS-335

**Comment by ysheung** [comment]
@karasusan 
Thank you for the hint about the graphic driver.
We were planning to run the application on some rack pc that came with Intel Xeon E-2334 CPU which doesn't have any extra graphic board and graphic chipset. Will this kind of hardware specification satisfy the requirements?
Thank you very much.

**Comment by randjtw** [comment]
The same problems.
Graphic card: GT-425M(Driver Version: 391.35)
Unity Version: 2020.3.17f1, 2020.3.26f1
Scenes: Menu, PeerConnection

**Comment by jinnyuri** [comment]
I faced the same issue.
I have 2 Windows desktops the problem occurs on all the ones.

Unity2021.3.3f1
WebRTC 2.4.0-exp.7
Windows10
Nvidia GeForce 920MX (Driver 430.63)
Nvidia GeForce GT730 (Diriver 430.64)

**Comment by karasusan** [comment]
@ysheung
Hi, I fixed the issue in the PR #741.
If the driver version is old than required one to use hardware codec, it removes HW codecs from options of codecs.

**Comment by ysheung** [comment]
> @ysheung Hi, I fixed the issue in the PR #741. If the driver version is old than required one to use hardware codec, it removes HW codecs from options of codecs.

Thank you for the information.
Is there any planned release date for 2.4.0-exp.8 that we could manage to have a test on different device.
Thank you very much.

**Comment by karasusan** [comment]
@ysheung
The release date is the end of June. 
Note that this fix is for avoiding the crash, not support the old driver.

**Comment by ysheung** [comment]
> @ysheung The release date is the end of June. Note that this fix is for avoiding the crash, not support the old driver.

Thank you for the reply.
If it is not supporting the old driver, what will happen when the driver doesn't support CUDA 11.0 or not supporting CUDA at all?

**Comment by karasusan** [comment]
@ysheung
If it is the situation as you said, NvCodec is excluded from options of video codec. And no crash.

**Comment by dziegielewski** [comment]
I was able to fix it by updating the video driver (gforce 850m latest old 2018, took a bit to find) and disabling the intel graphics device.
