### ISSUE TITLE
How can I compile an I-frame when I receive an I-frame message n

### ISSUE THREAD

**Issue by EricUUU** [Unity-Technologies/com.unity.webrtc#735]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS:Windows10
* Unity version:Unity 2021.3
* Codec:H264
```

### Steps To Reproduce

![iFReame](https://user-images.githubusercontent.com/9947921/170203643-cbb43f96-25e3-49c2-807f-4a06e1aaedb7.jpg)
How can I compile an I-frame when I receive an I-frame message，
My purpose is to send an I frame in time when I receive the I frame request，
Help me @kara

**Comment by EricUUU** [comment]
@karasusan

**Comment by EricUUU** [comment]
Hello, I have a question. Can I share this screen   @karasusan

**Comment by karasusan** [comment]
@EricUUU
Please make the sample for reproducing your issue. Thank you.

**Comment by karasusan** [comment]
@EricUUU
Can you make the sample for fixing your issue? Or may I close the issue?

**Comment by EricUUU** [comment]
No I can't

**Comment by karasusan** [comment]
@EricUUU
I am sorry but I cannot reproduce your issue without your contribution.

**Comment by EricUUU** [comment]
> @EricUUU 很抱歉，如果没有您的贡献，我无法重现您的问题。

OH
