### ISSUE TITLE
I wrote WebSocket Signaling base application

### ISSUE THREAD

**Issue by gtk2k** [Unity-Technologies/com.unity.webrtc#77]
https://github.com/gtk2k/UnityWebRTCTest

I am trying to implement Trickle ICE using WebSocket based on RenderStreaming.cs of UnityRenderStreaming, but after running the project, if I connect from a Web Page, Unity crashes.
The line in error is the yield return ret line of processAnswer (). (Line with // ****)
What's wrong?

Win10 2004 (19041.84)
Unity 2019.3.1f1

**Comment by karasusan** [comment]
Thanks for the sharing of your great work!
There is a team in Unity have tried to implement the signaling feature made with WebSocket. And it is working correctly.

This PR is helpful for you, but be careful that it have not been merged to master branch yet.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/209/files

**Comment by gtk2k** [comment]
Thanks!
Investigate yourself what is wrong compared to the implementation code introduced.

**Comment by ZFHung** [comment]
which file?
