### ISSUE TITLE
[BUG]: terrible crash

### ISSUE THREAD

**Issue by gawinwong** [Unity-Technologies/com.unity.webrtc#770]
### Package version

2.4.0-exp.8

### Environment

```markdown
* OS: Ubuntu 18.04
* Unity version: 2020.3.3
```

### Steps To Reproduce

use latest com.unity.webrtc on develop branch

### Current Behavior

When I use web to establish a connection, the unity editor will crash.

### Anything else?

I think this crash may be due to the commit "ad69bd225ed121fab0e5a812343d21f5a1b87b8e".
```diff
- var streamId = stream == null ? Guid.NewGuid().ToString() : stream.Id;
+ var streamId = stream?.Id;
```

**Comment by karasusan** [comment]
@gawinwong 
Can I have the code to reproduce the crash?

**Comment by gawinwong** [comment]
Just use the broadcast sample and the web app offered by unity render streaming.

**Comment by karasusan** [comment]
@gawinwong
I checked the broadcast sample but not reproduced.
I assume that the native plugin is not updated the latest version in your environment.

This pull request updates plugins and already merged to develop branch.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/771

**Comment by gawinwong** [comment]
The problem has been solved with the latest version, thanks a lot.
