### ISSUE TITLE
[REQUEST]: Quality metrics from the encoder

### ISSUE THREAD

**Issue by DenizUgur** [Unity-Technologies/com.unity.webrtc#775]
### Is your feature request related to a problem?

It would be nice to have a quality assessment feature built into the WebRTC package. Similar to how it was described [here](https://webrtc.googlesource.com/src/+/refs/heads/main/test/pc/e2e/g3doc/default_video_quality_analyzer.md).

### Describe the solution you'd like

Minimally, I would like to get SSIM and PSNR value for comparison between original frame and encoded frame.

### Describe alternatives you've considered

I assumed I could use OpenCV to get the assessment I needed, on the basis that the pointer [here](https://github.com/Unity-Technologies/com.unity.webrtc/blob/f20c3254090c299bcd6ab32cded9e78b1024ad83/Runtime/Scripts/VideoStreamTrack.cs#L254) was updated with the new frame.

### Additional context

With my previous assumption of that `WebRTC.Context.Encode(*ptr)` was updating the pointer here with the new frame I've tried to accomplish my goal with these modifications: [VideoStreamTrack.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9126977/VideoStreamTrack.txt)

**Comment by karasusan** [comment]
@DenizUgur
Oh, it is a good suggestion for us.
So far we have considered about the evaluation method of quality and performance of video coding. I feel this method is valuable for the first step.

**Comment by karasusan** [comment]
@DenizUgur
Unfortunatelly, right now we don't have the API to get buffers directly.
Could you use `Texture` instances to evaluate?

**Comment by DenizUgur** [comment]
I need to asses the quality of the encoded image. After looking through the source code I couldn't find where that encoded image gets feeded to the C# runtime. At this point I'm looking towards decoding the `m_encodedImage` with `NvDecoder` to get a `VideoFrame`. After than `I420SSIM` can be used (at least in theory). I couldn't test this yet.

It's a hacky solution for sure.

**Comment by DenizUgur** [comment]
@karasusan I assume you don't have any recommendations for this right?

**Comment by karasusan** [comment]
@DenizUgur
I am sorry but I don't have the good suggestion for accessing encoded data.

**Comment by DenizUgur** [comment]
I see, no worries. I'll post my findings here if I'm successful with it.
