### ISSUE TITLE
[BUG]: Example scenes not working on Android

### ISSUE THREAD

**Issue by zentwisty** [Unity-Technologies/com.unity.webrtc#779]
### Package version

2.4.0-exp.8

### Environment

```markdown
* OS: Android 11
* Device: moto g power (2021)
* Unity version: 2021.3.4f1
```

### Steps To Reproduce

1. Install the package and the example scenes.
2. Change build settings (set scripting backend to IL2CPP, disable ARMv7 and enable ARM64 target architectures, disable Optimize Frame Pacing according to #437 and also force OpenGLES3).
4. Build to Android.
5. Run the menu scene, then click on the PeerConnection scene button. Click Start then Call.

### Current Behavior

The video isn't streaming to the second screen. However, the project does work correctly when I run in Editor and build to Windows.

Sometimes the application will crash if I try to continue using it.
Note also that I also tried to run a build where I didn't force OpenGLES3, and the app would crash immediately when I clicked the Call button.

![Screenshot_20220721-124303](https://user-images.githubusercontent.com/60015082/180270915-845212da-a48a-437a-8994-47be6577377d.png)

Logs from LogCat:
[log.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9161322/log.txt)

(I haven't posted issues on GitHub before, so if there's any other information you need from me to fix this bug, please tell me what to get for you.)

### Expected Behavior

I expect it to work as it does in the Editor and in the Windows build. I didn't change any of the code; I'm running exactly what I downloaded for the example scenes.

**Comment by karasusan** [comment]
Thank you for sharing the issue. 
There is no clue in the log file, unfortunatelly. I would like to see the crash log but nothing in it.

It might be caused by the graphics API,  how about Vulkan API?

**Comment by karasusan** [comment]
@zentwisty
Hi, have you solved the issue? Thanks.

**Comment by KeigoTakamura** [comment]
@karasusan 


In conclusion, the Pear Connection sample is not working on Android 11 ~ Android 12 devices.
In my product, I know that when I do `new VideoStreamTrack (texture)`; on Android 11 and 12, it crashes.
Virtually exp8 is a situation that is completely useless on new Android devices.

In my environment, the above phenomenon is reproduced on Xperia 5 III (Android12) and Asus ZenFone 8(Android12) and AQUOS sense6(Android11)
Not happening on Android 10 Xperia 1 II
It was working fine。

However, it has not yet been possible to determine whether the cause is the OS or a hardware-specific problem.
For the time being, I caught the crash log of my Xperia 5 III with Logcat, so I will share it

TestDevice: `Xperia 5 III（XQ-BQ42)` 
Android Version `Android 12` 
Build Unity info ` 2021.3.0f1 (6eacc8284459)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'`

[logCatCrashLog.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9186557/logCatCrashLog.txt)

I have several verification terminals, so if there is any other verification I want you to do, please say anything.
I'm Japanese, so it would be helpful if you let me use Japanese, but can I use Japanese?

**Comment by KeigoTakamura** [comment]
supplement
Android 12 did not crash on Xiaomi 11T
  The biggest difference is that the SoC is not Snapdragon because it uses Mediatek Dimensity 1200-Ultra.
I don't have an 11T Pro verifier that uses the same custom Android ROM and uses Snapdragon 888 for the SoC, so I can't say that the cause is the SoC, but it may be involved in viewing the crash log. I think it's expensive

**Comment by karasusan** [comment]
> I'm Japanese, so it would be helpful if you let me use Japanese, but can I use Japanese?

日本語でも構いません。

**Comment by karasusan** [comment]
@KeigoTakamura 
Thank you for sharing the detail.
We can see in the crash log that **vkCmdCopyImage** is the cause of crash.
We need to check the SoC to investigate the crash.

```
07-26 13:29:03.234 32637 32714 E CRASH   :       #00 pc 00000000000b1a8c  /vendor/lib64/hw/vulkan.adreno.so (BuildId: d4402d93e07dc220f109ac933bb11f6f)
07-26 13:29:03.234 32637 32714 E CRASH   :       #01 pc 000000000009efb8  /vendor/lib64/hw/vulkan.adreno.so (qglinternal::vkCmdCopyImage2KHR(VkCommandBuffer_T*, VkCopyImageInfo2KHR const*)+1392) (BuildId: d4402d93e07dc220f109ac933bb11f6f)
07-26 13:29:03.234 32637 32714 E CRASH   :       #02 pc 000000000009ea10  /vendor/lib64/hw/vulkan.adreno.so (qglinternal::vkCmdCopyImage(VkCommandBuffer_T*, VkImage_T*, VkImageLayout, VkImage_T*, VkImageLayout, unsigned int, VkImageCopy const*)+224) (BuildId: d4402d93e07dc220f109ac933bb11f6f)
07-26 13:29:03.234 32637 32714 E CRASH   :       #03 pc 000000000014b350  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libwebrtc.so (unity::webrtc::VulkanUtility::CopyImage(VkCommandBuffer_T*, VkImage_T*, VkImage_T*, unsigned int, unsigned int)+96)
07-26 13:29:03.234 32637 32714 E CRASH   :       #04 pc 0000000000149ed8  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libwebrtc.so (unity::webrtc::VulkanGraphicsDevice::CopyResourceFromNativeV(unity::webrtc::ITexture2D*, void*)+324)
07-26 13:29:03.234 32637 32714 E CRASH   :       #05 pc 000000000014cdf8  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libwebrtc.so (unity::webrtc::GpuMemoryBufferFromUnity::GpuMemoryBufferFromUnity(unity::webrtc::IGraphicsDevice*, void*, unity::webrtc::Size const&, UnityRenderingExtTextureFormat)+208)
07-26 13:29:03.234 32637 32714 E CRASH   :       #06 pc 0000000000146e50  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libwebrtc.so (unity::webrtc::GpuMemoryBufferPool::GetOrCreateFrameResources(void*, unity::webrtc::Size const&, UnityRenderingExtTextureFormat)+180)
07-26 13:29:03.234 32637 32714 E CRASH   :       #07 pc 0000000000146b8c  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libwebrtc.so (unity::webrtc::GpuMemoryBufferPool::CreateFrame(void*, unity::webrtc::Size const&, UnityRenderingExtTextureFormat, webrtc::Timestamp)+44)
07-26 13:29:03.234 32637 32714 E CRASH   :       #08 pc 000000000012f3f4  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libwebrtc.so (OnRenderEvent(int, void*)+296)
07-26 13:29:03.234 32637 32714 E CRASH   :       #09 pc 0000000000549510  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libunity.so (BuildId: de37ca401b4fe2d8c2d17f9a2ef2b9ebc37eda64)
07-26 13:29:03.234 32637 32714 E CRASH   :       #10 pc 00000000005d93d0  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libunity.so (BuildId: de37ca401b4fe2d8c2d17f9a2ef2b9ebc37eda64)
07-26 13:29:03.234 32637 32714 E CRASH   :       #11 pc 00000000005d9ba8  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libunity.so (BuildId: de37ca401b4fe2d8c2d17f9a2ef2b9ebc37eda64)
07-26 13:29:03.234 32637 32714 E CRASH   :       #12 pc 00000000005d1438  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libunity.so (BuildId: de37ca401b4fe2d8c2d17f9a2ef2b9ebc37eda64)
07-26 13:29:03.235 32637 32714 E CRASH   :       #13 pc 000000000021b114  /data/app/~~BQQ8LGsEXchn8A65zirK3Q==/com.DefaultCompany.WebRTC_Sample_Unity-iLRN00wRclMxhKT9SVZPAQ==/lib/arm64/libunity.so (BuildId: de37ca401b4fe2d8c2d17f9a2ef2b9ebc37eda64)
07-26 13:29:03.235 32637 32714 E CRASH   :       #14 pc 00000000000b6a24  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 4a4029332735685df100db7f03e8fb32)
07-26 13:29:03.235 32637 32714 E CRASH   :       #15 pc 00000000000532bc  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 4a4029332735685df100db7f03e8fb32)
```

**Comment by KeigoTakamura** [comment]
@karasusan 

ありがとうございます。
Snapdragon ProfilerとかRenderDocでデバッグするあたりが妥当な手法になる感じでしょうか？
あまりMobileSoCのネイティブデバッグが詳しくないのでもしいい感じの手法とかご存知であればお教えください。

ちなみにCrashした端末の各SoCは
Xperia5ⅢがSnapdragon 888
Zenphone8もSnapdragon 888
AQUOS Sense6 がSnapdragon 690 5G

Crashしなかった端末は
 Xiaomi 11TがMediatek Dimensity 1200-Ultra
Xperia1 Ⅱが　Snapdagon865でした（ただしこれはAndroid10)

**Comment by KeigoTakamura** [comment]
おそらくAndroid11以降のバージョンでAdreno系GPUを搭載していると発生するのではないかとみています。

**Comment by KeigoTakamura** [comment]
すいません、私の検証ではOpenGLES3.0の強制が有効になっていませんでした。
Auto graphicsAPIにチェックが入っているとOSによって自動的にValkanが選ばれてしまいクラッシュするのが原因のように見えます。

![image](https://user-images.githubusercontent.com/40245723/181174103-e3b1b092-d143-443c-bf79-b9fd0e89f74d.png)

**Comment by karasusan** [comment]
@KeigoTakamura
手元の環境で再現できました。調査します。

**Comment by karasusan** [comment]
以下のコミットから発生していることが分かりました。回避策を検討します。
https://github.com/Unity-Technologies/com.unity.webrtc/commit/a46889e28538271dd2bb8cbebd6b9956031f4d0e

**Comment by KeigoTakamura** [comment]
@karasusan 
ありがとうございます、原因コミットが特定できてよかったです。
またなんかあったらデバッグとか諸々お手伝いするのでよろしくお願いいたします。

**Comment by karasusan** [comment]
memo: WRS-379

**Comment by karasusan** [comment]
I am checking this fix all platforms.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/786

**Comment by karasusan** [comment]
This issue is fixed and released the new version 2.4.0-exp.9.
I would like to close the cicket if you check.

**Comment by KeigoTakamura** [comment]
exp9 worked fine on my Android smartphone for verification, thank you for your support

It's LGTM.  @karasusan

**Comment by karasusan** [comment]
@zentwisty
Have you solved?
