### ISSUE TITLE
[BUG]: Unable to Transition to ICE Connection status "Connected" with Python answer role

### ISSUE THREAD

**Issue by ericjang** [Unity-Technologies/com.unity.webrtc#780]
### Package version

2.4.0-exp.7

### Environment

```markdown
* OS: Ubuntu20.04
* Unity version: 2021.1.20f1
* com.unity.webrtc: 2.4.0-exp.7
```

### Steps To Reproduce

1. Start turn server (simple_server.py), e.g. `./simple_server.py --disable-ssl --port 8910`
3. Start unity webrtc example that streams video
4. Start client , `python3 session-client.py`

### Current Behavior

On Unity Side (role=offerer), I expect to see the ICEConnectionState change to "Connected" after the ICECandidate is received from session-client.py (role=answerer)

![webrtc-broken](https://user-images.githubusercontent.com/433201/180619160-badc8c3b-dcfa-4722-9a3a-e627d617d9c2.png)

However, it just hangs and never transitions there. 

Here is an example ICE Candidate message sent by my python client:

```
candidate:a6482eeb8e28babb04eecd52c42821a2 1 udp 2130706431 192.168.1.3 52592 typ host generation 0 ufrag ea1U network-cost 999
```

### Expected Behavior

Normally, Unity switches ICEConnectionState to Connected

![unity_stream_working](https://user-images.githubusercontent.com/433201/180619189-4f86c297-318e-4b5f-b82a-252f49bcd28d.png)

This works fine when the answerer is a web browser, and seems to authenticate correctly. Here is an example ICE message sent when things are working:
```
candidate:704553097 1 udp 2113937151 e901ddc6-7ea3-4e87-9873-7888be110432.local 42455 typ host generation 0 ufrag AM4E network-cost 999
```

### Anything else?

I've attached webrtc.js, which is the session-client equivalent but implemented in javascript. this works fine and correctly connects to the Unity peer. This doesn't provide enough code to run the issue, but I can try to provide a more self-contained runnable example if needed.

session-client.py is what I believe is the equivalent code, but in python. As shown from screenshots of logs above, it correctly connects to the peer and sends an ICECandidate , but the Unity app never transitions to the state Connected. I'm wondering what else I can do to debug this?

[session-client.py.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9174448/session-client.py.txt)
[index.html.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9174449/index.html.txt)
[webrtc.js.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9174450/webrtc.js.txt)

**Comment by gtk2k** [comment]
Please write which WebRTC library the Python side is using.

**Comment by ericjang** [comment]
python is using [aiortc](https://github.com/aiortc/aiortc/)
[simple_server.py.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9174485/simple_server.py.txt)

both simple_server.py and session-client.py are based on https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/1.18/webrtc/signalling

which involve a slightly weird HELLO / SESSION <PEER> protocol that occurs before the actual exchange of SDP / ICE information, but I've confirmed that the issue is with getting Unity peer to go from "Checking" -> "Connected/Completed". So my main question is, is there anything malformed about my ICECandidate message that would cause this to happen? How can I debug this further?

**Comment by gtk2k** [comment]
https://github.com/gtk2k/Unity_aiortc_sample
I wrote a sample to connect with aiortc before, so please refer to this.

**Comment by ericjang** [comment]
Thanks very much @gtk2k , I was able to get your example running so I should be able to figure it out from here. I'll re-open the issue if I run into further challenges. thanks for your clean and well-written code!

**Comment by ericjang** [comment]
just FYI, when muxing the VideoStreamTrack via the `--record-to` flag, it's important to normalize the pts timestamps, e.g. using the `RemoteVideoStreamTrack` wrapper class suggested in https://github.com/aiortc/aiortc/issues/580
