### ISSUE TITLE
[BUG]: Package supported Unity version is 2019.4 - Native code references IUnityProfiler.h 

### ISSUE THREAD

**Issue by matt-knowles-level-ex** [Unity-Technologies/com.unity.webrtc#785]
### Package version

2.4.0-exp.8

### Environment

```markdown
* OS:Windows 10
* Unity version: 2019.4
```

### Steps To Reproduce

1. Attempt to open project referencing com.unity.webrtc 2.4.0-exp.8 on a Unity 2019.4.x project
2. It will fail to open.
3. Look at the Editor logs for the call stack causing the crash, you may have had to build the plugin with symbols to see it.

### Current Behavior

After the Editor fails to open you will see in the Editor logs a callstack pointing to the issue. The native code is including "IUnityProfiler.h" to hook into the native plugin api ([LowLevelNativePluginProfiler](https://docs.unity3d.com/Manual/LowLevelNativePluginProfiler.html))

In 2019.4 there is no IUnityProfiler.h instead the code was using IUnityProfilerCallbacks.h

========== OUTPUTTING STACK TRACE ==================

0x00007FFF12959C01 (webrtc) [\Plugin~\WebRTCPlugin\ProfilerMarkerFactory.cpp:28] unity::webrtc::ProfilerMarkerFactory::CreateMarker 
0x00007FFF12942A7D (webrtc) [Plugin~\WebRTCPlugin\UnityRenderEvent.cpp:224] PluginLoad 
0x00007FF7C1AEC204 (Unity) RegisterPlugin
0x00007FF7C1AEA215 (Unity) FindAndLoadUnityPlugin
0x00007FF7BFEA4588 (Unity) PluginManager::RefreshPlugins
0x00007FF7BFE5EF9E (Unity) Application::InitializeProject
0x00007FF7C07EA774 (Unity) WinMain
0x00007FF7C3809A32 (Unity) __scrt_common_main_seh
0x00007FFFC9D17034 (KERNEL32) BaseThreadInitThunk
0x00007FFFCB002651 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

### Expected Behavior

My expectation is the package Unity version dependency needs to be updated to at least 2020.1 as that is the earliest version supporting IUnityProfiler.h [Low Level Native Plugin Profiler 2020.1](https://docs.unity3d.com/2020.1/Documentation/Manual/LowLevelNativePluginProfiler.html)

Potentially I am wrong but looking at the headers in "_\Hub\Editor\2019.4.1f1\Editor\Data\PluginAPI_"  I don't see IUnityProfiler.h

The work around was modifying  "ProfilerMarkerFactory::CreateMarker".

I instead of calling CreateMarker:

 `int result = profiler_->CreateMarker(&desc, name, category, flags, eventDataCount);`

I create a UnityProfilerMarkerDesc by hand. I know this may break the profiler but at this point we are not using the profiler.

**Comment by karasusan** [comment]
@matt-knowles-level-ex 
Thank you for sharing the issue!
I will check it but 2019.4LTS will be discontinued to support this year. I cannot promise how long we will support the LTS version.

**Comment by karasusan** [comment]
@matt-knowles-level-ex 
Hi, I am checking this issue in my environment, but I cannot reproduced it.
No problem to open and play the Unity project on Unity Editor 2019.4LTS.

Have you used the package which downloaded from Package Manager?

**Comment by karasusan** [comment]
I would like to close the ticket if we haven't get other information about this issue.
