### ISSUE TITLE
Magic Leap compatibility?

### ISSUE THREAD

**Issue by jasonodomtaqtile** [Unity-Technologies/com.unity.webrtc#79]
We are looking for a webRTC solution for Unity and Magic Leap. Is this it?

**Comment by sindharta** [comment]
It might be. It depends on the requirements.
We encourage you to try it and give your feedback.

**Comment by imbible** [comment]
Tried but not working on Magic Leap. Actually I only need the data channel feature so will it make sense to you not to forcibly check the codec support in the code? Data channel should be codec agnostic because it does not rely on it.

**Comment by jasonodomtaqtile** [comment]
I looked into it the other day and did not see how it could be working as there is no lumin os, or even android plugin options. Just X86 X64.

**Comment by sindharta** [comment]
@jasonodomtaqtile I see.

We are considering to support Android, but it's too early to say at this moment since we are focusing on multi camera and DX12 support.

**Comment by karasusan** [comment]
Magicleap has supported WebRTC natively.
https://www.magicleap.com/news/product-updates/lumin-os-0-98-20-and-lumin-sdk-0-25
