### ISSUE TITLE
[BUG?]: OnVideoReceived not always called when connecting via webserver

### ISSUE THREAD

**Issue by mchrbn** [Unity-Technologies/com.unity.webrtc#794]
### Package version

2.4.0-exp.9

### Environment

```markdown
* OS: Windows 10
* Unity version: 2021.3.6
```

### Steps To Reproduce

Sorry not sure if it is a bug and if it is, if it is the right description for it.

- An Unreal Engine app is streaming its content via WebRTC and I'm trying to get its stream in Unity.
- The information exchange between both happens via a webserver (the one generated by Unreal/PixelStreaming)
- The exchange seems to work well between the two. The server is receiving the offer, sending an answer and both send their Ice candidates
- No errors logged in both Unity and webserver but OnVideoReceived is almost never called. Therefore I'm not receiving any textures in the Unity side. **However, it did work (very rarely) at random times.**

Below is a log sequence from the Unity side. Where WS -> is what is sent to the webserver and WS <- what is received.

As it still works sometimes, what could be the issue? Is it related to a bad pairing of Ice candidate? Or is the sequence of sending/receiving wrong (i.e. this issue #347  )

> [8/3/2022 4:42:23 PM]Successfully connected to ws://127.0.0.1:80
> [8/3/2022 4:42:23 PM]WS <- {"type":"config","peerConnectionOptions":{}}
> [8/3/2022 4:42:23 PM]WS <- {"type":"playerCount","count":1}
> [8/3/2022 4:42:24 PM]WS -> {"type":"offer","sdp":"v=0\r\no=- 2783483260383796420 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: ...too long, see attached file for full log
> [8/3/2022 4:42:24 PM]WS -> CANDIDATE: [2409:8900:2650:fe0b:a472:3141:564f:bca]:54377
> [8/3/2022 4:42:24 PM]WS -> CANDIDATE: [2409:8900:2650:fe0b:e99d:5cfe:828a:2291]:54378
> [8/3/2022 4:42:24 PM]WS -> CANDIDATE: 192.168.90.120:54379
> [8/3/2022 4:42:24 PM]WS -> CANDIDATE: [2409:8900:2650:fe0b:a472:3141:564f:bca]:52377
> [8/3/2022 4:42:24 PM]WS -> CANDIDATE: [2409:8900:2650:fe0b:e99d:5cfe:828a:2291]:52378
> [8/3/2022 4:42:24 PM]WS -> CANDIDATE: 192.168.90.120:52379
> [8/3/2022 4:42:24 PM]WS <- {"type":"answer","sdp":"v=0\r\no=- 3568475973502208657 2 IN IP4 127.0.0.1 ...too long, see attached file for full log
> [8/3/2022 4:42:24 PM]CONNECTION STATE CHANGE: Connecting
> [8/3/2022 4:42:24 PM]Received Texture! <- However, video..OnVideoReceived is never called
> [8/3/2022 4:42:24 PM]CONNECTION STATE CHANGE: Connected
> [8/3/2022 4:42:24 PM]WS <- {"type":"iceCandidate","candidate":{"sdpMid":"0","sdpMLineIndex":0,"candidate":"candidate:2378221925 1 udp 2122197247 2409:8900:2650:fe0b:e99d:5cfe:828a:2291 54383 typ host generation 0 ufrag 2cgX network-id 3 network-cost 10"}}
> [8/3/2022 4:42:24 PM]WS <- {"type":"iceCandidate","candidate":{"sdpMid":"0","sdpMLineIndex":0,"candidate":"candidate:2322053569 1 udp 2122129151 192.168.90.120 54384 typ host generation 0 ufrag 2cgX network-id 1 network-cost 10"}}

### Current Behavior

- OnTrack is called and I receive a Track of type Video
- OnVideoReceived isn't called most of times (it works well randomly)

### Expected Behavior

- OnVideoReceived is called so I can set my received texture from WebRTC to my local texture.

### Anything else?

The full code, if useful.

```
using UnityEngine;
using Unity.WebRTC;
using UnityWebSocket;
using Newtonsoft.Json;
using UnityEngine.UI;
using System.Collections;
using System.Linq;

public struct WSSdpAnswer{
    public string type;
    public string sdp;
}

public struct WSIceCandidate{
    public string type;
    public RTCIceCandidateInit candidate;
}

public class WebRTCReceiver : MonoBehaviour
{
    [SerializeField] RawImage receivedImg;
    [SerializeField] string wsAddress;

    WebSocket socket;

    RTCPeerConnection peerConnection;
    MediaStream receiveVideoStream;
    //RawImage test;

    void Awake(){
        WebRTC.Initialize();
    }

    void Start(){
        //Setup and connect to websocket
        socket = new WebSocket(wsAddress);
        socket.OnOpen += SocketOnOpen;
        socket.OnMessage += SocketOnMessage;

        socket.ConnectAsync();
    }

    void OnApplicationQuit(){
        if(socket != null && socket.ReadyState != WebSocketState.Closed)
            socket.CloseAsync();
        
        WebRTC.Dispose();
    }


    void SocketOnOpen(object _sender, OpenEventArgs _e){
        Debug.Log("Successfully connected to " + wsAddress);
        
        //Start RTC connection once we are succesfully connected to the webserver
        peerConnection = new RTCPeerConnection();
        peerConnection.AddTransceiver(TrackKind.Video);
        peerConnection.OnConnectionStateChange = state => {
            Debug.Log($"CONNECTION STATE CHANGE: {state}");
        };     
        peerConnection.OnIceCandidate = candidate => {
            Debug.Log($"WS -> CANDIDATE: {candidate.Address}");

            //Send local candidates to webserver
            string jsonCandidate = JsonConvert.SerializeObject(candidate);
            string json = "{\"type\":\"iceCandidate\",\"candidate\":" + jsonCandidate + "}";
            socket.SendAsync(json);
        };
        peerConnection.OnTrack = e => {
            if(e.Track is VideoStreamTrack video){
                Debug.Log("Received Texture!");
                video.OnVideoReceived += tex =>
                {
                    receivedImg.texture = tex;
                };
                receiveVideoStream = e.Streams.First();
                receiveVideoStream.OnRemoveTrack = ev =>
                {
                    receivedImg.texture = null;
                    ev.Track.Dispose();
                };
            }
        };
        
        StartCoroutine(CreateOffer());
        StartCoroutine(WebRTC.Update());
    }

    IEnumerator CreateOffer(){
        var offer = peerConnection.CreateOffer();
        yield return offer;

        var oDesc = offer.Desc;
        yield return peerConnection.SetLocalDescription(ref oDesc);

        //Convert object to json string
        string json = JsonConvert.SerializeObject(oDesc);

        //set the type as 'offer' as it is what is needed by the WS server
        json = json.Replace("\"type\":0", "\"type\":\"offer\"");
        
        //extmap-allowed-mixed not supported in current WebRTC webserver generated by UE. Have to remove it to avoid bug.
        //https://forums.unrealengine.com/t/game-crash-and-pop-up-below-message-when-start-pixel-streaming-and-connect-it/479860/3
        json = json.Replace("a=extmap-allow-mixed\\r\\n", "");

        //Send offer to webserver
        Debug.Log("WS -> " + json);

        socket.SendAsync(json);
    }

    void SocketOnMessage(object _sender, MessageEventArgs _e){
        Debug.Log("WS <- " + _e.Data.ToString());

        //If receive an answer from webserver, set remote description
        if(_e.Data.Contains("\"type\":\"answer\"")){
            WSSdpAnswer a = JsonConvert.DeserializeObject<WSSdpAnswer>(_e.Data);
            RTCSessionDescription sDesc = new RTCSessionDescription();
            sDesc.type = RTCSdpType.Answer;
            sDesc.sdp = a.sdp;

            peerConnection.SetRemoteDescription(ref sDesc);
        }
        //If receive a candidate from webserver, add it to peerConnection
        else if(_e.Data.Contains("\"type\":\"iceCandidate\"")){
            WSIceCandidate sCandidate = JsonConvert.DeserializeObject<WSIceCandidate>(_e.Data);

            RTCIceCandidate c = new RTCIceCandidate(sCandidate.candidate);
            peerConnection.AddIceCandidate(c);
        }
    }
}

```

**Comment by gtk2k** [comment]
Please send the contents of the sdp of the answer.

**Comment by mchrbn** [comment]
Here you go, thanks:

`{"type":"answer","sdp":"v=0\r\no=- 3568475973502208657 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS stream_id\r\nm=video 9 UDP/TLS/RTP/SAVPF 123 111 119 118\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:2cgX\r\na=ice-pwd:o2WCZRmEbTOBW9XsxP7699px\r\na=ice-options:trickle\r\na=fingerprint:sha-256 46:63:5F:89:EB:52:2D:5F:7C:C2:41:38:E4:40:68:3D:89:79:F7:48:74:D5:74:D1:2D:A7:51:6A:98:35:04:C2\r\na=setup:active\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 urn:3gpp:video-orientation\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:stream_id video_label\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:123 H264/90000\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 transport-cc\r\na=rtcp-fb:123 ccm fir\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034\r\na=rtpmap:111 rtx/90000\r\na=fmtp:111 apt=123\r\na=rtpmap:119 red/90000\r\na=rtpmap:118 ulpfec/90000\r\na=ssrc-group:FID 1367719576 3643134868\r\na=ssrc:1367719576 cname:11DtGHStij5zLcOp\r\na=ssrc:3643134868 cname:11DtGHStij5zLcOp\r\n"}`

**Comment by gtk2k** [comment]
The contents of sdp seem to be fine.
It seems that the offer is sent from Unity, but if it is possible to send the offer from Unreal, I would like you to try it.

**Comment by mchrbn** [comment]
I tried to send the offer with JS from a browser, instead of Unity, and it works fine. I can receive the stream from Unreal in my browser.

Could it be because of this?

> [8/3/2022 4:42:24 PM]CONNECTION STATE CHANGE: Connecting
> [8/3/2022 4:42:24 PM]Received Texture! <- However, video..OnVideoReceived is never called
> [8/3/2022 4:42:24 PM]CONNECTION STATE CHANGE: Connected

_OnTrack_ is called while the RTP Connection State is connecting but not yet connected.

**Comment by gtk2k** [comment]
Is the GPU installed in the Unity PC NVIDIA?

**Comment by mchrbn** [comment]
Yes the Unity PC has an NVIDIA

**Comment by gtk2k** [comment]
`WebRTC. Initialize();`
after
`StartCoroutine(WebRTC.Update());`
try adding

**Comment by gtk2k** [comment]
Hmmm, maybe Profile Level 42e01f is not supported on com.unity.webrtc side. .

**Comment by gtk2k** [comment]
Since I have very little experience with Unreal Engine, I was able to receive video streaming after researching it on the Internet and implementing it.

https://github.com/gtk2k/Unity_PixelStreamingReceiverTest

**Comment by mchrbn** [comment]
Thanks a lot for the help and for trying to implement it!

I'm not understanding something - it seems that in your code you are receiving an offer from the server and then send back an answer. However the webserver generated by UE works in the opposite way, it waits for an offer and then send back an answer. Did you modify the server to behave like this? Which version of UE did you use?

**Comment by gtk2k** [comment]
It's UE5.

**Comment by mchrbn** [comment]
Oh ok, then they updated their server - I was using UE 4.26 and it was working the other way round :).
I will test it again with 5.0 and come back to you. Thanks again.

**Comment by mchrbn** [comment]
I upgraded my projects to UE 5.0 and it works perfectly with your script.
Thanks again!
