### ISSUE TITLE
[BUG]: A few seconds latency of video on subscriber side when I publish video and audio together

### ISSUE THREAD

**Issue by kotrs** [Unity-Technologies/com.unity.webrtc#800]
### Package version

2.4.0-exp.10

### Environment

```markdown
* OS:iOS
* Unity version:Unity 2021.3
```

### Steps To Reproduce

1. Init WebRTC
2. Publish Video and Audio
3. Receive Video and Audio

### Current Behavior

A few seconds latency of video on subscriber side when I publish video and audio together. The latency is small after connection, but during the connection it is increasing. Publishing video without audio is OK.

### Expected Behavior

Latency of video on subscriber side up to 500ms

**Comment by kotrs** [comment]
Publisher - MacOS Unity Editor or iOS device
Subscriber - iOS device

The issue is on publisher side probably. Because the latency contineus when I disable audio subscribe on subscriber.

**Comment by kotrs** [comment]
I need to know if it is a feature of this package or not. Because my implementation is more complicated. The communication is established throw OpenVidu server. But sample OpenVidu client web app runs with audio without latency.
Then I use third party package for AEC. But the latency starts increasing when I begin sending data with SetData method in AudioStreamTrack. So it seems that problem is in WebRTC package.

**Comment by karasusan** [comment]
Can you check the bitrate for audio?

**Comment by kotrs** [comment]
I tried to set bitrate of audio sender to 10kb. But no change.

**Comment by karasusan** [comment]
@kotrs
Is it replicate the issue when testing it without OpenVidu?

**Comment by kotrs** [comment]
The delay was caused by a/v synchronisation on server side. It is not problem of this package.
Thank you
