### ISSUE TITLE
[REQUEST]: Update WebRTC source to address vulnerabilities on Android.

### ISSUE THREAD

**Issue by Lintzmaia** [Unity-Technologies/com.unity.webrtc#830]
### Package version

2.4.0-exp.10

### Environment

```markdown
OS: Windows 10
Unity version: Unity 2019.4
```

### Steps To Reproduce

1. Build application with WebRTC version 2.4.0-exp10.
2. Publish to Google Play.

### Current Behavior

Google has given us a error saying that WebRTC has vulnerabilities when pushing a new version to Google Play.
![image](https://user-images.githubusercontent.com/18687159/196978626-35c607bd-7341-4c0a-9dec-95fdb70f9905.png)

They provide us a link on how to fix this: 
https://support.google.com/faqs/answer/12577537
I believe the relevant section on this page is this:
`It is strongly recommended that apps update to the current source, though updating to M102 or later will remediate the security issue.`

I believe the vulnerability will only be exposed once the connection is made between 2 peers, so if I'm worng about this, please correct me since we chose to keep this version available on Google Play for now.

Is it possible for the next version to come with the latest version of WebRTC? Or is there something I can do to remediate this on my end?

**Comment by karasusan** [comment]
@Lintzmaia
Yes, we have a plan to update the webrtc version for the next release. The release would be in January.

**Comment by Lintzmaia** [comment]
Ok. Thank you!

**Comment by karasusan** [comment]
memo: WRS-97

**Comment by karasusan** [comment]
Fixed.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/843

**Comment by karasusan** [comment]
@Lintzmaia 
This issue is fixed. Please try the latest version 3.0.0-pre.2.
