### ISSUE TITLE
[BUG]: Editor & App Crashes/Freezes when enable simulcast with VP8 codec in Mac Machine

### ISSUE THREAD

**Issue by soorin1990** [Unity-Technologies/com.unity.webrtc#890]
### Package version

3.0.0-pre.4

### Environment

```markdown
* OS:Ventura 13.2.1 (22D68)
* Unity version: 2021.3.14f1
* Chip: Apple M1 Max
* Memory: 32 GB
```

### Steps To Reproduce

I am trying to enable simulcast using VP8 Codec type by modifying the existing MediaStreamSample.cs with the below code

	public bool isSimulcast = true;
        private RTCRtpTransceiverInit SetSimulcast(ref RTCRtpTransceiverInit init)
        {
            init.direction = RTCRtpTransceiverDirection.SendOnly;
            List<RTCRtpEncodingParameters> encodingList = new List<RTCRtpEncodingParameters>();
            RTCRtpEncodingParameters parameterH = new RTCRtpEncodingParameters();
            parameterH.maxBitrate = 4000*1000;
            parameterH.scaleResolutionDownBy = 1;
            parameterH.maxFramerate = 60;
            parameterH.active = true;
            parameterH.rid = "h";

            RTCRtpEncodingParameters parameterM = new RTCRtpEncodingParameters();
            parameterM.maxBitrate = 900*1000;
            parameterM.scaleResolutionDownBy = 1;
            parameterM.active = true;
            parameterM.maxFramerate = 60;
            parameterM.rid = "m";

            RTCRtpEncodingParameters parameterL = new RTCRtpEncodingParameters();
            parameterL.maxBitrate = 400*1000;
            parameterL.scaleResolutionDownBy = 1;
            parameterL.active = true;
            parameterL.maxFramerate = 60;
            parameterL.rid = "l";
            encodingList.Add(parameterH);
            encodingList.Add(parameterM);
            encodingList.Add(parameterL);
            init.sendEncodings = encodingList.ToArray();
            Debug.Log("simulcast set........");
            return init;
        }
        private void AddTracks()
        {
            if (isSimulcast)
            {
                RTCRtpTransceiverInit init = new RTCRtpTransceiverInit();
                SetSimulcast(ref init);
                RTCRtpTransceiver trans = _pc1.AddTransceiver(track, init);
                if (trans != null)
                    pc1Senders.Add(trans.Sender);
                else
                    Debug.LogError("Transceiver is null");
            }
            else
                pc1Senders.Add(_pc1.AddTrack(track));

            ***********************************
        }

	When i try to run this in editor by setting the Codec Type to VP8, it works fine in Windows machine but Editor Freezes in Mac machines.

	We are not sure if this is working with Intel Mac as we didnt get a chance to test it with Intel Mac Machine.

### Current Behavior

Both Editor & App Crashes on running with VP8 with simulcast enabled

### Expected Behavior

App should not crash and stream simulcast layers

Log:
* Assertion at threads.c:6918, condition `this_thread_controls == thread_given_control' not met
Obtained 6 stack frames.
Thread 0x31171c000 may have been prematurely finalizedasync && (unwind_options & MONO_UNWIND_LOOKUP_ACTUAL_METHOD) not legalAcceleratorClientConnectionCallback - disconnected - :0
#0  0x000001818bc97d in void absl::internal_any_invocable::RemoteInvoker<false, void, webrtc::(anonymous namespace)::RepeatingTask&&>(absl::internal_any_invocable::TypeErasedState*)
Thread 0x31171c000 may have been prematurely finalized#1  0x00000181de52c3 in std::__1::__function::__func<webrtc::(anonymous namespace)::TaskQueueStdlib::InitializeThread(webrtc::(anonymous namespace)::TaskQueueStdlib*, absl::string_view, rtc::ThreadPriority)::$_1, std::__1::allocator<webrtc::(anonymous namespace)::TaskQueueStdlib::InitializeThread(webrtc::(anonymous namespace)::TaskQueueStdlib*, absl::string_view, rtc::ThreadPriority)::$_1>, void ()>::operator()()
Thread 0x31171c000 may have been prematurely finalized#2  0x000001818b2447 in std::__1::__function::__func<rtc::PlatformThread::SpawnThread(std::__1::function<void ()>, absl::string_view, rtc::ThreadAttributes, bool)::$_1, std::__1::allocator<rtc::PlatformThread::SpawnThread(std::__1::function<void ()>, absl::string_view, rtc::ThreadAttributes, bool)::$_1>, void ()>::operator()()
Thread 0x31171c000 may have been prematurely finalized#3  0x000001818b20c8 in rtc::(anonymous namespace)::RunPlatformThread(void*)
Thread 0x31171c000 may have been prematurely finalized#4  0x007ff8030a9259 in _pthread_start
Thread 0x31171c000 may have been prematurely finalized#5  0x007ff8030a4c7b in thread_start
Obtained 6 stack frames.
Thread 0x3125f6000 may have been prematurely finalized#0  0x000001818bc97d in void absl::internal_any_invocable::RemoteInvoker<false, void, webrtc::(anonymous namespace)::RepeatingTask&&>(absl::internal_any_invocable::TypeErasedState*)
Thread 0x3125f6000 may have been prematurely finalized#1  0x00000181de52c3 in std::__1::__function::__func<webrtc::(anonymous namespace)::TaskQueueStdlib::InitializeThread(webrtc::(anonymous namespace)::TaskQueueStdlib*, absl::string_view, rtc::ThreadPriority)::$_1, std::__1::allocator<webrtc::(anonymous namespace)::TaskQueueStdlib::InitializeThread(webrtc::(anonymous namespace)::TaskQueueStdlib*, absl::string_view, rtc::ThreadPriority)::$_1>, void ()>::operator()()
Thread 0x3125f6000 may have been prematurely finalized#2  0x000001818b2447 in std::__1::__function::__func<rtc::PlatformThread::SpawnThread(std::__1::function<void ()>, absl::string_view, rtc::ThreadAttributes, bool)::$_1, std::__1::allocator<rtc::PlatformThread::SpawnThread(std::__1::function<void ()>, absl::string_view, rtc::ThreadAttributes, bool)::$_1>, void ()>::operator()()
Thread 0x3125f6000 may have been prematurely finalized#3  0x000001818b20c8 in rtc::(anonymous namespace)::RunPlatformThread(void*)
Thread 0x3125f6000 may have been prematurely finalized#4  0x007ff8030a9259 in _pthread_start
Thread 0x3125f6000 may have been prematurely finalized#5  0x007ff8030a4c7b in thread_start
Obtained 5 stack frames.
Thread 0x31215c000 may have been prematurely finalized#0  0x00000104dade03 in MetalSurfaceCallback(__CVDisplayLink*, CVTimeStamp const*, CVTimeStamp const*, unsigned long long, unsigned long long*, void*)
Thread 0x31215c000 may have been prematurely finalized#1  0x007ff80b8fe2b1 in CVDisplayLink::performIO(CVTimeStamp*)
Thread 0x31215c000 may have been prematurely finalized#2  0x007ff80b8fd10d in CVDisplayLink::runIOThread()
Thread 0x31215c000 may have been prematurely finalized#3  0x007ff8030a9259 in _pthread_start
Thread 0x31215c000 may have been prematurely finalized#4  0x007ff8030a4c7b in thread_start
Obtained 7 stack frames.
Thread 0x3126f9000 may have been prematurely finalized#0  0x0000018171f971 in webrtc::TimeDelta absl::internal_any_invocable::LocalInvoker<false, webrtc::TimeDelta, unity::webrtc::VideoFrameScheduler::StartRepeatingTask()::$_2&>(absl::internal_any_invocable::TypeErasedState*)
Thread 0x3126f9000 may have been prematurely finalized#1  0x000001818bc959 in void absl::internal_any_invocable::RemoteInvoker<false, void, webrtc::(anonymous namespace)::RepeatingTask&&>(absl::internal_any_invocable::TypeErasedState*)
Thread 0x3126f9000 may have been prematurely finalized#2  0x00000181de52c3 in std::__1::__function::__func<webrtc::(anonymous namespace)::TaskQueueStdlib::InitializeThread(webrtc::(anonymous namespace)::TaskQueueStdlib*, absl::string_view, rtc::ThreadPriority)::$_1, std::__1::allocator<webrtc::(anonymous namespace)::TaskQueueStdlib::InitializeThread(webrtc::(anonymous namespace)::TaskQueueStdlib*, absl::string_view, rtc::ThreadPriority)::$_1>, void ()>::operator()()
Thread 0x3126f9000 may have been prematurely finalized#3  0x000001818b2447 in std::__1::__function::__func<rtc::PlatformThread::SpawnThread(std::__1::function<void ()>, absl::string_view, rtc::ThreadAttributes, bool)::$_1, std::__1::allocator<rtc::PlatformThread::SpawnThread(std::__1::function<void ()>, absl::string_view, rtc::ThreadAttributes, bool)::$_1>, void ()>::operator()()
Thread 0x3126f9000 may have been prematurely finalized#4  0x000001818b20c8 in rtc::(anonymous namespace)::RunPlatformThread(void*)
Thread 0x3126f9000 may have been prematurely finalized#5  0x007ff8030a9259 in _pthread_start
Thread 0x3126f9000 may have been prematurely finalized#6  0x007ff8030a4c7b in thread_start
Launching bug reporter
Launching bug reporter
Launching bug reporter
Launching bug reporter

**Comment by karasusan** [comment]
Thank you, we need to check this line.
```
Assertion at threads.c:6918, condition `this_thread_controls == thread_given_control' not met
```

**Comment by kannan-xiao4** [comment]
memo: WRS-461

**Comment by Yousif-CS** [comment]
Any estimate on when we expect this issue to be fixed? This affects macOS, iOS and Android.

**Comment by karasusan** [comment]
@Yousif-CS
Does it work on Windows or Linux platform?

**Comment by soorin1990** [comment]
This is working in Windows, didn't get a chance to test it on Linus.

**Comment by karasusan** [comment]
@soorin1990
Thank you for the valuable information. In other words, it means this issue depends on platforms.

**Comment by karasusan** [comment]
@soorin1990 

#979 is merged.
