### ISSUE TITLE
[BUG]: Latency is very poor compared to Unreal, NvFBC

### ISSUE THREAD

**Issue by doctorpangloss** [Unity-Technologies/com.unity.webrtc#894]
### Package version

3.0.0-pre.4

### Environment

```markdown
* OS: Windows 2022, Linux
* Unity version: 2021.3.22f1
```

### Steps To Reproduce

1. Stream to an end user.
2. Observe an RTT of 0ms.
3. Observe input latency of 40-117ms.

### Current Behavior

Latency has become very high compared to other leading platforms.

### Expected Behavior

It would be nice if you were to pause Vulkan fixes to just work on latency.

### Anything else?

Latency isn't overrated. It should be your priority.

Vulkan stuff can wait. Linux will benefit from these fixes too.

**Comment by karasusan** [comment]
I haven't checked NvFBC, you mean Capture SDK, right?
https://developer.nvidia.com/capture-sdk
