### ISSUE TITLE
[BUG]: com.unity.webrtc@3.0.0-pre.5 Release is missing

### ISSUE THREAD

**Issue by ZenBre4ker** [Unity-Technologies/com.unity.webrtc#904]
### Package version

3.0.0-pre.5

### Environment

```markdown
OS: Windows 10
Unity version: Unity 2021.3
```

### Steps To Reproduce

1. Start the package manager
2. Try add git url `com.unity.webrtc@3.0.0-pre.5`

### Current Behavior

Not adding the newest release as it is not yet made.

### Expected Behavior

Should install com.unity.webrtc@3.0.0-pre.5

**Comment by karasusan** [comment]
We are making a latest version for releasing this week.
