### ISSUE TITLE
[BUG]: Android H264 Decoding does not work

### ISSUE THREAD

**Issue by BillWCJ** [Unity-Technologies/com.unity.webrtc#905]
### Package version

3.0.0-pre.4

### Environment

```markdown
* OS: Android 12
* Unity version: 21.3.17f
```

### Steps To Reproduce

1. Compile Webrtc with H264 enabled, then compile the Unity plugin for android
2. Compile Unity App and run on Android phone
3. Stream a video from Windows 11 PC using Chrome to Android phone with H264 codec
4. Verify that the WebRTC call is established and status is connected

### Current Behavior

Android app does not display H264 encoded video where as VP8 would work fine. The screen is just black

### Expected Behavior

The H264 encoded video is displaying fine similar to other codecs

### Anything else?

I also tried compiling the Windows version of the Unity WebRTC plugin with H264 enabled. 

Using the codec selection demo scene as part of the Unity WebRTC package, I was able to see the H264 codec showing up in the drop down list. Using the VP8, the demo works correctly. But when using H264 codec, the destination video does not show up.

**Comment by karasusan** [comment]
@BillWCJ 
Does your Android device support Android hardware codec?

**Comment by BillWCJ** [comment]
@karasusan Yes, I created a test client in Chrome and was able to stream correctly in Chrome

**Comment by karasusan** [comment]
@BillWCJ 
It is difficult to support you because you are using the library which you built yourself.

The library with H264 enabled flag should make available the software H264 codec.
Can you sure that which codec for receiver side you are using?

**Comment by BillWCJ** [comment]
@karasusan 
Could you send me any resources that you think might help me figure it out, or just point me in the general direction. I am happy to look into it myself and merge in the fix. I am sure many people would like to use the hardware H264 codec.

The video is streaming but just not displaying correctly in Unity (all black). I can confirm that from the WebRTC statistics.

**Comment by karasusan** [comment]
We are using the package sample for testing our package.
Can you check that the package sample works well with your library? 
https://docs.unity3d.com/Packages/com.unity.webrtc@3.0/manual/sample.html
