### ISSUE TITLE
[BUG]: CMAKELists.txt confusion

### ISSUE THREAD

**Issue by SetoKaiba** [Unity-Technologies/com.unity.webrtc#906]
### Package version

3.0.0-pre.5

### Environment

```markdown
* OS:Windows10
* Unity version:Unity 2021.3
```

### Steps To Reproduce

Load the project with preset x64-windows-msvc in CLion.

### Current Behavior

CLion get compiler information will report error.
https://youtrack.jetbrains.com/issue/CPP-33217/Reload-CMake-Project-confusion

### Expected Behavior

It should not report error.

### Anything else?

After a deep dive in the CMakeLists.txt, I found some confusion.
Why `/Yu` `/Yc` is added without filename here?

https://github.com/Unity-Technologies/com.unity.webrtc/blob/main/Plugin~/WebRTCPlugin/CMakeLists.txt#L125
https://github.com/Unity-Technologies/com.unity.webrtc/blob/main/Plugin~/WebRTCPlugin/CMakeLists.txt#L154

https://github.com/Unity-Technologies/com.unity.webrtc/blob/main/Plugin~/WebRTCPluginTest/CMakeLists.txt#L88
https://github.com/Unity-Technologies/com.unity.webrtc/blob/main/Plugin~/WebRTCPluginTest/CMakeLists.txt#L113

**Comment by SetoKaiba** [comment]
And also, Unity China accessing to global resource is cut off after it became joint venture. I have no access to Slack now. Is there any way to have an instant messaging with you?

**Comment by SetoKaiba** [comment]
Change the `/Yu /Yupch.h` to `/Yupch.h` and Change the `/Yc /Ycpch.h` to `/Yupch.h` solve the reload cmake project in CLion.

**Comment by SetoKaiba** [comment]
Change the `/Yu /Yupch.h` to `/Yupch.h` and Change the `/Yc /Ycpch.h` to `/Ycpch.h` solve the reload cmake project in CLion.

**Comment by SetoKaiba** [comment]
Change the `/Yu /Yupch.h` to `/Yupch.h` and Change the `/Yc /Ycpch.h` to `/Ycpch.h` solve the reload cmake project in CLion.

**Comment by karasusan** [comment]
This is a related issue.
#892

**Comment by kannan-xiao4** [comment]
memo: WRS-464

**Comment by SetoKaiba** [comment]
The #892 should fix the problem.
