### ISSUE TITLE
Android suppport?

### ISSUE THREAD

**Issue by BoyBouw** [Unity-Technologies/com.unity.webrtc#91]
Does this asset support Android? The asset description implies so ("The WebRTC Package provides browsers and mobile applications with Real-Time Communications (RTC) capabilities"). However, upon trying to build any demo scene, or our own implementation, that uses the WebRTC namespace we get the following error:

`The type or namespace name WebRTC does not exist in the namespace Unity  `

This works fine in the editor, or when building to Windows. Any suggestions, or simply is this not supported? Thanks!

**Comment by McPo** [comment]
My understanding is that this project doesn't build on Android. However you can view/receive the stream from a Windows machine on an Android device or Web Browser (Using the relevant WebRTC API/Libraries) as a regular app (Not Unity).

**Comment by BoyBouw** [comment]
I think you're correct, but then I would suggest to the authors to communicate this much more clearly. It now seems to be a cross-platform lib, which it is not. A confirmation of the above and a possible roadmap from the author would be greatly appreciated!

**Comment by karasusan** [comment]
At the moment, we don't have plans to support RenderStreaming on Android.
We may reconsider this in the future if the demand is strong, so please let us know what you are trying to do.

**Comment by BoyBouw** [comment]
Essentially, we want to communicate simple messages (two-way) and stream video (one-way) between our React Native application and our Android app. The latter is built in Unity, specifically for the Pico 4K 2G VR HMD. One eye-buffer is recorded and streamed to the React-Native application where it is displayed. 

As long as we play our implementation (with custom java signaling server) within the editor, or build for windows, everything works as expected. But as soon as we actually build for Android (note that switching platform does not have the same result)  we get the error.

`The type or namespace name WebRTC does not exist in the namespace Unity`

I hope this clears things up. 

From what I understand about this comment @karasusan,
> At the moment, we don't have plans to support RenderStreaming on Android.
It is possible to communicate simple messages back- and forth? For now, we are unable to build, so we cannot check this on Android.

**Comment by xeep-dev** [comment]
Many Unity apps are already using WebRTC for voice communication and general network data. I'm surprised Android support isn't a priority when many mobile & VR games would hugely benefit from this.

+1 on request, it could totally change the Unity networking landscape

**Comment by lgotkowski** [comment]
We are also in the need of having webrtc support for on mobile platforms like android and ios. In our case we have to stream the unity view from a mobile device to a webapp for remote support.

**Comment by karasusan** [comment]
Thanks, everyone. We understood a need exists for supporting mobile platforms. 
I will plan the roadmap containing this support.

**Comment by sananbintahir** [comment]
Is there any update on android support? We need cross-platform integration with communication and streaming between pc, ios, oculus quest (android), etc

**Comment by FullstackJack** [comment]
How do we get involved as a community to help out with the Android portion? We need this to be cross-platform and deployable to all places Unity targets.

**Comment by devluz** [comment]
Happy to help as well if there is a way to do it. I am already maintaining my own (very limited) version for the past 5 years for the asset WebRTC Video Chat and moving this to a community maintained version would be great

**Comment by karasusan** [comment]
We have a plan to support Android platform as of version 2.4.
This would be released in February.

**Comment by nsmith1024** [comment]
Its now Dec 2020, does this work on Android and IOS yet?

**Comment by karasusan** [comment]
@nsmith1024 
We are working on the iOS platform support and this should be released this month.

**Comment by nsmith1024** [comment]
Awesome, what about Android?

Can your WebRTC encode the video and audio and send it to YouTube Live? 

See this videoon YouTube Live and WebRTC 

https://www.youtube.com/watch?v=htN-gIPOkP0

**Comment by nsmith1024** [comment]
> 
> 
> @nsmith1024
> We are working on the iOS platform support and this should be released this month.

Awesome, what about Android?

Can your WebRTC encode the video and audio from the phone camera and stream it to YouTube Live?

See this video on YouTube Live and WebRTC

https://www.youtube.com/watch?v=htN-gIPOkP0

**Comment by karasusan** [comment]
@nsmith1024
Android support is planned for the next milestone. It might be released in February.

Thanks for sharing the awesome video, I have never seen it.
I think YouTube does not provide an API for live streaming via WebRTC. 
You need to use the other software to convert to the RTMP protocol from WebRTC.
https://stackoverflow.com/questions/61003528/how-to-stream-video-from-my-webrtc-to-facebook-rtmp-server-directly

**Comment by nsmith1024** [comment]
> 
> 
> @nsmith1024
> Android support is planned for the next milestone. It might be released in February.
> 
> Thanks for sharing the awesome video, I have never seen it.
> I think YouTube does not provide an API for live streaming via WebRTC.
> You need to use the other software to convert to the RTMP protocol from WebRTC.
> https://stackoverflow.com/questions/61003528/how-to-stream-video-from-my-webrtc-to-facebook-rtmp-server-directly

Thanks for the reply, I found a link to an article mentioning how to use WebRTC with YouTube, maybe its of use?
https://webrtchacks.com/youtube-does-webrtc-heres-how/

So do you think if i stream WebRTC from my phone camera (Unity app) to my own server, and then on my server use ffmpeg to convert the WebRTC stream in real-time to RTMP, sending that to YouTube live that would work? If so do you know how to do it?

**Comment by karasusan** [comment]
@nsmith1024
I am not sure the combination works as you expect.
We are preparing to release the version which supports iOS platform so you can try to integrate them.

**Comment by karasusan** [comment]
Our team is struggling to develop but the plan is delayed.
Android support is released at the end of March.

**Comment by BoyBouw** [comment]
Great to see the progress being made! I hope we'll see this released soon. 

As I mentioned above, we ultimately want to stream video (one eye buffer) from the Android app (built in Unity) to a web application. Since render streaming is [another package](https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/index.html), I was wondering if this update will include the option to stream video through WebRTC?

**Comment by karasusan** [comment]
> Great to see the progress being made! I hope we'll see this released soon.
> 
> As I mentioned above, we ultimately want to stream video (one eye buffer) from the Android app (built in Unity) to a web application. Since render streaming is [another package](https://docs.unity3d.com/Packages/com.unity.renderstreaming@2.0/manual/index.html), I was wondering if this update will include the option to also stream video through WebRTC?

Unity Render Streaming package depends on the WebRTC package. Therefore, we need to update the URS package after the WebRTC package to add Android support.

**Comment by BoyBouw** [comment]
Thanks! So to answer my question: As I understand it, this update will not be able to stream video through WebRTC from an android device yet. We'll have to wait for an update on the URS package for that, or choose an alternative. 

Please correct me if I'm wrong on the above. If it's correct, however, is there a timeline for the URS android update? I couldn't find it on Github.

**Comment by karasusan** [comment]
@BoyBouw 
I can not say when it will be released clearly, but I think by May.

**Comment by mikeslinkman** [comment]
So I'm a bit confused at this point regarding the status. Is Android support added to the latest 2.4.0 release as indicated in the readme or is it moved back to 2.5.0 and will it be released in June?

**Comment by karasusan** [comment]
@mikeslinkman
I mistook setting the milestone for this issue.
Android support will be released in April.

**Comment by mikeslinkman** [comment]
okay, thanks for clearing that up!

**Comment by sreenaths** [comment]
@karasusan 🙏🏽 🙏🏽 🙏🏽

**Comment by Yusefrahmati** [comment]
@karasusan 

Hi, I have a question, this new version in April contain support ARMv7 android architecture?
 
We need both Android CPU architectures.
