### ISSUE TITLE
@mykr13A ！ @Zxinwei  Now I switch my  Render-Streaming-project from windows platform to WebGL platform,during this time，when I run the project,it hava no compile erros。But when I  attemp to build the project to WebGL,click the Build,the console shows many error CS0246,which messages is "The type or namespace "SignalingManager" could not be found (are you missing a using directive or an assembly reference) "[BUG]: 

### ISSUE THREAD

**Issue by FlyBrid1** [Unity-Technologies/com.unity.webrtc#917]
### Package version

Others

### Environment

```markdown
* Windows:Windows11
* Unity version:2021.3.22
```

### Steps To Reproduce

1.I create the Unity-Render-Streaming Project using Unity 2021.3 on Windows11。
2.When  I switch my  Render-Streaming-project from windows platform to WebGL platform,during this time，when I run the project,it hava no compile erros。But when I  attemp to build the project to WebGL,click the Build,the console shows many error CS0246,which messages is "The type or namespace "SignalingManager" could not be found (are you missing a using directive or an assembly reference) "
3.Looking forward to your reply!!

### Current Behavior

 when I  attemp to build the project to WebGL,click the Build,the console shows many error CS0246,which messages is "The type or namespace "SignalingManager" could not be found (are you missing a using directive or an assembly reference) "

### Expected Behavior

I desired to build the RenderStreaming Project to WebGL Project successfully

**Comment by karasusan** [comment]
Please post the issue to this repository.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues

**Comment by kannan-xiao4** [comment]
@FlyBrid1 Please open an issue in the RenderStreaming repository. I close this issue.
