### ISSUE TITLE
Make com.unity.webrtc work with Wwise

### ISSUE THREAD

**Issue by Nemo-G** [Unity-Technologies/com.unity.webrtc#920]
### Is your feature request related to a problem?

I'm recently looking into a case when clients disable Unity default audio(FMOD) and use [Wwise](https://www.audiokinetic.com/en/products/wwise/) as the only Sound Engine in Unity. So we'd make unity webrtc support Wwise.

### Describe the solution you'd like

I would like two methods added.
1. A GetData method so that I can pull audio from webrtc track into Wwise source plugin
2. A UnsafeSetData method so that I can feed data from Wwise effect plugin into webrtc audio track

See this PR https://github.com/Unity-Technologies/com.unity.webrtc/pull/919 

### Describe alternatives you've considered

I think the two function is pretty straight-forward.

**Comment by karasusan** [comment]
Thanks for making the pull request. I posted the message on the PR. Can you confirm?

**Comment by Nemo-G** [comment]
Hi @karasusan Replied in PR https://github.com/Unity-Technologies/com.unity.webrtc/pull/919

Maybe it is other Unity check failed like NativeContainer instead of Allocator type. I haven't tested against all available types. 

Since the buffer to copy is not managed by Unity, a straight forward marshal copy here can prevent all unnecessary operations like checking, introduce no side effect and deliver right away with no time wasted.

**Comment by karasusan** [comment]
@Nemo-G
Thank you for sharing more detail. I'm going to check **SetData** API implementation and fix this issue.

**Comment by karasusan** [comment]
memo: WRS-481
