### ISSUE TITLE
API Flexibility

### ISSUE THREAD

**Issue by jordan9001** [Unity-Technologies/com.unity.webrtc#94]
The API seems to be set only for streaming game cameras/audio. I am not very comfortable with the API yet, but as far as I can tell if I currently want to stream out the user's webcam video I need to have a camera looking at a rendered WebCamTexture, and if I want to stream out the user's Microphone then the audio would have to pass through the Audio Listener.

This seems a bit rigid to me. Could things be rearranged to allow for more generic ways to create a MediaStream? Is there a better approach to support streaming data from webcams / external devices?

**Comment by karasusan** [comment]
We have never considered the use-case that stream WebCamTexture.
Certainly, WebCamTexture can not stream with current API.
I'm thinking about the proposal.

**Comment by karasusan** [comment]
I am checking that using `WebCamTexture` with the latest WebRTC package but it occurred crash, I need more time to investigate the issue.

**Comment by karasusan** [comment]
We will release the new version of the package until the end of April.
In this version,  new API is added, `VideoStreamTrack` is useful than the old version.

I close this issue once but please reopen it if the problem continues.

**Comment by Felix-N** [comment]
@karasusan is there an example of streaming a WebCamTexture?

**Comment by Felix-N** [comment]
@karasusan as a quick follow up:
I ran into the problem when using a WebCamTexture directly the expected Format did not match. Is there a suggested way of solving that issue?
