### ISSUE TITLE
Calling CreateDataChannel of RTCPeerConnection results in a crash.

### ISSUE THREAD

**Issue by tobias-stein** [Unity-Technologies/com.unity.webrtc#97]
Hi, 
I am trying to create a new data-channel on the server end by calling the following code:

RTCDataChannelInit Options = default;
var DC = this.PC.CreateDataChannel(InDataChannelLabel, ref Options);

this however will result in a editor crash. I will attach the call-stack bellow. 

I am currently working with the 2.0.-preview release version.

Cheers,
Tobi

Stack Trace of Crashed Thread 13924:
0x00007FF9629CADB9 (webrtc) RegisterDebugLog
0x0000026F93A050DD (Unity.WebRTC) Unity.WebRTC.NativeMethods.ContextCreateDataChannel()
0x0000026F93A04C1B (Unity.WebRTC) Unity.WebRTC.Context.CreateDataChannel()
0x0000026F93A04A93 (Unity.WebRTC) Unity.WebRTC.RTCPeerConnection.CreateDataChannel()
0x0000026F93A042AB (Camerafy) Camerafy.Service.WebRTC.WebRTC.AddDataChannel()
0x0000026F8E258013 (Camerafy) Camerafy.Eventing.CamerafyDispatcher.Register()
0x0000026F939FED9B (Camerafy) Camerafy.User.User.Initialize()
0x0000026F939A4CA3 (Camerafy) Camerafy.Application.Session.SpawnUser()
0x0000026F939A4673 (Camerafy) <>c__DisplayClass1_0.<Connect>b__0()
0x0000026F939A41E0 (Camerafy) <>c__DisplayClass5_0.<OnCompleted>b__0()
0x0000026F8E27C629 (UnityEngine.CoreModule) WorkRequest.Invoke()
0x0000026F8E27ACB3 (UnityEngine.CoreModule) UnityEngine.UnitySynchronizationContext.Exec()
0x0000026F8E27A803 (UnityEngine.CoreModule) UnityEngine.UnitySynchronizationContext.ExecuteTasks()
0x0000026F8DBF1985 (mscorlib) System.Object.runtime_invoke_void()
0x00007FF97CEEC11B (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FF97CE72282 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FF97CE7B27F (mono-2.0-bdwgc) mono_runtime_invoke
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B9348262)
0x00007FF7B9348262 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B9341DB1)
0x00007FF7B9341DB1 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B933BA65)
0x00007FF7B933BA65 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B671AC52)
0x00007FF7B671AC52 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B8E0092C)
0x00007FF7B8E0092C (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B8DE90B8)
0x00007FF7B8DE90B8 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B8DE9199)
0x00007FF7B8DE9199 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B8DEE41B)
0x00007FF7B8DEE41B (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B726CE2B)
0x00007FF7B726CE2B (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B726A7EC)
0x00007FF7B726A7EC (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B7BE02CD)
0x00007FF7B7BE02CD (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF7B7BE798F)
0x00007FF7B7BE798F (Unity) (function-name not available)
0x00007FF7BA963652 (Unity) InitializeNvCloth
0x00007FF9DAE17BD4 (KERNEL32) BaseThreadInitThunk
0x00007FF9DB1ACED1 (ntdll) RtlUserThreadStart

**Comment by karasusan** [comment]
Could you attach the code that can reproduce the problem?

**Comment by tobias-stein** [comment]
Hi,

this is pretty much all I am doing
`public bool AddDataChannel(string InDataChannelLabel, DataChannelReady OnReady, DataChannelClosed OnClosed, DataChannelReceived OnRecv)
        {
            // do not open a data channel twice for the same label
            if (this.DataChannels.ContainsKey(InDataChannelLabel))
                return false;

            RTCDataChannelInit Options = default;
            var DC = this.PC.CreateDataChannel(InDataChannelLabel, ref Options);
            if (DC == null)
                return false;

            // store data channel handle
            this.DataChannels.Add(InDataChannelLabel, DC);

            // hook-up events
            DC.OnOpen += () => { if (OnReady != null) { OnReady.Invoke(); } };
            DC.OnClose += () => 
            {
                if (OnClosed != null) { OnClosed.Invoke(); }
                DC.OnMessage = null;
            };
            DC.OnMessage += (bytes) => { if (OnRecv != null) { OnRecv.Invoke(bytes); } };

            return true;
        }`

I called the WebRTC.Init method before. PC is an initialized PeerConnection object.

Cheers,
Tobi

**Comment by tobias-stein** [comment]
Hi, 
another way to reproduce the crash: simply put the following 

RTCDataChannelInit opt = default;
var DC = pc.CreateDataChannel("foo", ref opt);

In the "void OnOffer(ISignaling signaling, DescData e)" method of the RenderStreaming MonoBehaviour.

Cheers,
Tobi.

**Comment by karasusan** [comment]
Fixed this issue and will release the bug-fix version this week. Thanks!
